var commerceItemId;
var fullyLoaded=false;
$(document).ready(function(){fullyLoaded=true;
$(".ajaxButton").live("click",function(e){e.preventDefault();
buttonId=$(this).attr("id");
if(typeof buttonId==="undefined"){buttonId=$(this).attr("rel");
}buttonHref=$(this).attr("href");
openAjaxModal(buttonHref,buttonId);
});
$(".text-button").click(function(e){e.preventDefault();
if($(this).hasClass("fogotpassword")){$("#modalWindow").load("/account/modals/modal-passwordforgot.jsp");
$("#modalWindow").modal({minWidth:400,minHeight:150});
$("#simplemodal-overlay").css("cursor","default");
}if($(this).hasClass("cvv")){$("#modalWindow").load("/checkout/modals/modal-cvv.jsp");
$("#modalWindow").modal({minWidth:600,minHeight:350});
$("#simplemodal-overlay").css("cursor","default");
}if($(this).hasClass("closeIt")){$.modal.close();
$("#modalWindow").empty();
}if($(this).hasClass("pdp-modal-detail")){window.location.href=this;
}if($(this).hasClass("gcinfo")){$("#modalWindow").load("/global/gadgets/modal/modal-gcinfo.jsp");
$("#modalWindow").modal({minWidth:404,minHeight:307});
$("#simplemodal-overlay").css("cursor","default");
}});
$(".vdollars").click(function(e){$("#modalWindow").load("/checkout/modals/modal-dollars.jsp");
$("#modalWindow").modal({minWidth:404,minHeight:180});
$("#simplemodal-overlay").css("cursor","default");
});
$(".close-window, .closs-button").click(function(e){e.preventDefault();
if($(this).hasClass("qv")){var prodId=$(".close-window, .closs-button").attr("href");
if(prodId!=""&&prodId!=undefined){quickViewModal(prodId);
}else{$.modal.close();
$("#modalWindow").empty();
}}else{$.modal.close();
$("#modalWindow").empty();
}});
$(".ordertracking-link").click(function(e){e.preventDefault();
$("#modalWindow").load("/global/modals/modal-trackorder.jsp");
$("#modalWindow").modal({minWidth:340,minHeight:210});
$("#simplemodal-overlay").css("cursor","default");
});
$(".button").click(function(e){if($(this).hasClass("close")){e.preventDefault();
$.modal.close();
$("#modalWindow").empty();
}});
$("#sara_searchInput").val("search keyword or item #");
$("#sara_searchInput").blur(function(e){if($(this).val()==""){$(this).val("search keyword or item #");
}else{$(this).val($(this).val().toLowerCase());
}});
$("#sara_searchInput").focus(function(e){$(this).removeClass("qempty");
if($(this).val()=="Oops! Let's try again, enter search here."||$(this).val()=="search keyword or item #"){$(this).val("");
}});
$("#sara_searchform").submit(function(e){if($("#sara_searchInput").val()==""||$("#sara_searchInput").val()=="Oops! Let's try again, enter search here."||$("#sara_searchInput").val()=="search keyword or item #"){$("#sara_searchInput").val("Oops! Let's try again, enter search here.");
$("#sara_searchInput").addClass("qempty");
e.preventDefault();
}$(this).val($(this).val().toLowerCase());
});
$(".carouselOverlay").click(function(e){$("#modalWindow").load("/carousels/index.html");
$("#modalWindow").modal({minWidth:675,minHeight:400});
$("#simplemodal-overlay").css("cursor","default");
});
$(".sendFriendTextArea").keypress(function(e){var lengthF=$(this).val();
if(lengthF.length>=500){e.preventDefault();
}});
});
function openAjaxModal(buttonHref,buttonId){$(".ui-dialog-content").dialog("destroy");
$("#dialog-message").remove();
if($("#"+buttonId+"Modal").length==0){$("body").append('<div id="'+buttonId+'Modal"></div>');
}$("#"+buttonId+"Modal").load(buttonHref);
var wWidth=$(window).width();
var wHeight=$(window).height();
var popWidth=eval(buttonId).width;
var popHeight=eval(buttonId).height;
var yposition=(wHeight/2)-((popWidth*0.7)/2);
var xposition=(wWidth/2)-(popWidth/2);
$("#"+buttonId+"Modal").dialog({height:"auto",minWidth:eval(buttonId).width,minHeight:eval(buttonId).height,modal:true,bgiframe:true,draggable:true,resizable:false,autoOpen:true,closeOnEscape:true,hide:"fade",show:"fade",position:[xposition,yposition]});
}function showEpressCheckoutInfo(productId){if(productId!=""){$.modal.close();
$("#modalWindow").empty();
$("#modalWindow").load("/checkout/modals/modal-expressco-info.jsp?productId="+productId);
}else{$("#modalWindow").load("/checkout/modals/modal-expressco-info.jsp");
}$("#modalWindow").modal({minWidth:635,minHeight:280});
$("#simplemodal-overlay").css("cursor","default");
}function validateState(country){$("#state").html("");
$("#state").load("/global/statePicker.jsp?countryCode="+escape(country));
}function validateStateModal(country){$("#state-modal").html("");
$("#state-modal").load("/global/statePicker.jsp?idOverride=state-modal&countryCode="+escape(country));
}function validateAndSetState(countryCode,stateCode){$("#state").html("");
$("#countryPicker").load("/global/statePicker.jsp?countryCode="+escape(countryCode),function(){jQuery(document).ready(function(){setSelectedState(countryCode,stateCode);
changeSelectColor();
});
});
}function submitProfileRegistration(){var prov=$("#province_val").val();
var state=$("#state").find(":selected").val();
if(state==""&&prov!=""){if($("#province").is(":visible")){$("#state").append('<option value="'+prov+'" selected="true">'+prov+"</option>");
}}$("#register").submit();
}function submitAddEditAddress(){prov=$("#province_val").val();
state=$("#state").find(":selected").val();
if(state==""&&prov!=""){if($("#province").is(":visible")){$("#state").append('<option value="'+prov+'" selected="true">'+prov+"</option>");
}}$(this).submit();
}function validateAndSetStateWithOverrideStates(countryCode,stateCode,overrideStates){$("#state").html("");
$("#state").append('<option value="">Select</option>');
$("#countryPicker").load("/includes/statePicker.jsp?countryCode="+escape(countryCode)+"&overrideStates="+escape(overrideStates),function(){jQuery(document).ready(function(){setSelectedState(countryCode,stateCode);
});
});
}function stateProvinceSync(){prov=$("#province_val").val();
state=$("#state").find(":selected").val();
if(state==""&&prov!=""){if($("#province").is(":visible")){$("#state").append('<option value="'+prov+'" selected="true">'+prov+"</option>");
}}}function setSelectedState(countryVal,stateVal){var slId="";
if(countryVal!=""&&stateVal!=""){slId="state";
}if(slId!=""){$("#"+slId+" option:selected").removeAttr("selected");
$("#"+slId+" option[value="+stateVal+"]").attr("selected","selected");
}}function showPasswordForgot(){$("#modalWindow").load("/account/modals/modal-passwordforgot.jsp");
$("#modalWindow").modal({minWidth:470,minHeight:210});
$("#simplemodal-overlay").css("cursor","default");
}function accountConf(productId){$("#modalWindow").load("/catalog/modals/modal-completelook.jsp?productId="+productId);
$("#modalWindow").modal({minWidth:650,minHeight:600});
$("#simplemodal-overlay").css("cursor","default");
}function completeLook(productId){$("#modalWindow").load("/global/modals/modal-accountcreation.jsp");
$("#modalWindow").modal({minWidth:350,minHeight:20});
$("#simplemodal-overlay").css("cursor","default");
}function editeGiftItem(productId){$("#modalWindow").load("/checkout/modals/modal-editgc-egc.jsp?productId="+productId);
$("#modalWindow").modal({minWidth:640,minHeight:330});
$("#simplemodal-overlay").css("cursor","default");
}function editGiftItem(productId){$("#modalWindow").load("/checkout/modals/modal-editgc-gcc.jsp?productId="+productId);
$("#modalWindow").modal({minWidth:630,minHeight:200});
$("#simplemodal-overlay").css("cursor","default");
}function quickView(productId,colorCode,name,brand){if(fullyLoaded){$("#modalWindow").load("/catalog/modals/modal-quickview.jsp?productId="+productId+"&colorCode="+encodeURI(colorCode));
$("#modalWindow").modal({minWidth:630,minHeight:460,fixed:false});
$("#simplemodal-overlay").css("cursor","default");
callCustomEvent("quickLook",productId,name,brand);
}}function editItem(productId,skuId,size,colorCode,qty,commeceItemId,brand,name){$("#modalWindow").load("/cart/modals/modal-edit-product.jsp?productId="+productId+"&skuId="+skuId+"&size="+encodeURI(size)+"&colorCode="+encodeURI(colorCode)+"&qty="+qty+"&commeceItemId="+commeceItemId+"&isedit=true");
$("#modalWindow").modal({minWidth:700,minHeight:605,fixed:false});
$("#simplemodal-overlay").css("cursor","default");
callCustomEvent("editCart",productId,name,brand);
}function sendToFriend(productId,ismodal,defaultColorCode){var color=$("#selectedColor"+productId).val();
var colorCode=$("#selectedColorCode"+productId).val();
if(colorCode=="false"){colorCode=defaultColorCode;
}$("#modalWindow").load("/pdp/modals/modal-tellafriend.jsp?productId="+productId+"&color="+encodeURI(color)+"&colorCode="+colorCode+"&ismodal="+ismodal);
$("#modalWindow").modal({minWidth:870,minHeight:485});
$("#simplemodal-overlay").css("cursor","default");
}function openCompleteLooks(productId,size,type){var colorToDisplay=$("#hiddenColor").html();
$("#modalWindow").load("/catalog/modals/modal-completelook.jsp?productId="+productId+"&size="+encodeURI(size)+"&colorToDisplayOutfit="+encodeURI(colorToDisplay),function(){var currentHeight=$("#modalWindow").height();
$("#modalWindow").modal({minWidth:645,minHeight:currentHeight,position:[10],escClose:false});
$("#simplemodal-overlay").css("cursor","default");
if(typeof type=="undefined"){$(".simplemodal-container").css({"position":"absolute"});
}});
}function addQuickshopToWishlist(){var validatedQty=true;
var validatedSize=true;
var missingQty=false;
var missingSize=false;
var productId="";
var skuId="";
var my_form=$("#addToCartOptionsQuickshop");
$.each($("input, select",my_form),function(i,v){var theElement=$(v);
var theValue=theElement.val();
var inputType=theElement.attr("type");
var vclass=theElement.attr("class");
var inputId=theElement.attr("id");
if(!(typeof inputId==="undefined")&&inputId.substring(0,9)=="productId"){missingSize=false;
missingQty=false;
productId=theValue;
}if(!(typeof inputId==="undefined")&&inputId.substring(0,13)=="catalogRefIds"){missingSize=false;
missingQty=false;
skuId=theValue;
}if(!(typeof inputId==="undefined")&&inputId=="sizeOptions"+productId&&theValue==""){missingSize=true;
validatedSize=false;
}if(!(typeof inputId==="undefined")&&inputId=="prodQtySelection"){if(theValue==""){missingQty=true;
validatedQty=false;
}else{$("#giftListCatalogRefIds"+productId).val(skuId);
$("#giftListQuantity"+productId).val(theValue);
}}});
if(validatedQty&&validatedSize){dataString=$("#addProductToGiftListQuickshop").serialize();
$.ajax({type:"POST",url:"/wishlist/gadgets/validateAddToGiftlist.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="false"){document.location.href="/wishlist/";
}else{document.location.href="/wishlist/";
}}});
}else{document.location.href="/wishlist/";
}}function addQuickshopToCart(){var validatedQty=true;
var validatedSize=true;
var missingQty=false;
var missingSize=false;
var productId="";
var my_form=$("#addToCartOptionsQuickshop");
$.each($("input, select",my_form),function(i,v){var theElement=$(v);
var theValue=theElement.val();
var inputType=theElement.attr("type");
var vclass=theElement.attr("class");
var inputId=theElement.attr("id");
if(!(typeof inputId==="undefined")&&inputId.substring(0,9)=="productId"){missingSize=false;
missingQty=false;
productId=theValue;
}if(!(typeof inputId==="undefined")&&inputId=="sizeOptions"+productId&&theValue==""){missingSize=true;
validatedSize=false;
}if(!(typeof inputId==="undefined")&&inputId=="prodQtySelection"){if(theValue==""){missingQty=true;
validatedQty=false;
}else{$("#qty"+productId).val(theValue);
}}});
var skuId=$("#catalogRefIds"+productId).val();
var brand=$("#brand").val();
if(brand=="JST"){brand="justice";
}else{brand="brothers";
}if(validatedQty&&validatedSize){dataString=$("#addToCartOptionsQuickshop").serialize();
$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){document.location.href="/cart/";
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}}else{document.location.href="/cart/";
}callCustomEvent("cartAdd",productId,skuId,brand);
}});
}else{document.location.href="/cart/";
}}function addcompleteLook(){dataString=$("#addToCartOptionsCmplLook").serialize();
$("#clookAddItemTocartError").html("");
$("#clookAddItemTocartError").hide();
var validatedQty=true;
var validatedSize=true;
var missingQty=false;
var missingSize=false;
var my_form=$("#addToCartOptionsCmplLook");
var qty=parseInt(0);
$.each($("input, select",my_form),function(i,v){var theElement=$(v);
var theValue=theElement.val();
var inputType=theElement.attr("type");
var vclass=theElement.attr("class");
var inputId=theElement.attr("id");
if(inputId.substring(0,18)=="clookCatalogRefIds"){missingSize=false;
missingQty=false;
}if(inputType=="select-one"&&theValue==""){missingSize=true;
validatedSize=false;
}if(vclass=="qty"&&theValue==0){missingQty=true;
validatedQty=false;
}else{if(vclass=="qty"&&theValue!=0){qty+=parseInt(theValue);
}}});
if(validatedQty&&validatedSize){$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to add item(s) to cart";
$("#clookAddItemTocartError").show();
$("#clookAddItemTocartError").html(message);
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){$.modal.close();
$("#modalWindow").empty();
cartExpand();
setTimeout(function(){cartContract();
},5000);
$.getJSON("/minicart/gadgets/totalCommerceItemCount.jsp",function(json){var count=json.cartcount;
var total=json.carttotal;
$("#cartCount").html(count);
$("#cartTotal").html(total);
});
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}}}}});
}else{$("#clookAddItemTocartError").show();
if(!validatedQty&&!validatedSize){$("#clookAddItemTocartError").html("Please specify quantity and size");
}else{if(!validatedQty){$("#clookAddItemTocartError").html("Please enter quantity");
}else{$("#clookAddItemTocartError").html("Please select size");
}}$("#simplemodal-container").css({"width":645,"height":"auto"});
}}function submitEmailFriendSubscriptions(productId,color,colorCode,ismodal){subject=$("#friendSubject").val();
sender=$("#friendNameFrom").val();
newSubject=subject.replace("senderName",sender);
$("#friendSubject").val(newSubject);
dataString=$("#emailForm").serialize();
$.ajax({type:"POST",cache:false,url:"/global/gadgets/validateSendMail.jsp",data:dataString,dataType:"json",success:function(data){if(data.error=="true"){$.ajax({type:"GET",cache:false,url:"/pdp/gadgets/tellaFriendErrors.jsp",dataType:"html",async:false,success:function(data2){$("#friendEmail").removeClass("error");
$("#friendNameFrom").removeClass("error");
$("#simplemodal-container").css("height","550px");
$("#divForErrors").html(data2);
if(data2.indexOf("email")!==-1){$("#friendEmail").addClass("error");
}if(data2.indexOf("name")!==-1){$("#friendNameFrom").addClass("error");
}}});
}else{if(data.error=="false"){$.modal.close();
$("#modalWindow").empty();
$("#modalWindow").load("/pdp/modals/modal-email-friend-thanks.jsp?productId="+productId+"&color="+encodeURI(color)+"&colorCode="+colorCode+"&ismodal="+ismodal);
$("#modalWindow").modal({minWidth:400,maxWidth:410,maxHeight:250,minHeight:110});
callCustomEvent("emailFriend","","","");
}}}});
}function giftCardExpireOverlay(callBack){$.modal.close();
$("#modalWindow").load("/giftcards/modals/modal-gcexpired.jsp",function(){$("#closeGCA,#closeGCB").click(function(event){event.preventDefault();
callBack();
});
});
$("#modalWindow").modal({minWidth:400,maxWidth:410,maxHeight:250,minHeight:110});
}function sendWishlist(wishlist){$("#modalWindow").load("/wishlist/modals/modal-wishlistEmail.jsp");
$("#modalWindow").modal({minWidth:370,minHeight:300});
$("#simplemodal-overlay").css("cursor","default");
}function submitWishlistSubscriptions(wishlist){dataString=$("#emailForm").serialize();
$.ajax({type:"POST",url:"/global/gadgets/validateSendMail.jsp",data:dataString,dataType:"json",success:function(data){if(data.error=="true"){$("#modalWindow").load("/wishlist/modals/modal-wishlistEmail.jsp");
$(".simplemodal-container").css({"position":"absolute","overflow":"scroll","overflow-x":"hidden"});
}else{if(data.error=="false"){$.modal.close();
$("#modalWindow").load("/pdp/modals/modal-email-friend-thanks.jsp");
$("#modalWindow").modal({maxWidth:320,maxHeight:100,minHeight:100});
}}}});
}function expressCheckoutLogin(productId,modal){$("#addItemAndExpressCheckout").val("true");
var validateSelection=validateProductSelection(productId);
if(!validateSelection){setError("Selection Required",false,productId);
}else{var errorQuantity=checkSKUQuality(productId);
if(""!=errorQuantity){setError(errorQuantity,false,productId);
}else{var skuId=$("#catalogRefIds"+productId).val();
var quantity=$("#prodQtySelection").val();
if(typeof modal!="undefined"&&modal){$.modal.close();
$("#modalWindow").empty();
$("#modalWindow").load("/checkout/modals/modal-expressco-signup.jsp",{productId:productId,skuId:skuId,quantity:quantity,modal:modal});
$("#modalWindow").modal({minWidth:635,minHeight:260});
$("#simplemodal-overlay").css("cursor","default");
}else{$("#modalWindow").load("/checkout/modals/modal-expressco-signup.jsp",{productId:productId,skuId:skuId,quantity:quantity});
$("#modalWindow").modal({minWidth:635,minHeight:260});
$("#simplemodal-overlay").css("cursor","default");
}}}}function addGiftOptions(shippingGroupId){$.ajax({type:"POST",url:"/checkout/gadgets/setgiftwrap.jsp?shipGrpId="+shippingGroupId,data:"",dataType:"text",success:function(obj){$("#modalWindow").load("/checkout/modals/modal-giftwrap.jsp?shippingGroupId="+shippingGroupId);
$("#modalWindow").modal({minWidth:390,minHeight:180});
$("#simplemodal-overlay").css("cursor","default");
}});
}function viewModalShoeSize(productId,type,catId){if(productId!=""){$.modal.close();
}$("#modalWindow").load("/global/modals/modal-shoesize.jsp?productId="+productId+"&type="+type+"&catId="+catId);
$("#modalWindow").modal({minWidth:710,minHeight:484});
$("#simplemodal-overlay").css("cursor","default");
}function viewModalShoeSizeEx(productId,type,catId,skuSize,selectedColor,qty,ci){if(productId!=""){$.modal.close();
}$("#modalWindow").load("/global/modals/modal-shoesize.jsp?productId="+productId+"&type="+type+"&catId="+catId+"&skuSize="+encodeURI(skuSize)+"&selectedColor="+encodeURI(selectedColor)+"&qty="+qty+"&ci="+ci);
$("#modalWindow").modal({minWidth:710,minHeight:484});
$("#simplemodal-overlay").css("cursor","default");
}function displayOrderDetails(orderId){var height=$("#"+orderId+"").height();
if(height==0){$("#"+orderId+"").load("/account/gadgets/accountOrderItemDetails.jsp?orderId="+orderId);
$("#"+orderId+"").css("height","100%");
$("#"+orderId+"").animate({"height":"100%"},100);
$("#"+orderId+"").fadeIn("fast");
$("#btn_"+orderId).attr("class","orderHideDetails");
$("#btn_"+orderId).attr("title","Hide Order Details");
}else{$("#"+orderId+"").animate({"height":0},100);
$("#"+orderId+"").fadeOut("fast");
$("#"+orderId+"").html("");
$("#btn_"+orderId).attr("class","orderViewDetails");
}}function quickViewModal(productId){$.modal.close();
$("#modalWindow").empty();
quickView(productId);
}function quickViewModal(productId,color){$.modal.close();
$("#modalWindow").empty();
quickView(productId,color);
}function sizeModal(){$.modal.close();
$("#modalWindow").empty();
}function loadShippingRatesModal(){$("#modalWindow").load("/checkout/modals/modal-shippingRates.jsp");
$("#modalWindow").modal({minWidth:630,minHeight:630,position:[10+f_scrollTop()]});
$(".simplemodal-container").css({"position":"absolute","overflow":"scroll","overflow-x":"hidden"});
$("#simplemodal-overlay").css("cursor","default");
}function displayCreditCardBillingAddress(billAddrSelectedId){$("#selectedBillingAddress").load("/checkout/gadgets/billingAddressInfo.jsp?billAddrSelectedId="+billAddrSelectedId);
}function displayBillingAddress(selectedKey){$("#selectedBillingAddress").load("/checkout/gadgets/billingAddressInfo.jsp?nickname="+escape(selectedKey));
}function displayCreditCardAddress(selectedKey){$("#selectedCreditCardAddress").load("/checkout/gadgets/creditCardInfo.jsp?nickname="+escape(selectedKey));
}function editItemModal(productId,skuId,size,color,qty,commeceItemId){$.modal.close();
$("#modalWindow").empty();
editItem(productId,skuId,size,color,qty,commeceItemId);
}function seeMyItems(itemCount){$("#modalWindow").load("/catalog/modals/modal-rv.jsp",function(){var elmHeight=$(".recent").height()+20;
var elemWidth=$(".recent").width()+20;
$("#modalWindow").modal({minWidth:elemWidth,minHeight:elmHeight});
$("#simplemodal-overlay").css("cursor","default");
});
}function removeGiftwrap(removeItemid){$("#rmGiftId").val(removeItemid);
dataString=$("#updateGiftWrap").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateGiftItem.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="false"){$("#fullCart").load("/checkout/gadgets/cartFull.jsp");
$("#shippingInfo").load("/checkout/gadgets/selectedShippingInfo.jsp");
}}});
}function addGiftWrap(){var shippingGroupId=$("#shipGrpId").val();
dataString=$("#giftWrapMsg").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){$("#modalWindow").load("/checkout/modals/modal-giftwrap.jsp?shippingGroupId="+shippingGroupId);
$("#modalWindow").modal({minWidth:390,minHeight:200});
$(".simplemodal-container").css({"height":"200px"});
$("#simplemodal-overlay").css("cursor","default");
}else{if(obj.error=="false"){$.modal.close();
$("#fullCart").load("/checkout/gadgets/cartFull.jsp");
}}}});
}function shippingAddress(nickNname,itemId){$.ajaxSettings.cache=false;
if(nickNname!=""){if(nickNname=="new"){$("#modalWindow").load("/checkout/modals/modal-address.jsp?commerceItemId="+itemId);
$("#modalWindow").modal({minWidth:430,minHeight:410});
$("#simplemodal-overlay").css("cursor","default");
}else{$("#addressNickname").val(nickNname);
$("#commerceItemId").val(itemId);
dataString=$("#changeShippingInfo").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){$.get("/checkout/gadgets/selectedShippingInfo.jsp",function(data){var availableShippingMethods=$(data).find("#availableShippingMethods");
$("#availableShippingMethods").html(availableShippingMethods);
var addressInfo=$(data).find("#addressInfo");
$("#addressInfo").html(addressInfo);
$("#fullCart").load("/checkout/gadgets/cartItemsBody.jsp");
});
}});
}}}function changeShippingAddress(nickNname){$.blockUI({message:null,overlayCSS:{opacity:0}});
$.ajaxSettings.cache=false;
if(nickNname!=""){$("#shippingAddressNickname").val(nickNname);
dataString=$("#changeShippingAddress").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){$.get("/checkout/gadgets/selectedShippingInfo.jsp",function(data){var availableShippingMethods=$(data).find("#availableShippingMethods");
$("#availableShippingMethods").html(availableShippingMethods);
var addressInfo=$(data).find("#addressInfo");
$("#addressInfo").html(addressInfo);
var shippingMethodSg=$("#shippingMethodSg").val();
var shippingSelected=false;
$("#availableShippingMethods input[type='radio']").each(function(){var shippingMethodOption=$(this).val();
if(shippingMethodSg===shippingMethodOption){shippingSelected=true;
}});
if(shippingSelected==false){var newShippingMethod=$("#availableShippingMethods input[type='radio']").eq(0).attr("id");
$("#"+newShippingMethod).attr("checked","checked");
changeShippingMethod("#"+newShippingMethod,nickNname,"");
}else{$("#fullCart").load("/checkout/gadgets/cartItemsBody.jsp");
}$.unblockUI();
}).error(function(){$.unblockUI();
});
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}}function addNewShippingAddress(){dataString=$("#addnewShippAddres").serialize();
var commerceItemId=$("#commItemId").val();
var addressNickname=$("#nickName").val();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){$.ajax({type:"POST",url:"/global/gadgets/modal/modal-address.jsp?commerceItemId="+commerceItemId+"&shipToAddressName="+addressNickname,data:dataString,dataType:"html",success:function(data){$("#modalWindow").html(data);
}});
$("#modalWindow").modal({minWidth:430,minHeight:410});
$("#simplemodal-overlay").css("cursor","default");
}else{if(obj.error=="false"){$("#shippingInfo").load("/checkout/gadgets/selectedShippingInfo.jsp",function(){$("#fullCart").load("/checkout/gadgets/cartItemsBody.jsp");
});
$.modal.close();
$("#modalWindow").empty();
}}}});
}function facetSelection(categoryId,facetTrail,ques,showPrd,hideCatFacets,refinId,facetId,sourceCategoryId,type){var selection=$("#selectionSort").val();
if(null==type||""==type){$.ajax({type:"GET",url:"/search/gadgets/searchPagination.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,ques:ques,showProductNavigation:showPrd},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchNav.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,ques:ques,showProductNavigation:showPrd,hideCategoryFacets:hideCatFacets},success:function(data){$("div#searchNav").html(data);
},async:false,dataType:"text"});
$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategorySearchItemBody.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,ques:ques},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/sortBy.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,ques:ques,showProductNavigation:showPrd,selectedOption:selection},success:function(data){$("dl#sortingHeader").html(data);
},async:false,dataType:"html"});
removeRepeatedDivs();
$("#selectionSort").trigger("onchange");
}else{$.ajax({type:"GET",url:"/catalog/gadgets/ajaxBrandItemsBody.jsp",data:{scatId:sourceCategoryId,categoryId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchPaginationAttr.jsp",data:{categoryId:categoryId,scatId:sourceCategoryId,hiddenfacetId:facetId,refElemRepId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchNav.jsp",data:{categoryId:categoryId,scatId:sourceCategoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type,showProductNavigation:"true",hideCategoryFacets:hideCatFacets},success:function(data){$("div#searchNav").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/sortByAttr.jsp",data:{categoryId:categoryId,catId:sourceCategoryId,facetId:facetId,refinId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type,showProductNavigation:"true",hideCategoryFacets:hideCatFacets},success:function(data){$("dl#sortingHeader").html(data);
},async:false,dataType:"html"});
}return false;
}function removeRepeatedDivs(){$("div#ajaxCategoryDisplay").each(function(index){if(index!=0){$(this).remove();
}});
}function nextPage(categoryId,facetTrail,startIndex,pageNum,howMany,ques,sortOrder,showProductNavigation){$.ajax({type:"GET",url:"/search/gadgets/searchPagination.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,showProductNavigation:showProductNavigation},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchNav.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,showProductNavigation:showProductNavigation},success:function(data){$("div#searchNav").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategorySearchItemBody.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,startIndex:startIndex,pageNum:pageNum,howMany:howMany,ques:ques,sortOrder:sortOrder,showProductNavigation:showProductNavigation},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
return false;
}function nextPageBrands(categoryId,facetTrail,startIndex,pageNum,howMany,ques,sortOrder,refId,facetId,type){$.ajax({type:"GET",url:"/catalog/gadgets/ajaxBrandItemsBody.jsp",data:{scatId:categoryId,q_facetTrail:facetTrail,startIndex:startIndex,pageNum:pageNum,howMany:howMany,ques:ques,sortOrder:sortOrder,refinementId:refId,facetId:facetId,type:type},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
return false;
}function sortResult(categoryId,facetTrail,sortOrder,ques){if(sortOrder!="reset"){$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategorySearchItemBody.jsp",data:{categoryId:categoryId,q_facetTrail:facetTrail,sortOrder:sortOrder,ques:ques},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
removeRepeatedDivs();
}else{if(categoryId==undefined){window.location.href="/catalog/categoryPage.jsp?categoryId="+categoryId;
}else{location.reload();
}}}function addToGiftList(listId,prodId,modal,giftSku,itemsQty){var sku=giftSku;
var qty=itemsQty;
if(sku==""||sku==null){sku=$("#catalogRefIds"+prodId).val();
}if(qty==""){qty=parseInt($("#prodQtySelection").val());
}$("#giftListId").val(listId);
$("#giftListQuantity").val(qty);
$("#giftListSkuId").val(sku);
$("#giftListProdId").val(prodId);
var validateSelection=validateProductSelection(prodId);
if(!validateSelection&&sku==null){setError("Selection Required",false,prodId);
}else{if(validateProductSelection()&&qty>0){$("#giftListId").val(listId);
if(itemsQty==""||itemsQty==null||itemsQty==0){$("#giftListQuantity").val($("#prodQtySelection").val());
}else{$("#giftListQuantity").val(itemsQty);
}$("#giftListSkuId").val(sku);
dataString=$("#addPorductToGiftList"+prodId).serialize();
$.ajax({type:"POST",url:"/giftregistry/modals/validateAddToGiftlist.jsp",data:dataString,dataType:"json",success:function(obj){if(modal="true"){$.modal.close();
$("#modalWindow").empty();
}window.location.href="/giftregistry/viewGiftlist.jsp?giftlistId="+listId+"&productId="+prodId;
}});
}else{setError("Selection Required",false);
}}}function openGiftList(prodId,skuId,ismodal){var sku=skuId;
if(sku==""){sku=$("#catalogRefIds"+prodId).val();
}var qty=parseInt($("#prodQtySelection").val());
var validateSelection=validateProductSelection(prodId);
if(!validateSelection){setError("Selection Required",false,prodId);
}else{$("#modalWindow").load("/giftregistry/modals/modal-chosegiftlist.jsp?productId="+prodId+"&skuID="+sku+"&ismodal="+ismodal+"&qty="+qty,function(){var currentHeight=$("#modalWindow").height();
$("#modalWindow").modal({minWidth:630,minHeight:currentHeight});
$("#simplemodal-overlay").css("cursor","default");
});
}}function createNewGiftListAddItem(productId,giftSku){var qty=parseInt($("#prodQtySelection").val());
if(validateProductSelection()&&qty>0){if(productId==""||productId==undefined){var prodId=$("#catalogRefProdId").val();
}else{var prodId=productId;
}if(giftSku==""||giftSku==undefined){var skuId=$("#catalogRefIds"+prodId).val();
}else{var skuId=giftSku;
}window.location.href="/account/giftlist?qty="+qty+"&sku="+skuId+"&productId="+prodId;
}else{setError("Selection Required ",false);
}}function openGiftCardNumber(){$("#modalWindow").load("/giftcards/modals/modal-giftCardNum.jsp");
$("#modalWindow").modal({minWidth:665,minHeight:540});
$("#simplemodal-overlay").css("cursor","default");
}function openCVV(){$("#modalWindow").load("/checkout/modals/modal-cvv.jsp");
$("#modalWindow").modal({minWidth:665,minHeight:410});
$("#simplemodal-overlay").css("cursor","default");
}function addItemToWishList(wishlist_id,product_id,sku_id,itemsQty){var qty=itemsQty;
if(qty==""||qty==undefined){qty=parseInt($("#prodQtySelection").val());
}var sku=sku_id;
if(sku==""||sku==null){sku=$("#catalogRefIds"+product_id).val();
}$("#giftListId").val(wishlist_id);
$("#giftListSkuId").val(sku);
$("#giftListProdId").val(product_id);
var validateSelection=validateProductSelection(product_id);
if(!validateSelection){setError("Please select size",false,product_id);
}else{if(validateProductSelection()&&qty>0){$("#addPorductToGiftList"+product_id+" #giftListId").val(wishlist_id);
$("#addPorductToGiftList"+product_id+" #giftListQuantity").val(qty);
$("#addPorductToGiftList"+product_id+" #giftListSkuId").val(sku);
dataString=$("#addPorductToGiftList"+product_id).serialize();
$.ajax({type:"POST",url:"/wishlist/gadgets/validateAddToGiftlist.jsp",data:dataString,dataType:"json",success:function(obj){$.getJSON("/wishlist/gadgets/wishlistItemsCount.jsp?r="+Math.random(),function(json){var count=json.wishlistcount;
$("#wishlistCount").html(count);
addToWishlist(product_id,$("#selectedColorCode"+product_id).val());
});
colorCodeProduct=$("#selectedColorCode"+product_id).val();
updateCertonaTags(product_id,colorCodeProduct,"wishlist");
}});
}else{setError("Selection Required",false);
}}}function validateWishlistSelection(prodId){var qty=parseInt($("#prodQtySelection").val());
var validateSelection=validateProductSelection(prodId);
if(!validateSelection||qty<0){setError("Please select size",false,prodId);
}else{var skuId=$("#catalogRefIds"+prodId).val();
window.location.href="/account/?giftItemQty="+qty+"&skuIdWishlist="+skuId+"&productIdWishlist="+prodId;
}}function validateGiftlistSelection(prodId){var qty=parseInt($("#prodQtySelection").val());
var validateSelection=validateProductSelection(prodId);
if(!validateSelection||qty<0){setError("Selection Required ",false,prodId);
}else{var skuId=$("#catalogRefIds"+prodId).val();
window.location.href="/account/signin.jsp?productIdGiftlist="+prodId+"&skuIdGiftlist="+skuId+"&giftItemQty="+qty;
}}function addItemToWishListCart(wishlist_id,product_id,isModal,sku_Id,qty){$("#giftListId").val(wishlist_id);
$("#giftListQuantity").val(qty);
$("#giftListSkuId").val(sku_Id);
$("#giftListProdId").val(product_id);
dataString=$("#addProductToGiftListCart").serialize();
$.ajax({type:"POST",url:"/giftregistry/modals/validateAddToGiftlist.jsp",data:dataString,dataType:"json",success:function(data){wlExpand();
setTimeout(function(){wlContract();
},5000);
$.ajax({type:"POST",url:"/cart",data:null,dataType:"html",success:function(data2){$("#wishlistCount").html($("#wishlistCount",data2).html());
}});
}});
}function addToWishlist(productId,colorCode){$.modal.close();
$("#modalWindow").load("/wishlist/modals/modal-wishlistadd.jsp?productId="+productId+"&colorCode="+colorCode);
$("#modalWindow").modal({minWidth:850,minHeight:436});
$("#simplemodal-overlay").css("cursor","default");
}function linkToWishlist(){window.location.href="/account/wishlist";
}function checkAgeVerified(){var ageVerified=document.getElementById("regAgeVerified");
var submitButton=document.getElementById("regSubmitButton");
if(ageVerified.checked){submitButton.disabled=false;
}else{submitButton.disabled=true;
}}function checkBalance(flag){$("#modalWindow").load("/giftcards/modals/modal-gcbalance.jsp?flag="+flag);
$("#modalWindow").modal({minWidth:320,minHeight:120});
$("#simplemodal-overlay").css("cursor","default");
}function checkAgain(){$("#modalWindow").load("/giftcards/modals/modal-gcbalance.jsp");
$("#modalWindow").modal({minWidth:320,minHeight:120});
$("#simplemodal-overlay").css("cursor","default");
}function checkBalanceSubmit(flag){dataString=$("#gc_balance_check").serialize();
$.ajax({type:"POST",url:"/giftcards/gadgets/validateGiftBalance.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){$.modal.close();
$("#modalWindow").load("/giftcards/modals/modal-gcbalance.jsp?flag="+flag);
$("#modalWindow").modal({minWidth:320,minHeight:170});
$("#simplemodal-overlay").css("cursor","default");
}else{if(obj.error=="false"){if(flag=="ecard"){window.location.href="/gift-cards/e-gift-card/balance";
}else{window.location.href="/gift-cards/check-balance";
}}}}});
}function showErrorMessage(elementId){if($("#error_field")[0].innerHTML!="Complete Required Fields"){$("#error_field")[0].innerHTML="Complete Required Fields";
$("#error_field").css({"display":"block"});
}$(elementId).addClass("error");
}function showSpecialErrorMessage(message,elementId){if($("#error_field")[0].innerHTML!=message){$("#error_field")[0].innerHTML=message;
$("#error_field").css({"display":"block"});
}$(elementId).addClass("error");
}function purchaseWithPurchaseView(productId,skuId,closeModal){if(typeof closeModal!="undefined"&&closeModal){$.modal.close();
}$("#modalWindow").load("/checkout/modals/modal-pwp.jsp?productId="+productId+"&skuId="+skuId);
$("#modalWindow").modal({minWidth:530,minHeight:250,overlayClose:true});
$("#simplemodal-overlay").css("cursor","default");
}function addSKUToCard(productId){var validateSelection=validateProductSelection(productId);
if(!validateSelection){setError("Selection Required",false,productId);
}else{var errorQuantity=checkSKUQuality(productId);
if(""!=errorQuantity){setError(errorQuantity,false,productId);
if($("#modalWindow:visible").length>0){$("#simplemodal-container").height(310);
}}else{dataString=$("#addToCartOptions"+productId+"").serialize();
$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to add item to cart";
setError(message,false,productId,clook);
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){window.location.href="/global/gadgets/closePWP.jsp";
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}}}}});
}}}function removeItemFromCart(currentItem,brand,productId,skuId){$("#removeItemId").val(currentItem);
dataString=$("#removeItemFromCartPage").serialize();
$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to remove item from cart";
$(".boxTitle").append(setError(message,false,currentItem,clook));
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){location.reload();
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}callCustomEvent("cartRemove",productId,skuId,brand);
}}}});
}function removeItemFromMiniCart(currentItem){var expand=false;
$("#removeItemId").val(currentItem);
dataString=$("#removeItemFromCartPage").serialize();
$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to remove item from cart";
setError(message,false,productId,clook);
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){cartExpand();
setTimeout(function(){cartContract();
},5000);
$.getJSON("/minicart/gadgets/totalCommerceItemCount.jsp?r="+Math.random(),function(json){var count=json.cartcount;
var total=json.carttotal;
$("#cartCount").html(count);
$("#cartTotal").html(total);
if(count==0){$("#mini_cart_button_holder").removeClass("cartItems");
}});
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{location.reload();
callBack();
}}}}});
}function removeSleeveFromMiniCart(commerceItemId,sleeveQuantity,holderProductId){var commerceItemQuantity=parseInt($("#updateGiftCardQuantity input[name="+commerceItemId+"]").val());
var updatedCommerceItemQuantity=commerceItemQuantity-sleeveQuantity;
$("#updateGiftCardQuantity input[name="+commerceItemId+"]").val(updatedCommerceItemQuantity);
$("#updateGiftCardQuantity input[name=holderProductId]").val(holderProductId);
$("#updateGiftCardQuantity input[name=giftCardCommerceItemId]").val(commerceItemId);
dataString=$("#updateGiftCardQuantity").serialize();
$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to remove item from cart";
setError(message,false,productId,clook);
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){cartExpand();
$.getJSON("/minicart/gadgets/totalCommerceItemCount.jsp?r="+Math.random(),function(json){var count=json.cartcount;
var total=json.carttotal;
$("#cartCount").html(count);
$("#cartTotal").html(total);
});
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}}}}});
}function closePWP(){window.location.href="/global/gadgets/closePWP.jsp";
}function addViewGiftWrap(messageId,checkId,sgid,closeModal){var txt_val=$("#"+messageId).val();
var chk_val=$("#"+checkId).attr("checked");
var sgid_val=$("#"+sgid).val();
if(typeof closeModal!="undefined"&&closeModal){$.modal.close();
}$("#modalWindow").load("/checkout/modals/modal-viewgiftwarp.jsp",{txt:txt_val,chk:chk_val,shippingGroupId:sgid_val});
$("#modalWindow").modal({minWidth:350,minHeight:380});
$("#simplemodal-overlay").css("cursor","default");
}function showGiftOptions(messageId,checkId,sgid,closeModal){var txt_val=$("#"+messageId).val();
var chk_val=$("#"+checkId).val();
var sgid_val=$("#"+sgid).val();
if(typeof closeModal!="undefined"&&closeModal){$.modal.close();
}$("#modalWindow").load("/checkout/modals/modal-giftwrap.jsp",{txt:txt_val,chk:chk_val,shippingGroupId:sgid_val});
$("#modalWindow").modal({minWidth:390,minHeight:180});
$("#simplemodal-overlay").css("cursor","default");
}function facetAttrSelection(categoryId,refinId,facetId,sourceCategoryId,facetTrail,type,showPrd,hideCatFacets){if(null==type||""==type){$.ajax({type:"GET",url:"/pdp/gadgets/productNavAttr.jsp",data:{categoryId:categoryId,hiddenfacetId:facetId,refElemRepId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail},success:function(data){$("div#searchNav").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategoryAttrItemBody.jsp",data:{scatId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail},success:function(data){$("div#ajaxCategoryDisplay").html(data);
$("ul.cat-list li:nth-child(4n)").addClass("fourth");
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchPaginationAttr.jsp",data:{categoryId:categoryId,hiddenfacetId:facetId,refElemRepId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
}else{$.ajax({type:"GET",url:"/catalog/gadgets/ajaxBrandItemsBody.jsp",data:{scatId:sourceCategoryId,categoryId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchPaginationAttr.jsp",data:{categoryId:categoryId,scatId:sourceCategoryId,hiddenfacetId:facetId,refElemRepId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchNav.jsp",data:{categoryId:categoryId,scatId:sourceCategoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type,showProductNavigation:"true",hideCategoryFacets:hideCatFacets},success:function(data){$("div#searchNav").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/sortByAttr.jsp",data:{categoryId:categoryId,catId:sourceCategoryId,facetId:facetId,refinId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:type,showProductNavigation:"true",hideCategoryFacets:hideCatFacets},success:function(data){$("dl#sortingHeader").html(data);
},async:false,dataType:"html"});
}return false;
}function facetTopLooksSelection(categoryId,refinId,facetId,sourceCategoryId,facetTrail){$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategoryTopLooksBody.jsp",data:{scatId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
$.ajax({type:"GET",url:"/search/gadgets/searchPaginationAttr.jsp",data:{categoryId:categoryId,hiddenfacetId:facetId,refElemRepId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,type:"topLooks"},success:function(data){$("div#searchPagination").html(data);
},async:false,dataType:"html"});
}function sortResultAttr(categoryId,facetTrail,sortOrder,facetId,refinId,sourceCategoryId){$.ajax({type:"GET",url:"/catalog/gadgets/ajaxCategoryAttrItemBody.jsp",data:{scatId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,sortOrder:sortOrder},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
}function sortResultBrands(categoryId,facetTrail,sortOrder,facetId,refinId,sourceCategoryId,type){$.ajax({type:"GET",url:"/catalog/gadgets/ajaxBrandItemsBody.jsp",data:{scatId:categoryId,facetId:facetId,refinementId:refinId,sourceCategoryId:sourceCategoryId,q_facetTrail:facetTrail,sortOrder:sortOrder,type:type},success:function(data){$("div#ajaxCategoryDisplay").html(data);
},async:false,dataType:"html"});
}function removePromotionCoupon(couponCode){$("#removeCouponCode").val(couponCode);
$("#removePromotion").submit();
}function checkSelection(){if($("#bill_shipforbill").attr("checked")){$("#bill_address").hide();
if($("#bill_shipforbill")[0]){$("#bill_shipforbill")[0].value="true";
}}else{displayBillingAddress($("#addressId").val());
$("#bill_address").show();
if($("#bill_shipforbill")[0]){$("#bill_shipforbill")[0].value="false";
}}}function optionSelection(r){if($("#savedCC").attr("checked")){$("#ccForm_savedCC").show();
$("#ccForm_newCC").hide();
}else{$("#ccForm_savedCC").hide();
$("#ccForm_newCC").show();
}}function addSelectionAndStartCheckout(productId,modal){$("#addItemAndExpressCheckout").val("false");
var validateSelection=validateProductSelection(productId);
if(!validateSelection){setError("Selection Required",false,productId);
}else{dataString=$("#addToCartOptions"+productId+"").serialize();
$.ajax({type:"GET",url:"/checkout/gadgets/validateAddToCart.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){message=obj.message||"Unable to add item to bag";
setError(message,false,productId,clook);
}else{if(obj.error=="false"||obj.error=="gcard"){var callBack=function(){window.location.href="/cart";
};
if(obj.error=="gcard"){giftCardExpireOverlay(callBack);
}else{callBack();
}}}}});
}}function shippingAddressEdit(nickname,action,ciId){commerceItemId=ciId;
$("#addressEditNickname").val(nickname);
$("#actionEdit").val(action);
dataString=$("#setdefaultEditShipping").serialize();
$.ajax({type:"POST",url:"/account/modals/modal-edit-address.jsp",data:dataString,dataType:"html",success:function(data){$("#modalWindow").html(data);
$("#modalWindow").modal({minWidth:460,minHeight:524,fixed:false});
$("#simplemodal-container").css("width","460");
$("#simplemodal-container").css("height","524");
$("#simplemodal-overlay").css("cursor","default");
},async:false,dataType:"html"});
$("#newAddressForm").hide();
}function saveShippingAddressEdit(nickname,action,ciId){var newNick=$("#addr-nickname").val();
dataString=$("#atg_store_editAddress").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingEditAddress.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){$("#errorMessage").load("/checkout/gadgets/profileErrorMessage.jsp");
}else{if(obj.error=="false"){updateShippingForm(nickname,newNick);
}}}});
}function updateEditedAddress(addressName,newNick){if(newNick!=null&&newNick!=""){$("#addressRefreshNickname").val(newNick);
$("#oldAddressName").val(addressName);
dataString=$("#refreshAddressForm").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){}else{if(obj.error=="false"){$.ajax({type:"POST",url:"/checkout/gadgets/displayRefreshedAddress.jsp",data:{refreshAddressName:newNick},dataType:"html",success:function(data){var idDisplay="#address-section";
var element=$(idDisplay);
$(element).html(data);
changeSelectName($("select").get(),newNick,addressName);
loadShippingInfo();
}});
}}}});
}else{$("#addressRefreshNickname").val(addressName);
dataString=$("#refreshAddressForm").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateShippingAddress.jsp",data:dataString,dataType:"json",success:function(obj){if(obj.error=="true"){}else{if(obj.error=="false"){$.ajax({type:"POST",url:"/checkout/gadgets/displayRefreshedAddress.jsp",data:{refreshAddressName:addressName},dataType:"html",success:function(data){$("#address-section").html(data);
loadShippingInfo();
}});
}}}});
}}function updateShippingForm(nickname,newNick){if(newNick!=nickname){updateEditedAddress(nickname,newNick);
}else{updateEditedAddress(nickname,null);
}}function loadShippingInfo(){$.ajax({type:"POST",url:"/checkout/gadgets/selectedShippingInfo.jsp",data:null,dataType:"html",success:function(data){$("#shippingInfo").html(data);
$.modal.close();
$("#modalWindow").empty();
}});
}function getModalSearchForm(){$("#modalWindow").load("/search/modals/modal-searchFormMessage.jsp");
$("#modalWindow").modal({minWidth:320,minHeight:70});
}function changeSelectName(selects,newName,oldName){for(var i=0;
i<selects.length;
i++){var selectValue=selects[i];
if($(selectValue).val()==oldName){var select="#"+$(selects[i]).attr("id")+" option:selected";
$(select).val(newName);
$(select).html(newName);
}}}function sendFormOnPage(formId,page){var dataString=$("#"+formId).serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validate.jsp",data:dataString,dataType:"jason",async:false});
window.location.href=page;
}function estimateCartShipping(formId){sendFormOnPage(formId,"/cart");
}function closeModal(){$.modal.close();
$("#modalWindow").empty();
}function f_scrollTop(){return f_filterResults(window.pageYOffset?window.pageYOffset:0,document.documentElement?document.documentElement.scrollTop:0,document.body?document.body.scrollTop:0);
}function f_filterResults(n_win,n_docel,n_body){var n_result=n_win?n_win:0;
if(n_docel&&(!n_result||(n_result>n_docel))){n_result=n_docel;
}return n_body&&(!n_result||(n_result>n_body))?n_body:n_result;
}function checkShippingAddresses(){var selects=document.getElementsByName("selectTheShippingAddress");
var result=true;
for(var i=0;
i<selects.length;
i++){if(0==selects[i].selectedIndex){result=false;
break;
}}if(!result){$("#shippingErrors").html("Please enter shipping address information for items in my bag.");
}return result;
}function imposeMaxLength(txt,MaxLen){if(txt.value.length>MaxLen){txt.value=txt.value.substring(0,MaxLen);
}}function changeShippingMethod(el,sgName,ci){$.blockUI({message:null,overlayCSS:{opacity:0}});
$("#checkout-newShippingMethod").val($(el).val());
$("#checkout-newShippingMethodItem").val(ci);
$("#checkout-newShippingMethodGroup").val(sgName);
var dataString=$("#checkout-setShippingAddress").serialize();
$.ajaxSettings.cache=false;
$.ajax({type:"POST",url:"/checkout/gadgets/validate.jsp",data:dataString,dataType:"text",success:function(data){$("#fullCart").load("/checkout/gadgets/cartItemsBody.jsp").error(function(){$.unblockUI();
});
$.unblockUI();
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}function checkPOBoxAddressCountry(){$.blockUI({message:null,overlayCSS:{opacity:0}});
$("#checkout-poBoxAddress").val($("#poBox").is(":checked"));
$("#checkout-country").val($("#country").val());
var dataString=$("#checkout-setPOBoxAddress").serialize();
$.ajaxSettings.cache=false;
$.ajax({type:"POST",url:"/checkout/gadgets/validate.jsp",data:dataString,dataType:"text",success:function(data){$("#availableShippingMethods").load("/checkout/gadgets/selectedShippingInfo.jsp #availableShippingMethods").error(function(){$.unblockUI();
});
$.unblockUI();
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}function setCountry(){if($("#country").val()!=""){$.blockUI({message:null,overlayCSS:{opacity:0}});
$("#checkout-setcountry").val($("#country").val());
$("#checkout-setstate").val($("#state").val());
var dataString=$("#checkout-setCountry").serialize();
$.ajaxSettings.cache=false;
$.ajax({type:"POST",url:"/checkout/gadgets/validate.jsp",data:dataString,dataType:"text",success:function(data){$("#availableShippingMethods").load("/checkout/gadgets/selectedShippingInfo.jsp #availableShippingMethods").error(function(){$.unblockUI();
});
$.unblockUI();
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}}function setupGiftCertificatePaymentGroupsForOrder(){var giftCardNumbers=$("#htmlGiftCertificateNumbers").val();
$("#giftCertificateNumbers").val(giftCardNumbers);
var giftCardPins=$("#htmlGiftCertificatePins").val();
$("#giftCertificatePins").val(giftCardPins);
var dataString=$("#giftCertificatePayment").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validate.jsp",data:dataString,dataType:"text",async:false,success:function(data){$("#checkout").load("/checkout/gadgets/stepThree.jsp");
}});
}function submitGiftCardForm(){if($("#giftCertificateNumber").val()==""||$("#giftCertificateVerificationNumber").val()==""){if($("#giftCertificateNumber").val()==""){$.ajax({type:"POST",url:"/tools/getMessageFromRepository.jsp?messageId=emptyGiftCardNumber",dataType:"json",success:function(obj){if(obj.message){setErrorGiftCard(obj.message);
addInputError("#giftCertificateNumber");
}}});
}if($("#giftCertificateVerificationNumber").val()==""){$.ajax({type:"POST",url:"/tools/getMessageFromRepository.jsp?messageId=emptyGiftCardPin",dataType:"json",success:function(obj){if(obj.message){setErrorGiftCard(obj.message);
addInputError("#giftCertificateVerificationNumber");
}}});
}return;
}$.blockUI({message:null,overlayCSS:{opacity:0}});
var giftCardNumber=$("#giftCertificateNumber").val();
var pinNumber=$("#giftCertificateVerificationNumber").val();
$("#giftCertificateNumberAjax").val(giftCardNumber);
$("#giftCertificateVerificationNumberAjax").val(pinNumber);
$.ajaxSettings.cache=false;
dataString=$("#giftCertificatePaymentAjax").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateGiftCard.jsp",data:dataString,dataType:"json",success:function(obj){$.get("/checkout/gadgets/stepThree.jsp",function(data){var paymentSection=$(data).find("#checkout-steps");
$("#checkout-steps").html(paymentSection.html());
if(obj.error=="true"){$("#giftCertificateNumber").val(giftCardNumber);
$("#giftCertificateVerificationNumber").val(pinNumber);
}$("#fullCart").load("/checkout/gadgets/cartItemsBody.jsp?page=checkout");
if($(data).find("#checkout-section-line").children().size()==0){$("#checkout-section-line").html($(data).find("#checkout-section-line").html());
}retrictGiftCardInputs();
if($("#giftCertificateVerificationNumberError").val()=="true"){$("#giftCertificateVerificationNumber").addClass("error");
}if($("#giftCertificateNumberError").val()=="true"){$("#giftCertificateNumber").addClass("error");
}$.unblockUI();
}).error(function(){$.unblockUI();
});
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}function setErrorGiftCard(msg){if($("#paymentErrorMessages").html().trim()==""){$("#paymentErrorMessages").append("<div id='error-payment'><div id='error-payment-message' class='error-message error-payment'></div></div>");
}var errors=$("#error-payment-message").html().trim();
if(errors.indexOf(msg)==-1){$("#error-payment-message").append(msg+"<br>");
}}function retrictGiftCardInputs(){$("#giftCertificateNumber").keypress(function(e){if(e.which!=8&&e.which!=0&&(e.which<48||e.which>57)){e.preventDefault();
}});
$("#giftCertificateVerificationNumber").keypress(function(e){if(e.which!=8&&e.which!=0&&(e.which<48||e.which>57)){e.preventDefault();
}});
}function removeGC(gcId){$.blockUI({message:null,overlayCSS:{opacity:0}});
$("#giftCertificateToRemove").val(gcId);
$.ajaxSettings.cache=false;
dataString=$("#giftCertificatePaymentRemoveAjax").serialize();
$.ajax({type:"POST",url:"/checkout/gadgets/validateGiftCard.jsp",data:dataString,dataType:"json",success:function(obj){$.get("/checkout/gadgets/stepThree.jsp",function(data){var paymentSection=$(data).find("#checkout-steps");
$("#checkout-steps").html(paymentSection.html());
$("#fullCart").load("/checkout/gadgets/cartItemsBody.jsp");
if($(data).find("#checkout-section-line").children().size()!=$("#checkout-section-line").children().size()){$("#checkout-section-line").html($(data).find("#checkout-section-line").html());
if($("#sfc_creditCardOption").val()!=""){displayCreditCardAddress($("#sfc_creditCardOption").val());
}toggleNewCreditCard();
}retrictGiftCardInputs();
$.unblockUI();
}).error(function(){$.unblockUI();
});
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}function checkSKUQuality(productId){var result="";
var skuId=$("#catalogRefIds"+productId).val();
var quantity=parseInt($("#prodQtySelection").val());
if(isNaN(quantity)||1>quantity){result="Quantity you've selected is incorrect.";
}else{$.ajax({url:"/search/gadgets/skuCheckQuantity.jsp?skuId="+skuId,dataType:"json",async:false,success:function(json){var qty=parseInt(json.qty);
if(qty<quantity){result="The quantity you've selected exceeds the available inventory of "+qty+".";
}}});
}return result;
}function allNewArrivals(formId){$("#"+formId).submit();
}function submitFormById(formId){$("#"+formId).submit();
}function nothanks(){$.modal.close();
$("#modalWindow").empty();
}function openDelayedDialog(div_id){setTimeout(function(){$("#"+div_id).dialog("open");
},1000);
}function getContactPhone(){$("body").append('<div id="modalWindow_Phone"></div>');
$("#modalWindow_Phone").load("/metro/myaccount/includes/modal_phone.jsp").dialog({height:"auto",minWidth:340,minHeight:90,resizable:false,autoOpen:true,modal:true});
openDelayedDialog("modalWindow_PhoneEmail");
$(".ui-widget-overlay").click(function(){closeModalGeneric("modalWindow_Phone",false);
});
}function getContactEmail(){$("body").append('<div id="modalWindow_Email"></div>');
$("#modalWindow_Email").load("/metro/myaccount/includes/modal_email.jsp").dialog({height:"auto",minWidth:340,minHeight:90,resizable:false,autoOpen:true,modal:true});
openDelayedDialog("modalWindow_PhoneEmail");
$(".ui-widget-overlay").click(function(){closeModalGeneric("modalWindow_Email",false);
});
}function getMetroConnect(){$("body").append('<div id="metroConnectWindow"></div>');
$("#metroConnectWindow").load("/metro/includes/modal_metro-connect.jsp").dialog({height:"auto",minWidth:365,minHeight:355,resizable:false,autoOpen:false,modal:true});
openDelayedDialog("metroConnectWindow");
}function getMyMetro(){$("body").append('<div id="myMetroWindow"></div>');
$("#myMetroWindow").load("/metro/includes/modal_mymetro.jsp").dialog({height:"auto",minWidth:310,minHeight:307,resizable:false,autoOpen:false,modal:true});
openDelayedDialog("myMetroWindow");
}function getEWallet(){$("body").append('<div id="ewalletWindow"></div>');
$("#ewalletWindow").load("/metro/includes/modal_ewallet_benefits.jsp").dialog({height:"auto",minWidth:350,minHeight:485,resizable:false,autoOpen:false,modal:true});
openDelayedDialog("ewalletWindow");
}function getOtherPaymentMethods(){$("body").append('<div id="otherPaymentsWindow"></div>');
$("#otherPaymentsWindow").load("/metro/includes/modal_other_payments.jsp").dialog({height:"auto",minWidth:660,minHeight:307,resizable:false,autoOpen:false,modal:true});
openDelayedDialog("otherPaymentsWindow");
}function signupEmailOverlay(referer){var email=$("#guest-email").val();
$("#modalWindow").load("/global/modals/modal-emailSignUp.jsp?isModal=true&email="+email);
$("#modalWindow").modal({minWidth:381,onShow:function(dialog){dialog.container.css({"height":"auto"});
}});
$("#simplemodal-overlay").css("cursor","default");
}function submitEmailSignup(){var isModal=$("#signUpIsModal").val();
var age=$("#regAgeVerified").attr("checked");
var email=$("#regEmail").val();
var confEmail=$("#regConfirmEmail").val();
var errorObj={error:"false",invalidEmail:null,invalidConfirmEmail:null,duplicatedEmailSub:null,verifyAge:null};
if(!age){errorObj.error=true;
errorObj.invalidEmail="Please verify you are over 13";
}if(email==""||email==undefined){errorObj.error=true;
errorObj.invalidConfirmEmail="Please enter a valid email address";
}if(confEmail==""||confEmail==undefined){errorObj.error=true;
errorObj.verifyAge="Please enter a valid confirmation email address";
}if(errorObj.error=="false"){if(!isModal){$("#emailSignUp").submit();
}else{dataString=$("#emailSignUp").serialize();
$.ajax({type:"POST",url:"/staticpages/gadgets/validateEmailSignup.jsp",data:dataString,dataType:"json",success:function(data){if(data.error=="true"){displayEmailSignupErrors(data);
}else{if(data.error=="false"){$.modal.close();
$("#modalWindow").load("/global/modals/modal-emailSignUp.jsp?success=true&isModal=true");
$("#modalWindow").modal({minWidth:381,minHeight:181});
}}},error:function(jqXHR,textStatus,error){}});
}}else{displayEmailSignupErrors(errorObj);
}}function displayEmailSignupErrors(data){var errMsg="<div class='error-message' id='error-message'>";
if(data.invalidEmail!=null){errMsg+=data.invalidEmail+"<br/>";
}if(data.invalidConfirmEmail!=null){errMsg+=data.invalidConfirmEmail+"<br/>";
}if(data.duplicatedEmailSub!=null){errMsg+=data.duplicatedEmailSub+"<br/>";
}if(data.verifyAge!=null){errMsg+=data.verifyAge+"<br/>";
}errMsg+="</div>";
$("#errorMessages").html(errMsg);
}function closeOrderStatusModal(){$("#modalWindow").empty();
$.modal.close();
}function orderTrack(formId){var submit=false;
if(formId!="orderStatusModal"){$("#"+formId).submit();
return false;
}else{if($("#emailAddressModal").val()==""){$("#emailAddressModal").attr("class","error");
$("#emptyOrderEmailDivModal").show();
submit=true;
}if($("#orderIdModal").val()==""){$("#orderIdModal").attr("class","error");
$("#emptyOrderIdDivModal").show();
submit=true;
}if(!submit){$("#"+formId).submit();
return false;
}else{$("#error-messageModal").show();
}}}function checkCardType(){if($("#ccType").val()=="AmericanExpress"){$("#verificationNewNumberInput").attr({maxLength:4});
$("#verificationNewNumberInput").val("");
}else{$("#verificationNewNumberInput").attr({maxLength:3});
$("#verificationNewNumberInput").val("");
}}function checkCardType(value){if(value=="AmericanExpress"){$("#verificationNumberInput").attr({maxLength:4});
$("#verificationNumberInput").val("");
}else{$("#verificationNumberInput").attr({maxLength:3});
$("#verificationNumberInput").val("");
}}function changeUcOrderId(){$("#orderId").bind("keyup",function(){$("#orderId").val(($("#orderId").val()).toUpperCase());
});
$("#orderId").bind("change",function(){$("#orderId").val(($("#orderId").val()).toUpperCase());
});
}function submitPasswordForgot(){dataString=$("#passwordForgot").serialize();
$.ajax({type:"POST",url:"/account/gadgets/validatePasswordForgot.jsp",data:dataString,dataType:"json",success:function(data){if(data.error=="false"){$.modal.close();
$("#modalWindow").empty();
$("#modalWindow").load("/account/modals/modal-passwordforgotsuccess.jsp");
$("#modalWindow").modal({minWidth:420,minHeight:170});
}else{if(data.error=="true"){document.getElementById("simplemodal-container").style.height="272px";
$("#forgotPwdErrors").html(data.messages);
$("#forgotPwdErrors").show();
}}}});
}function getMessageFromRepository(messageCode){var message="";
$.ajax({type:"POST",url:"/tools/getMessageFromRepository.jsp?messageId="+messageCode,dataType:"json",success:function(obj){if(obj.message){message=obj.message;
}}});
return message;
}function ImgLoad(myobj,oriSrc,naSrc){var oImg=new Image;
$(oImg).bind("load",function(){$(myobj).attr("width","180");
$(myobj).src=oImg.src;
});
$(oImg).error(function(){$(myobj).attr("width","180");
$(myobj).attr("src",naSrc);
});
oImg.src=oriSrc;
}function ImgLoadWidth(myobj,oriSrc,naSrc,width,clook,productId){var selectedColorCode="selectedColorCode";
clook=clook||"false";
if(clook=="true"){selectedColorCode="clookSelectedColorCode";
}var oImg=new Image;
$(oImg).bind("load",function(){$(myobj).attr("width",width);
$(myobj).src=oImg.src;
});
$(oImg).error(function(){color=$("#"+selectedColorCode+productId).val();
if(color!="false"&&color!=undefined){$(myobj).attr("width",width);
$(myobj).attr("src",naSrc);
}else{$(myobj).attr("src","");
}});
oImg.src=oriSrc;
}function imgError(image,src){image.src=src;
return true;
}function removeSleeve(commerceItemId,sleeveQuantity,holderProductId){var commerceItemQuantity=parseInt($("#updateGiftCardQuantity input[name="+commerceItemId+"]").val());
var updatedCommerceItemQuantity=commerceItemQuantity-sleeveQuantity;
$("#updateGiftCardQuantity input[name="+commerceItemId+"]").val(updatedCommerceItemQuantity);
$("#updateGiftCardQuantity input[name=holderProductId]").val(holderProductId);
$("#updateGiftCardQuantity input[name=giftCardCommerceItemId]").val(commerceItemId);
$("#updateGiftCardQuantity").submit();
}function submitAddLoyaltyCard(controlIndex){$("#loyaltyCardNumber").val($("#loyaltyCardNumber_"+controlIndex).val());
$("#addLoyaltyCardForm").submit();
}function submitRemoveLoyaltyCard(cardNumber){$("#removeloyaltyCardNumber").val(cardNumber);
$("#removeLoyaltyCard").submit();
}function submitCurrentRedemptionType(redemptionType){$("#newRedemptionType").val(redemptionType);
$("#updateCurrentRedemptionType").submit();
}function showCouponCodeOverlay(){$("#modalWindow").load("/cart/modals/couponCodeOverlay.jsp");
$("#modalWindow").modal({minWidth:700,minHeight:550});
$("#simplemodal-overlay").css("cursor","default");
}function showGiftWrapOverlay(){$("#modalWindow").load("/cart/modals/giftWrapOverlay.jsp");
$("#modalWindow").modal({minWidth:550,minHeight:425});
$("#simplemodal-overlay").css("cursor","default");
}function showJBucksFunCardsOverlay(){$("#modalWindow").load("/cart/modals/jBucksFunCardsOvelay.jsp");
$("#modalWindow").modal({minWidth:700,minHeight:425});
$("#simplemodal-overlay").css("cursor","default");
}function showFreeReturnsOverlay(){$("#modalWindow").load("/global/modals/modal-freeReturns.jsp");
$("#modalWindow").modal({minWidth:450,minHeight:565});
$("#simplemodal-overlay").css("cursor","default");
}function beginCheckout(){var addGiftWrap=$("#addGiftWrapCheckBox").attr("checked");
if(addGiftWrap=="checked"){$.blockUI({message:null,overlayCSS:{opacity:0}});
dataString=$("#giftWrapMsg").serialize();
$.ajax({type:"POST",async:false,url:$("#giftWrapMsg").attr("action"),data:dataString,dataType:"text",success:function(data){$("#checkoutForm").submit();
$.unblockUI();
},error:function(xhr,ajaxOptions,thrownError){$.unblockUI();
}});
}else{$("#checkoutForm").submit();
}}function submitShippingForm(){if($("#checkoutSavedAddress").attr("checked")=="checked"||$("#checkoutSavedAddress").attr("checked")==true){var addressNickname=document.getElementById("addressSelected");
if(addressNickname.value==null||addressNickname.value==""){$.ajax({type:"POST",url:"/tools/getMessageFromRepository.jsp?messageId=invalidShippingAddress",dataType:"json",success:function(obj){if(obj.message){addErrorMessage(obj.message);
$("#addressSelected").addClass("error");
return;
}}});
}else{var checkoutMultiShippingAddress=document.getElementById("checkoutMultiShippingAddress");
checkoutMultiShippingAddress.action=checkoutMultiShippingAddress.action+"&addressNickname="+addressNickname.value;
$("#continueButton").click();
}}else{if($("#checkoutNewAddress").attr("checked")=="checked"||$("#checkoutNewAddress").attr("checked")==true){var checkoutMultiShippingAddress=document.getElementById("checkoutMultiShippingAddress");
checkoutMultiShippingAddress.action=checkoutMultiShippingAddress.action+"&name="+$("#nickName").val();
$("#continueButton").click();
}else{$("#continueButton").click();
}}}function addErrorMessage(msg){if($("#shippingErrors").html().trim()==""){$("#shippingErrors").append("<div id='error-message' class='error-message'></div>");
}var errors=$("#error-message").html().trim();
if(errors.indexOf(msg)==-1){$("#error-message").append(msg+"<br>");
}}function isVisible(){setCountry();
}$("#newAddressForm").bind("isVisible",isVisible);
$("#newAddressForm").show("slow",function(){$(this).trigger("isVisible");
});
function showAddressForm(){$("#newAddressForm").show();
$("#newAddressSubtitle").attr("class","checkout-margin-top-fifteen");
$("#useAsBilling").attr("checked",true);
$("#shippingAddressInfo").hide();
$("#shippingAddressDrop").hide();
}function hideAddressForm(){$("#newAddressForm").hide();
$("#useAsBilling").attr("checked",false);
$("#shippingAddressInfo").show();
$("#shippingAddressDrop").show();
changeShippingAddress($("#addressSelected").val());
}function showCarousel(categoryId){closeModal();
$("#modalWindow").load("/catalog/modals/modal-carousel.jsp?categoryId="+categoryId);
$("#modalWindow").modal({minWidth:675,minHeight:400});
$("#simplemodal-overlay").css("cursor","default");
}function addOmnitureElem(qty,price){sjData.products[0].quantity=qty;
sjData.products[0].price=price;
}function BVcheckLoadState(bv_url){if(!BVisLoaded){var page=document.getElementById("BVFrame").src;
document.getElementById("BVFrame").src=bv_url+"logging?page="+escape(page);
document.getElementById("BVReviewsContainer").innerHTML="<!-- Review retrieval timed out -->";
}}function bvLoadRR(bv_url,bv_site_code,productId){var bvPage=bv_url+bv_site_code+productId+"/reviews.htm?format=embedded";
var bvReviewIDName="featurereview";
var bvReviewIDRegex=new RegExp("[?&]"+bvReviewIDName+"=([^&#]+)");
var bvReviewIDMatch=bvReviewIDRegex.exec(window.location.search);
var bvReviewID=bvReviewIDMatch?decodeURIComponent(bvReviewIDMatch[1]):null;
document.getElementById("BVFrame").src=/^[0-9]+$/.test(bvReviewID)?bvPage+"&reviewid="+bvReviewID:bvPage;
setTimeout("BVcheckLoadState('"+bv_url+"')",15000);
}function updateCertonaTags(item_id,color_id,event){if(typeof(event)=="undefined"){event="product";
}if(typeof(resx)!="undefined"&&resx!=null){resx.event=event;
resx.itemid=item_id+"_"+color_id;
if(event!="shopping+bag"){resx.rrqs="ColorCode="+color_id;
}certonaResx.run();
}}function addOmnitureElem(qty,price){sjData.products[0].quantity=qty;
sjData.products[0].price=price;
}function callCustomEvent(eventName,data1,data2,data3){if(eventName=="emailFriend"){sj.customEvent(eventName);
}else{sj.customEvent(eventName,data1,data2,data3);
}}function closeGeneralModal(){$("#modalWindow").empty();
$.modal.close();
}