var isUnLoad="no";
var isMobile={Android:function(){return navigator.userAgent.match(/Android/i);
},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i);
},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i);
},Opera:function(){return navigator.userAgent.match(/Opera Mini/i);
},Windows:function(){return navigator.userAgent.match(/IEMobile/i);
},any:function(){return(isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows());
}};
jQuery(document).ready(function(){if(isMobile.any()){jQuery.ajax({url:contextRoot+"/includes/mobileinterstitial.jsp",type:"GET",global:false,dataType:"xml",success:function(data){$xml=$(data);
if($xml.find("openpopup").text()){var success=$xml.find("openpopup").text();
if(success=="true"){$("#splash-bg").addClass("splashoverlay");
$("#splash-bg").load(contextRoot+"/includes/mobileinterstitialcontent.jsp");
$("#splash-bg").modal({minWidth:100,minHeight:100});
}else{}}}});
}jQuery(window).load(function(){substituteHyphen();
departmentDotAutoWidth();
shopDepartmentAutoHeight();
categoryGridLiAutoHeight();
recipeBoxAutoHeight();
storeLocatorLiAutoHeight();
itemCompareAutoHeight();
couponCarouseleAutoHeight();
departmentCarouselAutoHeight();
pdpCarouselAutoHeight();
articleCarouselAutoHeight();
NormalizeSubmenu();
});
subTitleDotAutoWidth();
scrollToTop();
checkedGeneralInput();
checkedInput();
displayVideoShopping();
removeVideoShopping();
displayRecieptAdd();
removeClickEvent();
setBtnOnMyList();
toggleBlackBox();
setUnloadValueForEvents();
var pageType=$("input#shopListPageType").val();
$(window).on("beforeunload",function(e){checkForShoppingListItems();
if(isUnLoad=="yes"&&pageType!="printPage"){var displayMsg="Want to save your list?\n\nPlease log in or create an H-E-B account to save your list.\n";
return displayMsg;
}});
jQuery(window).on("beforeunload",function(){jQuery(window).scrollTop(0);
});
jQuery(".valign").each(function(){jQuery(this).position({my:"center",at:"center",of:jQuery(this).parent()});
});
jQuery(document).ready(function(){jQuery(".va").each(function(){var margin_top=(jQuery(this).parent().height()-jQuery(this).height())/2;
jQuery(this).css({"margin-top":margin_top+"px"});
});
});
jQuery(".circular-carousel").jcarousel({wrap:null});
jQuery(".simple-circular-carousel").jcarousel({wrap:null,scroll:1});
$(".dept-hero .simple-circular-carousel").each(function(index){countLi=jQuery(this).find("li").length;
if(countLi==1){jQuery(this).css("position","static");
jQuery(".dept-hero .simple-circular-carousel").find(".jcarousel-prev").hide();
jQuery(".dept-hero .simple-circular-carousel").find(".jcarousel-next").hide();
}});
jQuery("#thecarousel.simple-circular-carousel").jcarousel({wrap:"",scroll:1});
jQuery(".four-circular-carousel").jcarousel({wrap:null,scroll:4});
var items=$("#mycarousel li").length;
var CP1=4;
var extra;
var CP2;
var CP3;
var count;
if(items<CP1){CP2=0;
CP3=0;
}else{extra=(items-CP1)%2;
CP2=((items-CP1-extra)/2);
CP3=((items)-(CP1+CP2));
count=CP1;
}if(items<=4){jQuery("#p1").parent().addClass("hidden");
jQuery("#thecarousel.simple-circular-carousel .jcarousel-prev").addClass("hidden");
jQuery("#thecarousel.simple-circular-carousel .jcarousel-next").addClass("hidden");
}else{if(CP2==0){CP2=CP3;
CP3=0;
jQuery("#p3").addClass("hidden");
}if(CP2==0&&CP3==0){jQuery("#p2").addClass("hidden");
jQuery("#p3").addClass("hidden");
}}$("#thecarousel .jcarousel-prev-horizontal").on("click",function(){if(count>CP1){count=count-1;
}if((count>=CP1)&&(count<(CP1+CP2))){jQuery("#p1").addClass("active");
jQuery("#p2").removeClass("active");
jQuery("#p3").removeClass("active");
}else{if((count>=((CP1+CP2)))&&(count<=(CP1+CP2))){jQuery("#p1").removeClass("active");
jQuery("#p2").addClass("active");
jQuery("#p3").removeClass("active");
}else{if(count>(CP1+CP2)&&(count<=items)){jQuery("#p1").removeClass("active");
jQuery("#p2").removeClass("active");
jQuery("#p3").addClass("active");
}}}});
$("#thecarousel .jcarousel-next-horizontal").on("click",function(){if(count<items){count=count+1;
}if((count>=CP1)&&(count<(CP1+CP2))){jQuery("#p1").addClass("active");
jQuery("#p2").removeClass("active");
jQuery("#p3").removeClass("active");
}else{if((count>=((CP1+CP2)))&&(count<=(CP1+CP2))){jQuery("#p1").removeClass("active");
jQuery("#p2").addClass("active");
jQuery("#p3").removeClass("active");
}else{if(count>(CP1+CP2)&&(count<=items)){jQuery("#p1").removeClass("active");
jQuery("#p2").removeClass("active");
jQuery("#p3").addClass("active");
}}}});
$("#mini-shopping-list").find(".four-circular-carousel").each(function(index){countLi=jQuery(this).children("li").length;
if(countLi<=4){jQuery(this).css("position","static");
jQuery("#mini-shopping-list").find(".jcarousel-prev").hide();
jQuery("#mini-shopping-list").find(".jcarousel-next").hide();
}});
jQuery(".mini-list-container .title .closeitem a").click(function(){jQuery("#mini-shopping-list,#header div.section-b ul.menu li.header .lists .icon").hide();
jQuery("#header div.section-b ul.menu li.header .lists a").removeClass("expanded");
$.ajax({url:contextRoot+"/mylist/includes/addAttributeToSession.jsp?operation=close",dataType:"html",type:"POST",data:"",success:function(data){}});
});
jQuery("#main-menu-cart").click(function(){if(jQuery("#mini-cart:visible").length){jQuery(".mini-cart-container .closeitem a").click();
}else{jQuery(".mini-list-container .closeitem a").click();
jQuery("#mini-cart,#header div.section-b ul.menu li.header .cart .icon").show();
jQuery("#header div.section-b ul.menu li.header .cart a").addClass("expanded");
}});
jQuery(".mini-cart-container .title .closeitem a").click(function(){jQuery("#mini-cart,#header div.section-b ul.menu li.header .cart .icon").hide();
jQuery("#header div.section-b ul.menu li.header .cart a").removeClass("expanded");
});
jQuery("#header .section-b .collapse-controller").click(function(){jQuery(this).parent().parent().find("li.body").toggle(0,"swing",function(arg){if(jQuery(this).is(":visible")){jQuery.ajax({url:contextRoot+"/includes/addsessionvalue.jsp",type:"POST",global:false,data:({boxaction:"open"}),success:function(data){$("#blackbox").removeClass("collapsed").addClass("expanded");
$("#boxcollapsecontrol").attr("title","close");
}});
}else{jQuery.ajax({url:contextRoot+"/includes/addsessionvalue.jsp",type:"POST",global:false,data:({boxaction:"close"}),success:function(data){$("#blackbox").removeClass("expanded").addClass("collapsed");
$("#boxcollapsecontrol").attr("title","open");
}});
}});
});
jQuery(".main-menu .current").append("<span class='icon' />");
jQuery("#header ul.main-menu li.item a").hover(function(){jQuery("#header ul.main-menu li.item").removeClass("active");
jQuery(this).parent().addClass("active");
jQuery("#megamenu div.megamenu-in").show();
jQuery("#megamenu div.megamenu-in .megamenu-section").hide();
jQuery("#megamenu div.megamenu-in .megamenu-section."+jQuery(this).attr("rel")).show();
jQuery("#megamenu div.megamenu-in .megamenu-section."+jQuery(this).attr("rel")+" .section-d").each(function(){var padding_added=(jQuery(this).outerHeight()-jQuery(this).height());
var padding_bottom=(jQuery(this).parent().height()-jQuery(this).height())-13;
if(padding_added>36){padding_bottom=(jQuery(this).parent().height()-jQuery(this).outerHeight());
}if(padding_bottom>0){jQuery(this).css({"padding-bottom":padding_bottom+"px"});
}});
},function(){});
jQuery("#megamenu div.megamenu-in").hover(function(){},function(){jQuery("#header ul.main-menu li.item").removeClass("active");
jQuery(this).hide();
});
jQuery("#header .section-a-a").hover(function(){jQuery("#header ul.main-menu li.item").removeClass("active");
jQuery("#header ul.main-menu").removeClass("active");
jQuery("#megamenu div.megamenu-in").hide();
},function(){});
jQuery("#scrollbar1").tinyscrollbar();
jQuery("#scrollbar1").tinyscrollbar({sizethumb:55});
jQuery(".password-tooltip-container .pwd-inner-container p").each(function(index,element){var pHeight=jQuery(this).height();
if(pHeight<=32){jQuery(this).css("padding-top",((32-pHeight)/2));
}});
jQuery(".coupons-selected div.clearfix").each(function(index){var firstHeight=jQuery(this).children(".first").height();
var secondHeight=jQuery(this).children(".second").height();
if(index>0&&secondHeight<firstHeight){var paddingSecond=Math.floor((firstHeight-secondHeight)/2);
jQuery(this).children(".second").css({"padding-top":paddingSecond+10,"padding-bottom":paddingSecond});
}});
jQuery(".help-icon").each(function(){var helpClass=jQuery(this).attr("class");
var postionArray=helpClass.split(" ");
var positionQtip=postionArray[1];
if(positionQtip==="qTop"){myPosition="bottom center";
atPosition="top center";
}else{myPosition="center left";
atPosition="center right";
}jQuery(this).qtip({position:{my:myPosition,at:atPosition,target:jQuery(this)},content:{text:jQuery(this).next("div.qtip-content")},style:{classes:"qtip-light qtip-rounded"}});
});
jQuery(".c-head-row").each(function(index){maxHeight=jQuery(this).children().eq(0).height();
jQuery(this).children().each(function(childrenIndex){if(childrenIndex!=0){childrenHeight=jQuery(this).height();
jQuery(this).css("padding-top",Math.floor(maxHeight-childrenHeight));
}});
});
jQuery(".item-description-name").each(function(index){var text=jQuery(this).text();
if(text.length>30){text=text.substr(0,27);
text+="...";
jQuery(this).text(text);
}text="";
});
jQuery(".re-table").each(function(index){jQuery(this).children(".re-row").each(function(rowIndex){var minHeight=96;
jQuery(this).children("div").each(function(rowColumn){var currentHeight=jQuery(this).height();
if(minHeight<currentHeight){minHeight=currentHeight;
}});
if(minHeight>96){for(var indexDiv=0;
indexDiv<5;
indexDiv++){jQuery(this).children("div").eq(indexDiv).css("min-height",minHeight);
}}});
});
jQuery(".cookingrecipewrapper .cookingrecipe .maintxt").each(function(index){var titleText=jQuery(this).text();
truncateSingleWord(jQuery(this),titleText,68);
});
jQuery(".cookingartilceswrapper .articles .maintxt").each(function(index){var titleText=jQuery(this).text();
truncateSingleWord(jQuery(this),titleText,44);
});
jQuery(".simple-circular-carousel .items .details span").each(function(index){var titleText=jQuery(this).text();
truncateWord(jQuery(this),titleText,100);
});
jQuery(".cat-coupon-description .couponDesc").each(function(index){var titleText=jQuery(this).text();
truncateWord(jQuery(this),titleText,100);
});
jQuery(".recipeboxlink .atl-container ul li a").each(function(index){var titleText=jQuery(this).text();
truncateWord(jQuery(this),titleText,13);
});
jQuery(".seasonallink a").each(function(index){if(jQuery(this).attr("class")!="viewallseasonal"){var titleText=jQuery(this).text();
truncateWord(jQuery(this),titleText,22);
}});
jQuery(".cookingartilceswrapper .articles").children("a").children("p.title").each(function(index){var titleText=jQuery(this).text();
truncateWord(jQuery(this),titleText,27);
});
jQuery(".cookingrecipewrapper .cookingrecipe .title").children("a.titleAnchor").each(function(index){var titleText=jQuery(this).text();
truncateWord(jQuery(this),titleText,27);
});
jQuery(".relatedartilceswrapper .relatedarticles").children("a").children("p.title").each(function(index){var titleText=jQuery(this).text();
truncateWord(jQuery(this),titleText,27);
});
jQuery(".relatedartilceswrapper .relatedarticles .maintxt").each(function(index){var titleText=jQuery(this).text();
truncateSingleWord(jQuery(this),titleText,44);
});
$(".staticcontent .clearfix .lowercontainer p strong").each(function(index){lengthContainer=$(".staticcontent .clearfix .lowercontainer p strong").length;
heightContainer=jQuery(this).height();
if(index==0){maxHeight=0;
}if(maxHeight<heightContainer){maxHeight=heightContainer;
}if((index+1)%3==0){for(position=2;
position>=0;
position--){jQuery(".staticcontent .clearfix .lowercontainer p strong").eq(index-position).css("min-height",maxHeight);
}maxHeight=0;
}else{if((lengthContainer-1)==index&&(lengthContainer%3!=0)){for(position=((lengthContainer%3)-1);
position>=0;
position--){jQuery(".staticcontent .clearfix .lowercontainer p strong").eq(index-position).css("min-height",maxHeight);
}maxHeight=0;
}}});
jQuery(".staticcontent .clearfix .lowercontainertwo p strong").each(function(index){lengthContainer=$(".staticcontent .clearfix .lowercontainertwo p strong").length;
heightContainer=jQuery(this).height();
if(index==0){maxHeight=0;
}if(maxHeight<heightContainer){maxHeight=heightContainer;
}if((index+1)%3==0){for(position=2;
position>=0;
position--){jQuery(".staticcontent .clearfix .lowercontainertwo p strong").eq(index-position).css("min-height",maxHeight);
}maxHeight=0;
}else{if((lengthContainer-1)==index&&(lengthContainer%3!=0)){for(position=((lengthContainer%3)-1);
position>=0;
position--){jQuery(".staticcontent .clearfix .lowercontainertwo p strong").eq(index-position).css("min-height",maxHeight);
}maxHeight=0;
}}});
jQuery("#signup-email-address").click(function(e){e.preventDefault();
var sText=$("#signup-email-address").val();
if(sText!=undefined&&sText=="Enter your email address"){$("#signup-email-address").val("");
$("#signup-email-address").removeClass("ghost");
}});
jQuery("#signup-email-address").blur(function(e){e.preventDefault();
var sText=$("#signup-email-address").val();
if(sText!=undefined&&sText==""){$("#signup-email-address").val("Enter your email address");
$("#signup-email-address").addClass("ghost");
}});
$("body").on("click","#updateRecipeAddToList",function(){$("#shopListLimitError").removeClass("show").addClass("dontShow");
var formID=$(this).attr("name");
var shoppingListId="";
if(document.getElementById("selectList")!=null){shoppingListId=document.getElementById("selectList").value;
}if(shoppingListId==null||shoppingListId==undefined||shoppingListId.length==0){shoppingListId=document.getElementById("miniListSelect").value;
}if(shoppingListId==null||shoppingListId==undefined||shoppingListId.length==0){shoppingListId=document.getElementById("selectedShoppingListId").value;
}$.ajax({accept:"application/json",url:$("#"+formID).attr("action"),dataType:"json",type:"POST",data:$("#"+formID).serialize(),success:function(data){if(data.success){showShoppingListInMinilist(shoppingListId);
closeGeneralModal();
$("#uncheckall_1").click();
}else{closeGeneralModal();
$("#shopListLimitError").removeClass("dontShow").addClass("show");
jQuery("html, body").animate({scrollTop:0},600);
}}});
return false;
});
$(".deals-landing-page button.see-coupons").click(loadCouponSel);
jQuery(".couponDesc").each(function(){var currElem=jQuery(this);
var text=jQuery(this).text();
if(!String.prototype.trim){text=text.replace(/^\s+|\s+$/g,"");
}else{text=text.trim();
}if(text.length>100){text=text.substr(0,101);
text+="...";
jQuery(this).text(text);
}text="";
});
jQuery("#wrapper").click(function(e){jQuery(".aheadSearch").hide();
});
$("input.numberOnly").keyup(function(e){if(e.keyCode===39||e.keyCode===37||e.keyCode===38||e.keyCode===40){return;
}$(this).val($(this).val().replace(/[^\d]/ig,""));
});
$("input.decimalOnly").keyup(function(e){if(e.keyCode===39||e.keyCode===37||e.keyCode===38||e.keyCode===40){return;
}$(this).val($(this).val().replace(/[^0-9.]/ig,""));
});
$("#spinner").bind("ajaxError",function(){$(this).hide();
});
jQuery(document).keyup(function(e){if(e.keyCode==27){$("#OverlayDiv").each(function(index){$("#OverlayDiv").empty();
$.modal.close();
});
if($("#pcrRegSubmitBut")!=undefined){jQuery("#pcrRegSubmitBut").attr("class","button ovallon btn-submit");
jQuery("#pcrRegSubmitBut").removeAttr("disabled");
}}});
jQuery("#pricingToolTipClose").click(function(){jQuery(".tab-message-container").empty();
jQuery(".tab-message-container").remove();
$.ajax({url:contextRoot+"/includes/setcookieorprofile.jsp?source=category",dataType:"html",type:"POST",data:"",success:function(data){}});
});
});
function heightAlignmentTab(){jQuery(".view-tabs-container").each(function(){var generalHeight=jQuery(this).height();
jQuery(this).children().each(function(){if(jQuery(this).hasClass("view-tab-highlight")){jQuery(this).css("height",(generalHeight-2)+"px");
}else{jQuery(this).css("height",generalHeight+"px");
}jQuery(this).children(".vat").filter(function(){var margin_top=Math.floor((jQuery(this).parent().height()-jQuery(this).height())/2);
jQuery(this).css({"margin-top":margin_top+"px"});
});
});
});
}function truncateWord(id,term,termLong){var termLength=term.length;
var titleText="";
if(termLength>termLong){titleText=term.substr(0,termLong);
titleText+="...";
id.text(titleText);
}}function truncateSingleWord(id,term,termLong){var termLength=term.length;
var titleText="";
if(termLength>termLong){var termArray=term.split(" ");
var currenTermLength=0;
for(var position=0;
position<termArray.length;
position++){currenTermLength+=termArray[position].length;
currenTermLength+=1;
if((currenTermLength-1)>termLong){currenTermLength-=termArray[position].length;
currenTermLength-=1;
position=termArray.length;
}}titleText=term.substr(0,currenTermLength-1);
titleText+="...";
id.text(titleText);
}}function shopDepartmentAutoHeight(){jQuery(".shop-content ul.cat-list").each(function(index){var count=1;
var maxHeight=0;
var lengthLiProd=jQuery(this).children("li").length;
jQuery(this).find("li > div.shop-list-deparment").each(function(indexDepart){var departmentHeight=jQuery(this).find("a").height();
if(maxHeight<departmentHeight){maxHeight=departmentHeight;
}if(count%4==0&&indexDepart!=0){for(var x=3;
x>=0;
x--){jQuery("body").find("ul.cat-list").eq(index).find("li > div.shop-list-deparment").eq(indexDepart-x).css("min-height",maxHeight);
}maxHeight=0;
}else{if((lengthLiProd-1)==indexDepart){var lastProducts=(lengthLiProd%4)-1;
if(lastProducts>=1){for(var x=lastProducts;
x>=0;
x--){jQuery("body").find("ul.cat-list").eq(index).find("li > div.shop-list-deparment").eq(indexDepart-x).css("min-height",maxHeight);
}}}}count++;
});
});
}function categoryGridLiAutoHeight(){jQuery("ul.cat-grid").each(function(index){var count=1;
var maxHeight=0;
var lengthLi=jQuery(this).children("li").length;
var sectionName=jQuery(this).parent().parent().attr("class");
var module=0;
var countMax=0;
if(typeof sectionName==="undefined"||sectionName===""){sectionName=jQuery(this).parent().parent().parent().attr("class");
}if(typeof sectionName!="undefined"&&(sectionName==="shopping-left-container"||(sectionName.indexOf("shopping-left-container")>=0))){module=3;
countMax=2;
}else{module=4;
countMax=3;
}jQuery(this).find("> li").each(function(indexLi){var liHeight=jQuery(this).height();
if(maxHeight<liHeight){maxHeight=liHeight;
}if(count%module==0&&indexLi!=0){for(var x=countMax;
x>=0;
x--){jQuery("body").find("ul.cat-grid").eq(index).find("> li").eq(indexLi-x).css("min-height",maxHeight);
}maxHeight=0;
}else{if((lengthLi-1)==indexLi){var lastLi=(lengthLi%module)-1;
if(lastLi>=1){for(var x=lastLi;
x>=0;
x--){jQuery("body").find("ul.cat-grid").eq(index).find("> li").eq(indexLi-x).css("min-height",maxHeight);
}}}}count++;
});
});
}function recipeBoxAutoHeight(){jQuery(".recipecontainer .recipewrapper").each(function(index){lengthRecipeBox=jQuery(".recipecontainer .recipewrapper").length;
heightBox=jQuery(this).height();
if(index==0){maxHeight=heightBox;
}if(maxHeight<heightBox){maxHeight=heightBox;
}if((index+1)%3==0){for(position=2;
position>=0;
position--){jQuery(".recipecontainer .recipewrapper").eq(index-position).css("min-height",maxHeight+3);
}maxHeight=0;
}else{if((lengthRecipeBox-1)==index&&(lengthRecipeBox%3!=0)){for(position=((lengthRecipeBox%3)-1);
position>=0;
position--){jQuery(".recipecontainer .recipewrapper").eq(index-position).css("min-height",maxHeight+3);
}maxHeight=0;
}}});
}var countofTotalLI=0;
function storeLocatorLiAutoHeight(){jQuery("ul.store-list").each(function(index){var count=1;
var maxHeight=0;
var lengthLi=jQuery(this).children("li").length;
var module=4;
var countMax=3;
jQuery(this).find("li").each(function(indexLi){var liHeight=jQuery(this).height();
if(maxHeight<liHeight){maxHeight=liHeight;
}if(count%module==0&&indexLi!=0){for(var x=countMax;
x>=0;
x--){jQuery("body").find("ul.store-list").eq(index).find("li").eq(indexLi-x).css("min-height",maxHeight);
}maxHeight=0;
}else{if((lengthLi-1)==countofTotalLI){var lastLi=(lengthLi%module)-1;
if(lastLi>=1){for(var x=lastLi;
x>=0;
x--){jQuery("body").find("ul.store-list").eq(index).find("li").eq(indexLi-x).css("min-height",maxHeight);
}}countofTotalLI=0;
}}count++;
countofTotalLI++;
});
});
}function departmentCarouselAutoHeight(){jQuery(".cat-carousel-content ul").each(function(index){var maxHeight=0;
var lengthLi=jQuery(this).children("li").length;
jQuery(this).find("li").each(function(indexLi){var liHeight=jQuery(this).height();
if(maxHeight<liHeight){maxHeight=liHeight;
}if((lengthLi-1)==indexLi){for(var x=indexLi;
x>=0;
x--){jQuery("body").find(".cat-carousel-content ul").eq(index).find("> li").eq(indexLi-x).css("min-height",maxHeight);
}}});
});
}function pdpCarouselAutoHeight(){jQuery(".pdp-carousel ul").each(function(index){var maxHeight=0;
var lengthLi=jQuery(this).children("li").length;
var modLength=lengthLi%4;
var countLi=0;
jQuery(this).find("li").each(function(indexLi){var liHeight=jQuery(this).height();
if(maxHeight<liHeight){maxHeight=liHeight;
}countLi++;
if(modLength==0){if(countLi==4){for(var x=3;
x>=0;
x--){jQuery(".pdp-carousel ul").eq(index).find("> li").eq(indexLi-x).css("min-height",maxHeight);
}countLi=0;
maxHeight=0;
}}else{if(modLength!=0&&((lengthLi-1)==indexLi)){for(var x=indexLi;
x>=0;
x--){jQuery(".pdp-carousel ul").eq(index).find("> li").eq(indexLi-x).css("min-height",maxHeight);
}}}});
});
}function articleCarouselAutoHeight(){jQuery(".cookingartilceswrapper .cat-carousel ul").each(function(index){var maxHeight=0;
var lengthLi=jQuery(this).children("li").length;
var modLength=lengthLi%3;
var countLi=0;
jQuery(this).find("li").each(function(indexLi){var liHeight=jQuery(this).height();
if(maxHeight<liHeight){maxHeight=liHeight;
}countLi++;
if(modLength==0){if(countLi==3){for(var x=2;
x>=0;
x--){jQuery(".cookingartilceswrapper .cat-carousel ul").eq(index).find("> li").eq(indexLi-x).css("min-height",maxHeight);
}countLi=0;
maxHeight=0;
}}else{if(modLength!=0&&((lengthLi-1)==indexLi)){for(var x=indexLi;
x>=0;
x--){jQuery(".cookingartilceswrapper .cat-carousel ul").eq(index).find("> li").eq(indexLi-x).css("min-height",maxHeight);
}}}});
});
}function subTitleDotAutoWidth(){jQuery(".cat-subtitle").each(function(index){var contentWidth=jQuery(this).width();
var subTitleWidth=jQuery(this).find("div").eq(1).width()+21;
var dotWidth=(contentWidth-subTitleWidth)/2;
if(dotWidth%7!=0){var restMod=Math.round((dotWidth%7)*2);
var dotWidthLeft=Math.floor(dotWidth)-restMod;
var dotWidthRight=Math.floor(dotWidth)+restMod;
if(dotWidthRight%7<5){dotWidthRight=dotWidthRight-(dotWidthRight%7);
}if(dotWidthLeft%7<5){dotWidthLeft=dotWidthLeft-(dotWidthLeft%7);
}jQuery(this).find("div").eq(0).css("width",dotWidthLeft);
jQuery(this).find("div").eq(2).css("width",dotWidthRight);
}else{jQuery(this).find("div").eq(0).css("width",dotWidth);
jQuery(this).find("div").eq(2).css("width",dotWidth);
}});
}function departmentDotAutoWidth(){jQuery(".cat-list .cat-list-deparment-name").each(function(index){parentWidht=jQuery(this).width();
childenWidth=0;
jQuery(this).children("div").each(function(indexChildren){childenWidth+=jQuery(this).outerWidth();
if(indexChildren==0){dotLeftWidth=jQuery(this).outerWidth();
}else{if(indexChildren==2){rightLeftWidth=jQuery(this).outerWidth();
}}});
remainingWidth=(parentWidht-childenWidth)-1;
if(remainingWidth>0){jQuery(this).children("div").eq(0).css("width",dotLeftWidth+Math.floor(remainingWidth/2));
jQuery(this).children("div").eq(2).css("width",rightLeftWidth+Math.floor(remainingWidth/2));
}});
}function scrollToTop(){if(jQuery(this).scrollTop()>70){jQuery(".scrollup").fadeIn();
}jQuery(window).scroll(function(){if(jQuery(this).scrollTop()>70){jQuery(".scrollup").fadeIn();
}else{jQuery(".scrollup").fadeOut();
}});
jQuery(".scrollup").click(function(){jQuery("html, body").animate({scrollTop:0},600);
return false;
});
}function checkedGeneralInput(){jQuery('.cutomize-checkbox input[type="checkbox"]').click(function(){var classCheckbox=jQuery(this).attr("class");
if(typeof classCheckbox==="undefined"||classCheckbox===""){jQuery(this).addClass("checked");
jQuery(this).attr("checked","checked");
jQuery(this).parent().children("label").css("background-position","0 -24px");
}else{jQuery(this).removeClass("checked");
jQuery(this).removeAttr("checked");
jQuery(this).parent().children("label").css("background-position","0 0");
}});
}function validateCheck(){jQuery(".cutomize-checkbox input").each(function(index){var disableAttr=jQuery(this).attr("disabled");
if(disableAttr==="disabled"){jQuery(this).prop("disabled",false);
jQuery(this).parent().children("label").removeClass("disabled");
jQuery(this).parent().addClass("enabled");
jQuery(this).parent().parent().children("div.text").removeClass("disabled");
}else{if(jQuery(this).parent().hasClass("enabled")){jQuery(this).parent().removeClass("enabled");
jQuery(this).prop("disabled",true);
jQuery(this).parent().children("label").addClass("disabled");
jQuery(this).parent().parent().children("div.text").addClass("disabled");
}}});
}function checkedInput(){jQuery(".pdp-addons input").click(function(){var classCheckbox=jQuery(this).attr("class");
if(typeof classCheckbox==="undefined"||classCheckbox===""){jQuery(this).addClass("checked");
jQuery(this).parent().attr("class","pdp-addons on");
jQuery(this).attr("checked","checked");
}else{jQuery(this).removeClass("checked");
jQuery(this).parent().attr("class","pdp-addons");
jQuery(this).removeAttr("checked");
}});
}function displayVideoShopping(){jQuery(".shopping-video-title").click(function(){if(jQuery(this).hasClass("on")){jQuery(".shopping-video").hide();
jQuery(this).removeClass("on");
}else{jQuery(".shopping-video").show();
jQuery(this).addClass("on");
}});
}function removeVideoShopping(){jQuery(".shopping-video-close").click(function(){jQuery(".shopping-video-container").remove();
$.ajax({url:contextRoot+"/includes/setcookieorprofile.jsp?source=shoppinglist",dataType:"html",type:"POST",data:"",success:function(data){}});
});
}function displayGuideSearch(){jQuery("#guide-search").focus(function(){jQuery(this).attr("value","");
jQuery(this).keyup(function(){jQuery(".my-list-autocomplete").fadeIn("slow");
});
});
jQuery(".my-list-autocomplete").click(function(){jQuery(".my-list-autocomplete").fadeOut("slow");
jQuery("#guide-search").attr("value","Start typing here to add to your list...");
});
$("#guide-search").bind("keydown",function(event){var keycode=(event.keyCode?event.keyCode:(event.which?event.which:event.charCode));
if(keycode==13){$("input.add-to-list").click();
return false;
}else{return true;
}});
}function displayRecieptAdd(){jQuery("#reciept-add").focus(function(e){e.preventDefault();
var existVal=jQuery(this).val();
var title=jQuery(this).attr("title");
if(existVal==title){jQuery(this).attr("value","");
jQuery(this).removeClass("ghost");
}});
$("#reciept-add").bind("keydown",function(event){var keycode=(event.keyCode?event.keyCode:(event.which?event.which:event.charCode));
if(keycode==13){$("input.add-to-list").click();
return false;
}else{return true;
}});
}function displayAheadSearch(id){jQuery(id).attr("value","");
jQuery(id).keyup(function(e){if(e.keyCode==13){jQuery(".aheadSearch").fadeIn("slow");
}else{jQuery(".aheadSearch .right-block").click(function(){jQuery(".aheadSearch").fadeOut();
});
}});
jQuery(".ghost").click(function(e){jQuery(".aheadSearch").fadeIn("slow");
});
jQuery(".search-container").hover(function(){},function(){jQuery(".aheadSearch").fadeOut("slow");
});
}function displayDropdown(id){jQuery(".atl-container").fadeOut();
jQuery(".atl-recipe-container").fadeOut();
jQuery(id).parent().children("div.atl-container").fadeIn();
jQuery(jQuery(id).parent().children("div.atl-container")).click(function(){jQuery(id).parent().children("div.atl-container").fadeOut();
});
jQuery(id).parent().children("div.atl-container").hover(function(){},function(){jQuery(id).parent().children("div.atl-container").fadeOut();
});
}function displayRecipeDropdown(id){jQuery(".atl-recipe-container").fadeOut();
jQuery(".atl-container").fadeOut();
jQuery(id).parent().children("div.atl-recipe-container").fadeIn();
jQuery(jQuery(id).parent().children("div.atl-recipe-container")).click(function(){jQuery(id).parent().children("div.atl-recipe-container").fadeOut();
});
jQuery(id).parent().children("div.atl-recipe-container").hover(function(){},function(){jQuery(id).parent().children("div.atl-recipe-container").fadeOut();
});
}function setSelectedShoppingList(contextRoot,isWarmUser){if(isWarmUser){location.href=contextRoot+"/my-account/login?source=mylist&action=browseRedirect";
}else{var selectedShoppingListId=document.getElementById("miniListSelect").value;
var url=contextRoot+"/mylist/includes/miniListServer.jsp?selectedShoppingListId="+selectedShoppingListId;
$.ajax({url:url,success:function(data){$("#mini-shopping-list").html(data);
$("#miniListSelect").val(selectedShoppingListId);
jQuery(".four-circular-carousel-shopping").jcarousel({wrap:null,scroll:4});
$(".four-circular-carousel-shopping").each(function(index){countLi=jQuery(this).children("li").length;
if(countLi<=4){jQuery(this).css("position","static");
jQuery("#mini-shopping-list").find(".jcarousel-prev").hide();
jQuery("#mini-shopping-list").find(".jcarousel-next").hide();
}});
jQuery(".mini-list-container .title .closeitem a").click(function(){jQuery("#mini-shopping-list,#header div.section-b ul.menu li.header .lists .icon").hide();
jQuery("#header div.section-b ul.menu li.header .lists a").removeClass("expanded");
$.ajax({url:contextRoot+"/mylist/includes/addAttributeToSession.jsp?operation=close",dataType:"html",type:"POST",data:"",success:function(data){}});
});
$("#mini-shopping-list,#header div.section-b ul.menu li.header .lists .icon").show();
$("#header div.section-b ul.menu li.header .lists a").addClass("expanded");
$("#minilisttriangle").css("display","inline");
}});
}}function shoppingList(shoppingListId){var ajaxDummyParameter=Math.random();
var url=contextRoot+"/mylist/includes/miniListServer.jsp?selectedShoppingListId="+shoppingListId+"&ajaxDummyParameter="+ajaxDummyParameter;
$.ajax({url:url,success:function(data){$("#mini-shopping-list").html(data);
$("#miniListSelect").val(shoppingListId);
jQuery(".four-circular-carousel-shopping").jcarousel({wrap:null,scroll:4});
$(".four-circular-carousel-shopping").each(function(index){countLi=jQuery(this).children("li").length;
if(countLi<=4){jQuery(this).css("position","static");
jQuery("#mini-shopping-list").find(".jcarousel-prev").hide();
jQuery("#mini-shopping-list").find(".jcarousel-next").hide();
}});
jQuery(".mini-list-container .title .closeitem a").click(function(){jQuery("#mini-shopping-list,#header div.section-b ul.menu li.header .lists .icon").hide();
jQuery("#header div.section-b ul.menu li.header .lists a").removeClass("expanded");
$.ajax({url:contextRoot+"/mylist/includes/addAttributeToSession.jsp?operation=close",dataType:"html",type:"POST",data:"",success:function(data){}});
});
$("#mini-shopping-list,#header div.section-b ul.menu li.header .lists .icon").show();
$("#header div.section-b ul.menu li.header .lists a").addClass("expanded");
$("#minilisttriangle").css("display","inline");
}});
}function showGivenShoppingListInMinilist(){jQuery("#mini-shopping-list,#header div.section-b ul.menu li.header .lists .icon").show();
$("#minilisttriangle").css("display","inline");
jQuery("#header div.section-b ul.menu li.header .lists a").addClass("expanded");
}function showShoppingListInMinilist(listId){$.ajax({url:contextRoot+"/mylist/includes/addAttributeToSession.jsp?operation=addToList",dataType:"html",type:"POST",data:"",success:function(data){}});
$.ajax({url:contextRoot+"/mylist/includes/shoppinglistitemscheck.jsp",dataType:"html",type:"POST",data:"",success:function(data){var isColdUser=data;
if(isColdUser.trim()=="YES"){isUnLoad="yes";
}else{isUnLoad="no";
}}});
shoppingList(listId);
jQuery("html, body").animate({scrollTop:0},600);
}function hideMiniShoppinglist(){jQuery("#mini-shopping-list,#header div.section-b ul.menu li.header .lists .icon").hide();
jQuery("#header div.section-b ul.menu li.header .lists a").removeClass("expanded");
}function addToList(productId,skuId,listId){$("#shopListLimitError").removeClass("show").addClass("dontShow");
var profileListId=$("input#profileActiveShoppingListId").val();
if(profileListId!=undefined&&profileListId!=""){listId=profileListId;
}var quantity=$("input#quantity"+productId).val();
if(quantity==undefined||quantity==""||quantity==0){alert("Please enter valid quantity");
return false;
}$.ajax({url:contextRoot+"/mylist/includes/addToList.jsp?productId="+productId+"&skuId="+skuId+"&listId="+listId+"&quantity="+quantity,dataType:"html",type:"POST",data:"",success:function(data){if(data.indexOf("addtolisterror")!=-1){$("#shopListLimitError").removeClass("dontShow").addClass("show");
jQuery("html, body").animate({scrollTop:0},600);
}else{showShoppingListInMinilist(listId);
}resetQuantity("quantity"+productId);
}});
$(document).ajaxError(function(){});
}function addToListFromPrimoPick(productId,skuId,listId){$("#shopListLimitError").removeClass("show").addClass("dontShow");
var profileListId=$("input#profileActiveShoppingListId").val();
if(profileListId!=undefined&&profileListId!=""){listId=profileListId;
}var quantity="1";
$.ajax({url:contextRoot+"/mylist/includes/addToList.jsp?productId="+productId+"&skuId="+skuId+"&listId="+listId+"&quantity="+quantity,dataType:"html",type:"POST",data:"",success:function(data){if("Error"==data){window.location=contextRoot+"/applicationerror.jsp";
}if(data.indexOf("addtolisterror")!=-1){$("#shopListLimitError").removeClass("dontShow").addClass("show");
jQuery("html, body").animate({scrollTop:0},600);
}else{showShoppingListInMinilist(listId);
}resetQuantity(skuId+"_"+productId+"_quantity");
}});
$(document).ajaxError(function(){});
}function addToListFromPDP(productId,skuId,listId){$("#shopListLimitError").removeClass("show").addClass("dontShow");
var quantity=$("input#quantity").val();
if(quantity==undefined||quantity==""||quantity==0){alert("Please enter valid quantity");
return false;
}$.ajax({url:contextRoot+"/mylist/includes/addToList.jsp?productId="+productId+"&skuId="+skuId+"&listId="+listId+"&quantity="+quantity+"&pageType=pdp",dataType:"html",type:"POST",data:"",success:function(data){if(data.indexOf("addtolisterror")!=-1){$("#shopListLimitError").removeClass("dontShow").addClass("show");
jQuery("html, body").animate({scrollTop:0},600);
}else{showShoppingListInMinilist(listId);
}resetQuantity("quantity");
}});
$(document).ajaxError(function(){});
}function addToListFromCategory(productId,skuId,listId,unknownItemId){$("#shopListLimitError").removeClass("show").addClass("dontShow");
var profileListId=$("input#profileActiveShoppingListId").val();
if(profileListId!=undefined&&profileListId!=""){listId=profileListId;
}var quantity=$("input#"+skuId+"_"+productId+"_quantity").val();
if(quantity==undefined||quantity==""||quantity==0){alert("Please enter valid quantity");
return false;
}$.ajax({url:contextRoot+"/mylist/includes/addToList.jsp?productId="+productId+"&skuId="+skuId+"&listId="+listId+"&unknownItemId="+unknownItemId+"&quantity="+quantity,dataType:"html",type:"POST",data:"",success:function(data){if(data.indexOf("addtolisterror")!=-1){$("#shopListLimitError").removeClass("dontShow").addClass("show");
jQuery("html, body").animate({scrollTop:0},600);
}else{showShoppingListInMinilist(listId);
}resetQuantity(skuId+"_"+productId+"_quantity");
}});
$(document).ajaxError(function(){});
}function addToListFromCompare(productId,skuId,listId){$("#shopListLimitError").removeClass("show").addClass("dontShow");
var profileListId=$("input#profileActiveShoppingListId").val();
if(profileListId!=undefined&&profileListId!=""){listId=profileListId;
}var quantity=$("input#quantity_"+productId+"_"+skuId).val();
if(quantity==undefined||quantity==""||quantity==0){alert("Please enter valid quantity");
return false;
}$.ajax({url:contextRoot+"/mylist/includes/addToList.jsp?productId="+productId+"&skuId="+skuId+"&listId="+listId+"&quantity="+quantity,dataType:"html",type:"POST",data:"",success:function(data){if(data.indexOf("addtolisterror")!=-1){$("#shopListLimitError").removeClass("dontShow").addClass("show");
jQuery("html, body").animate({scrollTop:0},600);
}else{showShoppingListInMinilist(listId);
}resetQuantity("quantity_"+productId+"_"+skuId);
}});
$(document).ajaxError(function(){});
}function resetQuantity(id){$("#"+id).val(1);
}function getPrintLayOut(shoppingListId,isUserHot){var inputElements=document.getElementsByTagName("input");
var checkedValue="";
var href=contextRoot+"/mylist/includes/shoppingListPrintTemplate.jsp?shoppingListId="+shoppingListId+"&aisle="+isUserHot+"&selectedPrintOption=";
for(var i=0;
inputElements[i];
++i){if(inputElements[i].className=="checked"&&inputElements[i].checked){checkedValue=checkedValue+inputElements[i].value;
}}href=href+checkedValue;
window.open(href,"mywindow","status=1,width=700,height=700,scrollbars=1");
}function setBtnOnMyList(){$(".input-qty").bind("keydown",function(event){var keycode=(event.keyCode?event.keyCode:(event.which?event.which:event.charCode));
if(keycode==13){document.getElementById("updateMyList").click();
return false;
}else{return true;
}});
}function removeClickEvent(){$("input.add-to-list").click(function(){$("input.add-to-list").unbind("click",handler);
});
$("input#updateMyList").click(function(){$("input#updateMyList").unbind("click",handler);
});
}function checkForShoppingListItems(){$.ajax({url:contextRoot+"/mylist/includes/shoppinglistitemscheck.jsp",dataType:"html",type:"POST",data:"",success:function(data){var isColdUser=data;
if(isColdUser.trim()=="YES"){isUnLoad="yes";
}else{isUnLoad="no";
}}});
}checkForShoppingListItems();
function toggleBlackBox(){jQuery.ajax({url:contextRoot+"/includes/getsessionvalue.jsp",type:"GET",global:false,dataType:"xml",success:function(data){$xml=$(data);
if($xml.find("result").text()){var success=$xml.find("result").text();
if(success=="true"){$("#boxcollapsecontrol").attr("title","open");
}else{jQuery("#header .section-b .collapse-controller").parent().parent().find("li.body").toggle(0,"swing",function(arg){if(jQuery("#header .section-b .collapse-controller").is(":visible")){$("#blackbox").removeClass("collapsed").addClass("expanded");
$("#boxcollapsecontrol").attr("title","close");
}});
}}}});
}function isAllUpperCase(text){if(text==text.toUpperCase()){return true;
}return false;
}function loadCouponSel(){window.location.href=contextRoot+"/digital-coupon/coupon-selection";
}function onBlur(el){if(el.value==""){el.value=el.defaultValue;
}}function onFocus(el){if(el.value==el.defaultValue){el.value="";
}jQuery(".textfield-search").removeClass("ghost");
jQuery(function(){var allergyTags=["Allergy Test A1","Allergy Test A2","Allergy Test A3"];
jQuery(".textfield-search").autocomplete({source:allergyTags});
});
}function activateSubMenu(subMenuId){$("li.item").each(function(){if($(this).attr("id")==subMenuId){$(this).addClass("active");
}});
}function highlightLeftNav(leftNavId){var aObject=document.getElementById(leftNavId);
aObject.className="active-link";
}function itemCompareAutoHeight(){jQuery("ul.nutrfac-list").each(function(index){var count=1;
var maxHeight=0;
var lengthLi=jQuery(this).children("li").length;
var module=4;
var countMax=3;
jQuery(this).find("div.supplement-facts").each(function(indexLi){var liHeight=jQuery(this).height();
if(maxHeight<liHeight){maxHeight=liHeight;
}if(count%module==0&&indexLi!=0){for(var x=countMax;
x>=0;
x--){jQuery("body").find("ul.nutrfac-list").eq(index).find("div.supplement-facts").eq(indexLi-x).css("min-height",maxHeight);
}maxHeight=0;
}else{if((lengthLi-1)==indexLi){var lastLi=(lengthLi%module)-1;
if(lastLi>=1){for(var x=lastLi;
x>=0;
x--){jQuery("body").find("ul.nutrfac-list").eq(index).find("div.supplement-facts").eq(indexLi-x).css("min-height",maxHeight);
}}}}count++;
});
});
}function couponCarouseleAutoHeight(){jQuery("div.jcarousel-skin-mlts ul").each(function(index){var count=1;
var maxHeight=0;
var lengthLi=jQuery(this).children("li").length;
jQuery(this).find("li div.details").each(function(indexLi){var liHeight=jQuery(this).height();
if(maxHeight<liHeight){maxHeight=liHeight;
}for(var x=lengthLi-1;
x>=0;
x--){jQuery("body").find("div.jcarousel-skin-mlts").eq(index).find("li div.details").eq(indexLi-x).css("min-height",maxHeight);
}});
});
}function substituteHyphen(){$('*:contains("-")').contents().each(function(){if(this.nodeType==3&&$.trim(this.textContent?this.textContent:this.nodeValue)!=""){var e=document.createElement("span");
var escaped=this.nodeValue.replace(/-/g,"&#8209;");
e.innerHTML=document.createTextNode(escaped).nodeValue;
this.nodeValue=e.textContent?e.textContent:e.innerText;
}});
heightAlignmentTab();
}function NormalizeSubmenu(){$("#top-category-menu .menu .item a").each(function(){var text=this.textContent?this.textContent:this.innerText;
var label=$.trim(text);
var words=label.split(" ");
if(words.length>=3){this.innerHTML='<span class="submenu-first-line">'+words[0]+" "+words[1]+'</span><span class="submenu-second-line">'+words.slice(2).join(" ");
}else{this.innerHTML='<span class="submenu-only-line">'+$.trim(words.join(" "))+"</span>";
}});
}function setUnloadValueForEvents(){$(document).bind("keypress",function(e){if(e.keyCode==116){isUnLoad="no";
}});
if($.browser.msie){$("body").on("click","a",function(){isUnLoad="no";
});
}else{$("a").bind("click",function(){if("shoplistGridView"!=this.id&&"shoplistListView"!=this.id&&"recipeGridView"!=this.id&&"recipeListView"!=this.id&&"addNoteAnchor"!=this.id&&"shopListPrint"!=this.id&&!($(this).hasClass("btn-edit")||$(this).hasClass("shopping-video-title")||$(this).hasClass("shopping-video-close"))){isUnLoad="no";
}});
}$("body").on("click","button",function(){isUnLoad="no";
});
$("body").on("click","select",function(){if("shopListSortSelect"!=this.id&&"sortBySelect"!=this.id){isUnLoad="no";
}});
$("form").bind("submit",function(){isUnLoad="no";
});
$("body").on("click","input[type=submit]",function(){isUnLoad="no";
});
$("body").on("click","input[type=button]",function(){isUnLoad="no";
});
$("body").on("click","input[type=checkbox]",function(){isUnLoad="no";
});
}function showHideRecipeCategory(id){if(jQuery(id).parent().find(".hidden").length>0){jQuery(id).parent().find(".hidden").fadeIn("slow").attr("class","show");
jQuery(id).text("Less...").addClass("less");
}else{jQuery(id).parent().find(".show").fadeOut("slow").attr("class","hidden");
jQuery(id).text("More...").removeClass("less");
}}function closeMessageToolTip(){jQuery(".tab-message-container").empty();
jQuery(".tab-message-container").remove();
}function closeSplashModal(){$.modal.close();
$("#splash-bg").remove();
}