function isEmpty(id){if($(id)==null||$(id).val()==""){return true;
}return false;
}function isEmptyWithValue(id,value){if(isEmpty(id)||$(id).val()==value){return true;
}return false;
}function validateEmail(id){return validateRegEx(".+@.+",id);
}function validatePassword(id){return validateRegEx("(?=.*\\d)(?=.*[a-zA-Z]).{8,25}",id);
}function validateRegEx(regExStr,id){var regEx=new RegExp(regExStr);
if(regEx.test($(id).val())){return true;
}return false;
}function validateEqual(id1,id2){if($(id1).val()==$(id2).val()){return true;
}return false;
}function validateEmptyAndSetGhostText(inputFieldName,ghostValue,ghostClass){if(isEmpty(inputFieldName)){$(inputFieldName).val(ghostValue);
$(inputFieldName).addClass(ghostClass);
}}function removeGhostTextFromInputField(inputFieldName,ghostValue,inputValue,ghostClass){if(ghostValue==inputValue){$(inputFieldName).val("");
}$(inputFieldName).removeClass(ghostClass);
}function getMonth(date){var month=date.getMonth()+1;
return month<10?"0"+month:month;
}function getDay(date){var date=date.getDate();
return date<10?"0"+date:date;
}function getMonthDifference(lastAvailableDate,earliestDate){var lastDateMonth=lastAvailableDate!=null?lastAvailableDate.substr(0,2):3;
var firstDateMonth=earliestDate!=null?earliestDate.substr(0,2):0;
var maxDateValue=(lastDateMonth-firstDateMonth)+"M";
return maxDateValue;
}function isRequestSecure(){if(window.location.protocol=="https:"){return true;
}else{return false;
}}$(document).ready(function(){titleMessage();
titlemessageWithCss();
});
function titleMessage(){$(".titlemessage").each(function(){if(this.value==""){this.value=$(this).attr("title");
}$(this).keydown(function(){if(this.value==$(this).attr("title")){this.value="";
}});
$(this).blur(function(){if(this.value==""){this.value=$(this).attr("title");
}});
$(this).focus(function(){if(this.value==$(this).attr("title")){this.value="";
}});
});
}function titlemessageWithCss(){$(".titlemessagewithcss").each(function(){var attrTitleVal=$(this).attr("title");
if(this.value==""||this.value==attrTitleVal){this.value=$(this).attr("title");
$(this).addClass("ghost");
}$(this).focus(function(){if(this.value==$(this).attr("title")){this.value="";
$(this).removeClass("ghost");
}});
$(this).blur(function(){if(this.value==""){this.value=$(this).attr("title");
$(this).addClass("ghost");
}});
});
}