jQuery(document).ready(function(){$("body").on("click","button#sendEmailToFriend",validateEmailForm);
});
function checkMaxLength(){currentLengthInTextarea=$("#emailmessage").val().length;
if(currentLengthInTextarea>(300)){$("#emailmessage").val($("#emailmessage").val().slice(0,300));
}}var openOverLay=false;
var nameReg=/^[A-Za-z\s]+$/;
var emailReg=/^[_A-Za-z0-9-]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$/;
function validateEmailForm(form){var isError=false;
isError=validForm();
if(isError){return false;
}else{$("form#emailToFriendForm").submit();
}return false;
}function validForm(){var error=false;
if($("#recipientEmails").val().trim()==""){error=true;
$("#recipentEmailErrMsg").removeClass("show").addClass("dontShow");
$("#emptyRecipentEmailErrMsg").removeClass("dontShow").addClass("show");
$("#recipientEmailLabel").addClass("error-label");
}else{if(!validateMultipleEmailIds()){error=true;
$("#emptyRecipentEmailErrMsg").removeClass("show").addClass("dontShow");
$("#recipentEmailErrMsg").removeClass("dontShow").addClass("show");
$("#recipientEmailLabel").addClass("error-label");
}else{$("#emptyRecipentEmailErrMsg").removeClass("show").addClass("dontShow");
$("#recipentEmailErrMsg").removeClass("show").addClass("dontShow");
$("#recipientEmailLabel").removeClass("error-label");
}}if($("#yourName").val().trim()==""){error=true;
$("#emptyUserNameErrMsg").removeClass("dontShow").addClass("show");
$("#userNameErrMsg").removeClass("show").addClass("dontShow");
$("#nameLabel").addClass("error-label");
}else{if(!validateName()){error=true;
$("#emptyUserNameErrMsg").removeClass("show").addClass("dontShow");
$("#userNameErrMsg").removeClass("dontShow").addClass("show");
$("#nameLabel").addClass("error-label");
}else{$("#emptyUserNameErrMsg").removeClass("show").addClass("dontShow");
$("#userNameErrMsg").removeClass("show").addClass("dontShow");
$("#nameLabel").removeClass("error-label");
}}if($("#yourEmail").val().trim()==""){error=true;
$("#emptyUserEmailErrMsg").removeClass("dontShow").addClass("show");
$("#userEmailErrMsg").removeClass("show").addClass("dontShow");
$("#userEmailLabel").addClass("error-label");
}else{if(!validateUserEmailId()){error=true;
$("#userEmailErrMsg").removeClass("dontShow").addClass("show");
$("#emptyUserEmailErrMsg").removeClass("show").addClass("dontShow");
$("#userEmailLabel").addClass("error-label");
}else{$("#emptyUserEmailErrMsg").removeClass("show").addClass("dontShow");
$("#userEmailErrMsg").removeClass("show").addClass("dontShow");
$("#userEmailLabel").removeClass("error-label");
}}if(error){$("#emailErrorMsgContent").removeClass("dontShow").addClass("show");
return true;
}else{var emailMsg=$("#emailmessage").val().trim();
if(emailMsg!=""){emailMsg=emailMsg.replace(/"/g,"");
$("#emailmessage").val(emailMsg);
}$("#emailErrorMsgContent").removeClass("show").addClass("dontShow");
return false;
}}function validateName(){var yourName=$("#yourName").val();
if(!nameReg.test(yourName)){return false;
}else{return true;
}}function validateUserEmailId(){var emailId=$("#yourEmail").val();
if(!emailReg.test(emailId.trim())){return false;
}else{return true;
}}function validateMultipleEmailIds(){var multipleIds=$("#recipientEmails").val();
var Ids=multipleIds.split(",");
for(var i=0;
i<Ids.length;
i++){if(!validateEmailId(Ids[i].trim())){return false;
}}return true;
}function validateEmailId(emailId){return(emailReg.test(emailId))?true:false;
}function loadEmailOverlay(id,contentType){var url=contextRoot+"/includes/emailtofriendoverlay.jsp";
var div="emailOverlayDiv";
loadEmailOverlayContent(url,div,id,contentType,true);
}function loadEmailOverlayContent(url,div,id,contentType,openOverLay){var srcUrl=$("#sourceUrl").val();
var contentName=$("#contentName").val();
var contentDesc=$("#contentDesc").val();
var contentUrl=$("#contentUrl").val();
var contentExpDate=$("#contentExpDate").val();
var reviewCount=$("#reviewCount").val();
var reviewRating=$("#reviewRating").val();
var divId="#"+div;
$.ajax({url:url,dataType:"html",type:"POST",data:{successUrl:srcUrl,contentId:id,contentType:contentType,contentName:contentName,contentDesc:contentDesc,contentUrl:contentUrl,contentExpDate:contentExpDate,reviewCount:reviewCount,reviewRating:reviewRating,},success:function(data){$(divId).html(data);
}});
if(openOverLay){$(divId).modal({minWidth:735,minHeight:625,fixed:false,top:[20]});
$("#emailOverlayDiv").fadeIn();
}}function closeEmailModal(){$("#modalWindow").empty();
$.modal.close();
}function closeEmailModalOverCoupon(){$("#modalWindow").empty();
$("#emailOverlayDiv").fadeOut();
}function loadEmailSuccessOverlay(){$("#emailSuccessOverlayDiv").load(contextRoot+"/includes/emailsuccessoverlay.jsp");
$("#emailSuccessOverlayDiv").modal({minWidth:475,minHeight:235});
}function loadProfileUpdateOverlay(page){$("#profileUpdateOverlayDiv").load(contextRoot+"/includes/profileupdateoverlay.jsp?page="+page);
$("#profileUpdateOverlayDiv").modal({minWidth:475,minHeight:235});
}