jQuery(document).ready(function(){updateRecipeTabClick();
testCall();
loadMoreFunc();
});
function updateRecipeTabClick(){$("li[id^='section-']").click(function(index){var idButton=$(this).attr("id");
$("ul[id^='tab-']").hide();
var count=idButton.substring(idButton.length-1,idButton.length);
$("ul#tab-"+count).show();
var arr=idButton.split("-");
var count=arr[1];
var total=$("#total_"+count).val();
var currentShowing=$("#tab-"+count).children("li").length;
if(currentShowing>=total){currentShowing=total;
$("div.content-block-5").find("button.load-more-recipes").hide();
}else{$("div.content-block-5").find("button.load-more-recipes").show();
}});
}function testCall(){$(".content-block-5 li").click(function(index,elem){$(".content-block-5 .tabs li").children().addClass("unselected");
$(this).children().removeClass("unselected");
$("div.content-block-5").find("div.triangle1").hide();
$(this).find("div.triangle1").show();
});
}function loadMoreFunc(){$("button.load-more-recipes").on("click",function(){var currentSection=$(".content-block-5 .tabs li").children().not(".unselected");
var currentSectionId=$(currentSection).parent("li").attr("id");
var arr=currentSectionId.split("-");
var count=arr[1];
var total=$("#total_"+count).val();
var section=$("#sectionId_"+count).val();
var currentShowing=$("#tab-"+count).children("li").length;
var thisButton=this;
var start=currentShowing+1;
$.get("includes/homepromorecipeslist.jsp?start="+start+"&howMany=3&section="+section,function(data){$("#tab-"+count).append(data);
$.scrollTo($("#tab-"+count+" > li:nth-child("+start+")"),800);
$("div.scrollwrapper").show();
currentShowing=currentShowing+3;
if(currentShowing>=total){currentShowing=total;
$(thisButton).hide();
}});
});
}