(function($j){$j.EndecaSearchSuggestor=function(ele,opts){this._active=true;
this._options=opts;
this._lastValue="";
this._element=ele;
this._container=$j('<div class="aheadSearch"></>');
this._timeOutId=this._options.timeOutId;
this._contextPath=this._options.contextPath;
this._hideTimeOutId;
this._selectedIndex=-1;
this._selectedID="";
var suggestor=this;
$j("body").append(this._container);
ele.keydown(function(e){switch(e.keyCode){case 38:if(suggestor._active){suggestor.moveToPrev();
}else{suggestor.show();
}break;
case 40:if(suggestor._active){suggestor.moveToNext();
}else{suggestor.show();
}break;
case 9:suggestor.hide();
break;
case 13:if(suggestor._active&&suggestor._selectedIndex!=-1){e.preventDefault();
suggestor.selectItem();
return false;
}break;
case 27:if(suggestor._active){suggestor.hide();
}break;
default:suggestor.handleRequest();
}});
};
$j.EndecaSearchSuggestor.prototype.moveToPrev=function(){if(this._selectedIndex==-1){this._selectedIndex=0;
}else{if(this._selectedIndex==0){return;
}this._selectedIndex--;
}$j(".dimResult",this._container).removeClass("active");
obj=$j($j(".dimResult",this._container).get(this._selectedIndex));
$j(obj).addClass("active");
};
$j.EndecaSearchSuggestor.prototype.moveToNext=function(){if(this._selectedIndex==-1){this._selectedIndex=0;
}else{if(this._selectedIndex==$j(".dimResult",this._container).size()-1){return;
}this._selectedIndex++;
}$j(".dimResult",this._container).removeClass("active");
obj=$j($j(".dimResult",this._container).get(this._selectedIndex));
$j(obj).addClass("active");
};
$j.EndecaSearchSuggestor.prototype.selectItem=function(){if(this._selectedIndex==-1){return;
}var url=$j("a",$j(".dimResult",this._container).get(this._selectedIndex)).attr("href");
document.location.href=url;
};
$j.EndecaSearchSuggestor.prototype.hide=function(){this._container.hide();
this._active=false;
};
$j.EndecaSearchSuggestor.prototype.show=function(){if(this._container.is(":hidden")){this.setPosition();
this._container.show();
this._active=true;
this._selectedIndex=-1;
}};
$j.EndecaSearchSuggestor.prototype.handleRequest=function(){var suggestor=this;
var defaultSearchText="Search products, recipes, and more";
var callback=function(){var text=$j.trim(suggestor._element.val());
if(""!=text&&defaultSearchText!=text&&text!=suggestor._lastValue){if(text.length>=suggestor._options.minAutoSuggestInputLength){suggestor.requestData();
}else{suggestor.hide();
}}suggestor._lastValue=text;
};
if(this._timeOutId){clearTimeout(this._timeOutId);
}this._timeOutId=setTimeout(callback,this._options.delay);
};
$j.EndecaSearchSuggestor.prototype.requestData=function(){var suggestor=this;
var response=$j.ajax({url:suggestor.composeUrl(),dataType:"html",async:true,success:function(data){suggestor.showSearchResult(data);
}});
};
$j.EndecaSearchSuggestor.prototype.composeUrl=function(){var url=this._options.autoSuggestServiceUrl;
var searchTerm=$j.trim(this._element.val());
if(url.indexOf("?")==-1){url+="?";
}else{url+="&";
}url+="q="+searchTerm;
return url;
};
$j.EndecaSearchSuggestor.prototype.showSearchResult=function(data){if(data!=null){this._container.html(data);
this.bindEventHandler();
this.show();
}else{this.hide();
}};
$j.EndecaSearchSuggestor.prototype.bindEventHandler=function(){var suggestor=this;
$j("div.aheadSearch li.dimResult").mouseover(function(e){var text=$("a",this).text();
var lastSel=$j(".dimResult.active",suggestor._container).attr("id");
$j(".dimResult.active",suggestor._container).removeClass("active");
$j(this).addClass("active");
});
$j("li.dimResult",this._container).click(function(e){suggestor.selectItem();
});
$j("a",$j("li.dimResult",this._container)).click(function(e){suggestor.selectItem();
});
$j(".dimRoots",this._container).click(function(){clearTimeout(suggestor._hideTimeOutId);
suggestor._element.focus();
});
$j("div.aheadSearch li.dimResult a").mouseover(function(e){e.preventDefault();
e.stopPropagation();
});
};
$j.EndecaSearchSuggestor.prototype.setPosition=function(){var offset=this._element.offset();
this._container.css({top:offset.top+this._element.outerHeight(),left:offset.left});
};
$j.fn.endecaSearchSuggest=function(options){var opts=$j.extend({},$j.fn.endecaSearchSuggest.defaults,options);
this.each(function(){var element=$j(this);
new $j.EndecaSearchSuggestor(element,opts);
});
};
$j.fn.endecaSearchSuggest.defaults={minAutoSuggestInputLength:2,displayImage:false,delay:250,autoSuggestServiceUrl:"",collection:"",searchUrl:"",containerClass:"dimSearchSuggContainer",defaultImage:"no_image.gif"};
})(jQuery);
