$(document).ready(function(){var departmentSelected=$("#sidebar > div.sideBarTitle > a").text();
var departmentSelected=$.trim(departmentSelected.toLowerCase());
$("ul.nav > li.nav-Cat > a").each(function(){var departmentLi=$.trim($(this).text());
if(departmentSelected===departmentLi.toLowerCase()){$(this).addClass("nav-Selected");
}});
$("#sidebar ul li ul li ul li").prepend("- ");
var lengthNav=$("#sidebar > ul.leftNavCategory > li").length;
if($("#sidebar > ul.leftNavCategory > li").eq(lengthNav-1).children().length>0){$("#sidebar > ul.leftNavCategory > li").eq(lengthNav-1).has("ul").attr("class","last");
}else{$("#sidebar > ul.leftNavCategory > li").eq(lengthNav-2).attr("class","last");
}var lengthFeatureNav=$("#sidebar > ul.featureLeftNav > li").length;
if($("#sidebar > ul.featureLeftNav > li").eq(lengthFeatureNav-1).children().length>0){$("#sidebar > ul.featureLeftNav > li").eq(lengthFeatureNav-1).has("ul").attr("class","last");
}else{$("#sidebar > ul.featureLeftNav > li").eq(lengthFeatureNav-2).attr("class","last");
}$(".ymal ul.cat-list li:nth-child(5n)").addClass("fifth");
$("#sidebar h4:first").addClass("first");
$("ul.tab-nav li:first").addClass("first");
$("ol.checkout-nav li:nth-child(3n)").addClass("third");
$("ol.checkout-nav li:last").addClass("last");
$(".topnav-wl").click(wlExpand);
$("#minicart-link").hover(function(){cartExpand();
});
$("textarea").keyup(function(e){var limit=parseInt($(this).attr("maxlength"));
var text=$(this).val();
var chars=text.length;
if(chars>limit){var new_text=text.substr(0,limit);
$(this).val(new_text);
}});
changeSelectColor();
});
$("ul.cat-list").ready(function(){$("ul.cat-list li:nth-child(4n)").addClass("fourth");
});
function getCookieValue(key){currentcookie=document.cookie;
if(currentcookie.length>0){firstidx=currentcookie.indexOf(key+"=");
if(firstidx!=-1){firstidx=firstidx+key.length+1;
lastidx=currentcookie.indexOf(";",firstidx);
if(lastidx==-1){lastidx=currentcookie.length;
}return unescape(currentcookie.substring(firstidx,lastidx));
}}return"";
}function cartExpand(){$.ajax({url:"/minicart/modals/modal-cartsummary.jsp",cache:false,dataType:"html",success:function(data){$("#minicart").html(data);
loadMini();
}});
}function wlExpand(){$.ajax({url:"/wishlist/modals/modal-wishlist.jsp",cache:false,dataType:"html",success:function(data){$("#miniwishlist").html(data);
loadMiniWl();
}});
}function loadMini(){$("#minicart").css("height","auto");
$("#minicart").css("display","block");
if($("#miniwishlist").css("display")!="none"){$("#miniwishlist").animate({"height":0},200);
$("#miniwishlist").fadeOut("fast");
}}function loadMiniWl(){$("#miniwishlist").css("height","auto");
var height=$("#miniwishlist").height();
$("#miniwishlist").css("height",height+"px");
var wlLinkPos=$(".topnav-wl").position();
var wlDivPos=$("#miniwishlist").position();
var wlNewLeft=wlLinkPos.left+parseInt($(".topnav-wl").css("margin-left"));
$("#miniwishlist").css("top",wlLinkPos.top+$(".topnav-wl").height());
$("#miniwishlist").css("left",wlNewLeft);
$("#miniwishlist").animate({"height":height},200);
$("#miniwishlist").fadeIn("fast");
$("#minicart").animate({"height":0},200);
$("#minicart").fadeOut("fast");
}function autoCloseCartContract(){setTimeout(cartContract,5000);
}function cartContract(){$("#minicart").fadeOut("fast");
}function wlContract(){$("#miniwishlist").animate({"height":0},200);
$("#miniwishlist").fadeOut("fast");
$(".close-miniwishlist").remove();
$(".miniwishlist-header").remove();
$(".miniwishlist-list").remove();
$(".miniwishlist-total").remove();
$(".miniwishlist-button").remove();
}function popupOptions(){this.height=screen.availHeight/2;
this.width=screen.availWidth/2;
this.top=0;
this.left=0;
this.toolbar=false;
this.location=false;
this.directories=false;
this.status=false;
this.menubar=false;
this.scrollbars=false;
this.resizable=false;
this.dependent=false;
this.build=_buildOptions;
}function _buildOptions(){var sTemp="";
sTemp+="height="+this.height+",";
sTemp+="width="+this.width+",";
sTemp+="top="+this.top+",";
sTemp+="left="+this.left+",";
sTemp+="scrollbars="+((this.scrollbars)?"yes":"no")+",";
sTemp+="toolbar="+((this.toolbar)?"yes":"no")+",";
sTemp+="location="+((this.location)?"yes":"no")+",";
sTemp+="directories="+((this.directories)?"yes":"no")+",";
sTemp+="status="+((this.status)?"yes":"no")+",";
sTemp+="menubar="+((this.menubar)?"yes":"no")+",";
sTemp+="resizable="+((this.resizable)?"yes":"no")+",";
sTemp+="dependent="+((this.dependent)?"yes":"no");
return(sTemp);
}function popup(winlink,winname){var winwidth=(arguments.length>=3)?arguments[2]:screen.availWidth/2;
var winheight=(arguments.length>=4)?arguments[3]:screen.availHeight/2;
var winscroll=(arguments.length>=5)?((arguments[4]=="1")?true:false):false;
var wintoolbar=(arguments.length>=6)?((arguments[5]=="1")?true:false):false;
var winresize=(arguments.length>=7)?((arguments[6]=="1")?true:false):true;
var winmenubar=(arguments.length>=8)?((arguments[7]=="1")?true:false):false;
var oOption=new popupOptions();
oOption.width=winwidth;
oOption.height=winheight;
oOption.scrollbars=winscroll;
oOption.toolbar=wintoolbar;
oOption.resizable=winresize;
oOption.menubar=winmenubar;
oOption.top=((screen.availHeight/2)-(winheight/2));
oOption.left=((screen.availWidth/2)-(winwidth/2));
oOption.location=false;
oOption.directories=false;
oOption.status=false;
oOption.dependent=false;
var sOptions=oOption.build();
window.open(winlink,null,sOptions);
}function addElement(rootElementID,content){$(rootElementID).append(content);
}if(typeof String.prototype.trim!=="function"){String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"");
};
}function checkBoxClick(){this.blur();
this.focus();
}function changeSelectColor(){$("select").each(function(){var selectOption=$(this).val();
if(selectOption==="0"||selectOption===""||selectOption===null){$(this).css({"color":"#666"});
}else{$(this).css({"color":"#333"});
}});
$("select").change(function(){if($(this).val()==="0"||$(this).val()===""||$(this).val()===null){$(this).css({"color":"#666"});
}else{$(this).css({"color":"#333"});
}});
}function setError(msg,resetMsg,productId,clook,isNote,noBorder){var messageField="addItemTocartError";
clook=clook||"false";
isNote=isNote||false;
noBorder=noBorder||false;
if(isNote){messageField="itemPresellMsg";
}if(clook=="true"){messageField="clookAddItemTocartError";
if(isNote){messageField="clookItemPresellMsg";
}}if(resetMsg){$("#"+messageField+productId).html("");
$("#"+messageField+productId).hide();
}else{msgDiv=$("<div>"+msg+"</div>");
if(productId==""||productId==undefined){return msgDiv.addClass("error-message");
}else{currentMessage=$("#"+messageField+productId).text();
addMessage=currentMessage.indexOf(msg);
if(addMessage<0){$("#"+messageField+productId).append(msgDiv);
}if(noBorder){$("#"+messageField+productId).css("border","none");
}$("#"+messageField+productId).show();
}}}