function loadStoreSelection(url,div,zipcode){var divId="#"+div;
$.ajax({url:url,dataType:"html",type:"POST",data:"zipcode="+zipcode,success:function(data){$(divId).html(data);
}});
}function loadCategoryStore(url,div,zipcode,endIndex){var divId="#"+div;
$.ajax({url:url,dataType:"html",type:"POST",data:"zipcode="+zipcode+"&endIndex="+endIndex,success:function(data){$(divId).html(data);
}});
}function findStore(){var zipcode=$("#zipcode").val();
loadCategoryStore(contextRoot+"/browse/includes/categorystore.jsp","storeSearch",zipcode,"10");
}function loadNextStorePage(endIndex){var zipcode=$("#zipcode").val();
loadCategoryStore(contextRoot+"/browse/includes/categorystore.jsp","storeSearch",zipcode,endIndex);
}function populateStoreId(selectedStore){$("#imsSuccessURL").val($("#afterStoreSelectionURL").val());
$("#imsSelectedStore").val(selectedStore);
}function getSelected(){var selected=$("div.cat-compare input[type=checkbox]:checked").size();
var selectionString="";
if(selected==0){alert("Please select the items to be compared");
}else{$.each($("div.cat-compare input[type=checkbox]:checked"),function(k,v){if(selectionString.length>0){selectionString=selectionString+",";
}selectionString=selectionString+$(v).attr("id");
});
}return selectionString;
}function redirectCompare(){var categoryName=$("input#categoryName").val();
var selectionString=""+generateProductIds();
if(selectionString.length>0){window.location.href=contextRoot+"/compare/"+selectionString+"/"+categoryName;
}}function generateProductIds(){var selected=$("div.cat-compare input[type=checkbox]:checked").size();
var selectionString="";
if(selected<2){alert(" Please select two or more items to compare.");
}else{$.each($("div.cat-compare input[type=checkbox]:checked"),function(k,v){if(selectionString.length>0){selectionString=selectionString+"/";
}selectionString=selectionString+$(v).attr("id");
});
}return selectionString;
}function enableCompare(event){var selected=$("div.cat-compare input[type=checkbox]:checked").size();
if(selected<2){$("input#prodComp").removeClass("cat-compare-on-btn");
$("input#prodComp").addClass("cat-compare-off-btn");
}else{$("input#prodComp").removeClass("cat-compare-off-btn");
$("input#prodComp").addClass("cat-compare-on-btn");
}if(selected>4){event.stopPropagation();
alert("You can select upto 4 products for comparison");
return false;
}return true;
}function loadMoreProductsGrid(loadMoreElem){var Ntt=$("#catNttVal").val();
if(Ntt!=""&&Ntt!=undefined){Ntt=Ntt.replace(/"/g,"&quot;");
}var currentShowing=$("li.gridproductview").length;
var start=currentShowing+1;
$("#spinner").show();
$.post(contextRoot+"/browse/includes/categorygridproductsajax.jsp",{NValue:$("#catNVal").val(),NsValue:$("#catNsVal").val(),NrValue:$("#catNrVal").val(),NttValue:Ntt,inputStoreValue:$("#inputEndecaStoreVal").val(),groupIdValue:$("#groupIdVal").val(),currentTab:$("#currentTab").val(),unKnownItemIdVal:$("#unKnownItemIdVal").val(),start:start},function(data){$("#spinner").hide();
$("#productListPlaceHolder").append(data);
$.scrollTo($("li.gridproductview")[start-1],800);
currentShowing=currentShowing+32;
renderLoadMoreButton(currentShowing,loadMoreElem);
categoryGridLiAutoHeight();
});
}function loadMoreProductsList(loadMoreElem){var Ntt=$("#catNttVal").val();
if(Ntt!=""&&Ntt!=undefined){Ntt=Ntt.replace(/"/g,"&quot;");
}var currentShowing=$("li.listproductview").length;
var start=currentShowing+1;
$("#spinner").show();
$.post(contextRoot+"/browse/includes/categorylistproductsajax.jsp",{NValue:$("#catNVal").val(),NsValue:$("#catNsVal").val(),NrValue:$("#catNrVal").val(),NttValue:Ntt,inputStoreValue:$("#inputEndecaStoreVal").val(),groupIdValue:$("#groupIdVal").val(),currentTab:$("#currentTab").val(),unKnownItemIdVal:$("#unKnownItemIdVal").val(),start:start},function(data){$("#spinner").hide();
$("#productListPlaceHolder").append(data);
$.scrollTo($("li.listproductview")[start-1],800);
currentShowing=currentShowing+32;
renderLoadMoreButton(currentShowing,loadMoreElem);
categoryGridLiAutoHeight();
});
}function renderLoadMoreButton(currentShowing){var totalRecord=$('[name|="prdTotalRecord"]').val();
if(totalRecord>currentShowing){$("#prdCategoryLoadMore").show();
$("#prdCategoryLoadMoreWrapper > div.pagenofn").html("Showing "+currentShowing+" of "+totalRecord);
}else{$("#prdCategoryLoadMore").hide();
if(totalRecord<=0){$("#prdCategoryLoadMoreWrapper > div.pagenofn").html("No Products Found");
}else{$("#prdCategoryLoadMoreWrapper > div.pagenofn").html("Showing "+totalRecord+" of "+totalRecord);
}}}function loadMoreSearchRecipesGrid(loadMoreElem){var Ntt=$("#catNttVal").val();
if(Ntt!=""&&Ntt!=undefined){Ntt=Ntt.replace(/"/g,"&quot;");
}var currentShowing=$("li.gridrecipesview").length;
var start=currentShowing+1;
$.ajax({async:"false",url:contextRoot+"/search/includes/gridrecipeviewajax.jsp",type:"POST",data:({NValue:$("#catNVal").val(),NsValue:$("#catNsVal").val(),NrValue:$("#catNrVal").val(),NttValue:Ntt,start:start,recipeSeoUrlValue:$("#recipeSeoUrlVal").val()}),beforeSend:function(){$("#spinner").show();
},success:function(data){$("#spinner").hide();
$("#recipesListPlaceHolder").append(data);
$.scrollTo($("li.gridrecipesview")[start-1],800);
currentShowing=currentShowing+32;
renderSearchRecipesLoadMoreBtn(currentShowing,loadMoreElem);
},complete:function(){categoryGridLiAutoHeight();
}});
}function loadMoreSearchRecipesList(loadMoreElem){var Ntt=$("#catNttVal").val();
if(Ntt!=""&&Ntt!=undefined){Ntt=Ntt.replace(/"/g,"&quot;");
}var currentShowing=$("li.listrecipesview").length;
var start=currentShowing+1;
$.ajax({async:"false",url:contextRoot+"/search/includes/listrecipeviewajax.jsp",type:"POST",data:({NValue:$("#catNVal").val(),NsValue:$("#catNsVal").val(),NrValue:$("#catNrVal").val(),NttValue:Ntt,start:start,recipeSeoUrlValue:$("#recipeSeoUrlVal").val()}),beforeSend:function(){$("#spinner").show();
},success:function(data){$("#spinner").hide();
$("#recipesListPlaceHolder").append(data);
$.scrollTo($("li.listrecipesview")[start-1],800);
currentShowing=currentShowing+32;
renderSearchRecipesLoadMoreBtn(currentShowing,loadMoreElem);
},complete:function(){categoryGridLiAutoHeight();
}});
}function renderSearchRecipesLoadMoreBtn(currentShowing){var totalRecord=$('[name|="recipeTotalRecord"]').val();
if(totalRecord>currentShowing){$("#recipesLoadMore").show();
$("#recipesLoadMoreWrapper > div.pagenofn").html("Showing "+currentShowing+" of "+totalRecord);
}else{$("#recipesLoadMore").hide();
if(totalRecord<=0){$("#recipesLoadMoreWrapper > div.pagenofn").html("No Products Found");
}else{$("#recipesLoadMoreWrapper > div.pagenofn").html("Showing "+totalRecord+" of "+totalRecord);
}}}function loadMoreArticlesList(loadMoreElem){var Ntt=$("#catNttVal").val();
if(Ntt!=""&&Ntt!=undefined){Ntt=Ntt.replace(/"/g,"&quot;");
}var currentShowing=$("li.listarticleview").length;
var start=currentShowing+1;
$("#spinner").show();
$.post(contextRoot+"/search/includes/contentviewajax.jsp",{NValue:$("#catNVal").val(),NttValue:Ntt,start:start},function(data){$("#spinner").hide();
$("#articleListPlaceHolder").append(data);
$.scrollTo($("li.listarticleview")[start-1],800);
currentShowing=currentShowing+32;
renderArticleLoadMoreButton(currentShowing,loadMoreElem);
});
}function renderArticleLoadMoreButton(currentShowing){var totalRecord=$('[name|="articleTotalRecord"]').val();
if(totalRecord>currentShowing){$("#articleLoadMore").show();
$("#articleLoadMoreWrapper > div.pagenofn").html("Showing "+currentShowing+" of "+totalRecord);
}else{$("#articleLoadMore").hide();
if(totalRecord<=0){$("#articleLoadMoreWrapper > div.pagenofn").html("No Products Found");
}else{$("#articleLoadMoreWrapper > div.pagenofn").html("Showing "+totalRecord+" of "+totalRecord);
}}}jQuery(document).ready(function(){enableCompare();
$("body").on("click","div.cat-compare input[type=checkbox]",function(event){return enableCompare(event);
});
$(".checkboxtest").each(function(){var value=$(this).parent().children("input.checkboxCheckedVal").val();
if(value=="true"){$(this).attr("checked",true);
}else{$(this).attr("checked",false);
}});
$("#prodSortBySelect").change(function(){location.href=$(this).val();
});
$("#prdCategoryLoadMore").on("click",function(){if($(".view-list-on").length>0){loadMoreProductsList();
}else{loadMoreProductsGrid();
}});
$("#recipesLoadMore").on("click",function(){if($(".view-list-on").length>0){loadMoreSearchRecipesList();
}else{loadMoreSearchRecipesGrid();
}});
$("#articleLoadMore").on("click",function(){loadMoreArticlesList();
});
});
