function loadTermsCondOverlay(){$("#OverlayDiv").load("overlay/indexTermsCondOverlay.html");
$("#OverlayDiv").modal({minWidth:790,minHeight:272});
}function loadGiftCardNumberPinOverlay(){$("#OverlayDiv").load("/docs/checkout/overlay/GiftCardPinOverlay.html");
$("#OverlayDiv").modal({minWidth:840,minHeight:588});
}function loadStoreOverlay(){$("#OverlayDiv").load("overlay/selectStoreOverlay.html");
$("#OverlayDiv").modal({minWidth:886,minHeight:624});
}function loadItemAvailableOverlay(){$("#OverlayDiv").load("overlay/itemAvailableOverlay.html");
$("#OverlayDiv").modal({minWidth:886,minHeight:624});
}function loadNutritionalTagsOverlay(){$("#OverlayDiv").load("overlay/pdpNutritionalTagsOverlay.html");
$("#OverlayDiv").modal({minWidth:734,minHeight:211,fixed:false,position:["15%",""]});
}function loadEmailToFriendOverlay(){$("#OverlayDiv").load("overlay/emailToFriendOverlay.html");
$("#OverlayDiv").modal({minWidth:735,minHeight:625});
}function loadIngredientsToShoppingListOverlay(){$("#OverlayDiv").load("overlay/addToListOverlay.html");
$("#OverlayDiv").modal({minWidth:704,minHeight:514});
}function loadLoyalityThankYouOverLay(){$("#OverlayDiv").load("overlay/thankyouoverlay.html");
$("#OverlayDiv").modal({minWidth:553,minHeight:194});
}function closeGeneralModal(){$("#OverlayDiv").empty();
$.modal.close();
}function loadPrintOverlay(){$("#OverlayDiv").load("overlay/printOverlay.html");
$("#OverlayDiv").modal({minWidth:517,minHeight:330});
}function loadMobileValidation(){$("#OverlayDiv").load("overlay/mobileNumberOverlay.html");
$("#OverlayDiv").modal({minWidth:783,minHeight:388});
}function loadMobileConfirmation(){$("#OverlayDiv").load("overlay/mobileNumberConfirmationOverlay.html");
$("#OverlayDiv").modal({minWidth:550,minHeight:215});
}function loadDeleteAddress(){$("#OverlayDiv").load("overlay/deleteAddressOverlay.html");
$("#OverlayDiv").modal({minWidth:500,minHeight:195});
}function loadCouponPopupOverlay(){$("#OverlayDiv").load("overlay/couponsPopUp.html");
$("#OverlayDiv").modal({minWidth:585,minHeight:380});
}function loadErrorOverlay(){$("#OverlayDiv").load("overlay/errorOverlay.html");
$("#OverlayDiv").modal({minWidth:475,minHeight:235});
}function loadCancelOverlay(){$("#OverlayDiv").load("overlay/cancelOverlay.html");
$("#OverlayDiv").modal({minWidth:500,minHeight:195});
}function loadMobileSuccess(){$("#OverlayDiv").load("overlay/mobileNumberSuccessOverlay.html");
$("#OverlayDiv").modal({minWidth:748,minHeight:337});
}function vppSuccessOverlay(){$("#OverlayDiv").load("overlay/vppSuccessOverlay.html");
$("#OverlayDiv").modal({minWidth:513,minHeight:253});
}function loadCancelOrderOverlay(){$("#OverlayDiv").load("overlay/cancelOrderOverlay.html");
$("#OverlayDiv").modal({minWidth:500,minHeight:245});
}function transactionDetailsOverlay(){$("#OverlayDiv").load("overlay/transactionoverlay.html");
$("#OverlayDiv").modal({minWidth:736,minHeight:660,fixed:false});
}function giftCardPinOverlay(){$("#OverlayDiv").load("/docs/checkout/overlay/GiftCardPinOverlay.html");
$("#OverlayDiv").modal({minWidth:709,minHeight:540});
}function cvcOverlay(){$("#OverlayDiv").load("/docs/checkout/overlay/CVCOverlay.html");
$("#OverlayDiv").modal({minWidth:689,minHeight:466});
}function drugInformationOverlay(){$("#OverlayDiv").load("overlay/drugInformationOverlay.html");
$("#OverlayDiv").modal({minWidth:633,minHeight:391});
}function moveRecipe(){$("#OverlayDiv").load("overlay/moveRecipeOverlay.html");
$("#OverlayDiv").modal({minWidth:580,minHeight:310});
}