$(document).ready(function(){$(".quickrecipe-container").hide();
$(".quickrecipe-filter .advsearch").attr("href","javascript:showHideAdvSearch();");
$(".maintxt").each(function(index,item){var charWidth=46;
if($(".inline-table.item").size()>0){charWidth=70;
}var obj=$(item).find("span");
if(obj.length){var placename=$(obj).text();
if($.browser.msie||navigator.userAgent.match(/Trident\/7\./)){if($(obj).width()>charWidth){placename=placename.substring(0,charWidth);
$(obj).text(placename+"...");
}}else{if($(obj).width()>$(item).width()&&placename.trim().length>46){var limit=0;
do{limit++;
placename=placename.substring(0,placename.length-1);
$(obj).text(placename+"...");
}while($(obj).width()>$(item).width()&&limit<2000);
}else{if(placename.trim().length>charWidth){var lineWidth=charWidth/2;
var line1="";
var line2="";
var words=placename.split(" ");
for(i=0;
i<words.length;
i++){if((line1+" "+words[i]).length<lineWidth&&(line2=="")){line1=line1.trim()+" "+words[i];
}else{if((line2+" "+words[i]+"...").length<lineWidth&&(line1!="")){line2=line2.trim()+" "+words[i];
}else{break;
}}}$(obj).text(line1+" "+line2+"...");
}}}var objParent=$(obj).parent();
$(objParent).html($(obj).html());
}});
$("body").on("click","a#deleteRecipe",function(){var value=$(this).attr("name");
if(value!=null&&value!="undefined"){$("input#deleteRecipeId").val(value);
submitNameForm("deleteRecipeFromFolder");
}});
$("body").on("blur","div#createUserFolderText input:text, div#rename input.recipeboxinput",function(){if($(this).val()==""&&$(this).data("ghost-text")!=undefined&&$(this).data("ghost-text")!=""){$(this).val($(this).data("ghost-text"));
$(this).addClass("ghost-text");
}});
$("body").on("focus","div#createUserFolderText input:text",function(){if($(this).hasClass("ghost-text")){$(this).attr("value","");
$(this).removeClass("ghost-text");
}});
$("body").on("focus","div#rename input.recipeboxinput",function(){$(this).removeClass("ghost-text");
$(this).removeAttr("style");
});
$(".pdp-carousel-customize-btn, .cat-add-to-cart-btn").on("click",function(e){var quantityTxt=$(this).parent().children(".cat-input-qty");
var quantity=quantityTxt.val();
if(quantity==""||quantity==0){quantityTxt.addClass("input-error");
e.preventDefault();
return false;
}else{quantityTxt.removeClass("input-error");
return true;
}});
if(($(".relatedarticles").length>10)||($(".contentwrapper .articles").length>10)){categoryGridLiAutoHeight();
var divSize=$(".relatedarticles").length;
var nthDiv=0;
if(divSize==0){divSize=$(".contentwrapper .articles").length;
divSize=divSize-8;
nthDiv=$(".articles:eq("+divSize+")");
}else{divSize=divSize-8;
nthDiv=$(".relatedarticles:eq("+divSize+")");
}$(window).scrollTop(nthDiv.offset().top).scrollLeft(nthDiv.offset().left);
var loadBtn=$(".showing").offset();
}else{if($("div.related-more-videos").length>12){var divSize=$("div.related-more-videos").length;
divSize=divSize-12;
var nthDiv=$("div.related-more-videos:eq("+divSize+")");
$(window).scrollTop(nthDiv.offset().top).scrollLeft(nthDiv.offset().left);
var loadBtn=$("div.showing").offset();
}else{}}if($("div.cookingconnectionvideowrapper div.cookingrecipe").length>6){var divSize=$("div.cookingrecipe").length;
divSize=divSize-5;
var nthDiv=$("div.cookingrecipe:eq("+divSize+")");
$(window).scrollTop(nthDiv.offset().top).scrollLeft(nthDiv.offset().left);
}else{}$("body").on("click","#createAccountBtn",function(){var url=$("input#createAccountUrl").val();
window.location.href=contextRoot+url;
return false;
});
$("iframe").each(function(){var ifr_source=$(this).attr("src");
var wmode="wmode=transparent";
if(ifr_source.indexOf("?")!=-1){$(this).attr("src",ifr_source+"&"+wmode);
}else{$(this).attr("src",ifr_source+"?"+wmode);
}});
});
function removeEditLink(){$("#editLink").removeClass("inline-block bluelinks").addClass(function(){return"dontShow";
});
$("#rename").removeClass("dontShow").addClass(function(){return"showRename";
});
}function submitForm(form,select){if(select!=null){if($(select).val()=="select"){return;
}}form.submit();
}function loadBoxItems(selectValue,folderRepId){if(selectValue==null){return;
}$.ajax({async:"false",url:contextRoot+"/recipe/includes/recipeboxitemsfrag.jsp",dataType:"html",type:"POST",data:"sortParam="+$(selectValue).val()+"&folderId="+folderRepId+"&folderRepId="+true,success:function(data){$("#recipeContainer").html(data);
},complete:function(){recipeBoxAutoHeight();
}});
}function loadIngredientsShoppingListOverlay(recipeId,divName){var url=contextRoot+"/recipe/includes/recipeOverlay/recipeaddtolistoverlay.jsp";
var div=divName;
loadRequestedPage(url,div,recipeId,true,744,261,true);
}function loadRecipeNutritionalTagsOverlay(recipeId){var url=contextRoot+"/recipe/includes/recipeOverlay/nutritionaltagsoverlay.jsp";
var divId="#nutritionTagsOverlay";
$.ajax({url:url,dataType:"html",type:"POST",data:"recipeId="+recipeId,success:function(data){$(divId).html(data);
}});
$(divId).modal({minWidth:734,minHeight:211,fixed:false,position:[75]});
}function loadRequestedPage(url,div,recipeId,openOverLay,width,height,isPosition){var divId="#"+div;
$.ajax({url:url,dataType:"html",type:"POST",data:"recipeId="+recipeId,success:function(data){$(divId).html(data);
}});
if(openOverLay){if(isPosition){$(divId).modal({minWidth:width,minHeight:height,position:["20%",""]});
}else{$(divId).modal({minWidth:width,minHeight:height});
}}}function checkAll(className,checkAllId,unCheckAllId,dummyBtnId,originalBtnId){var name="."+className;
var checkAll="#"+checkAllId;
var unCheck="#"+unCheckAllId;
var dummyBtn="#"+dummyBtnId;
var originalBtn="#"+originalBtnId;
$(name).find(":checkbox").each(function(){$(this).attr("checked",true);
$(this).addClass("checked");
});
$(checkAll).removeClass("inline-block").addClass(function(){return"dontShow";
});
$(unCheck).removeClass("dontShow").addClass(function(){return"inline-block";
});
$(dummyBtn).removeClass("inline-block").addClass(function(){return"dontShow";
});
$(originalBtn).removeClass("dontShow").addClass(function(){return"inline-block";
});
}function unCheckAll(className,checkAllId,unCheckAllId,dummyBtnId,originalBtnId){var name="."+className;
$(name).find(":checkbox").each(function(){$(this).attr("checked",false);
$(this).removeClass("checked");
});
$("#"+checkAllId).removeClass("dontShow").addClass(function(){return"inline-block";
});
$("#"+unCheckAllId).removeClass("inline-block").addClass(function(){return"dontShow";
});
$("#"+dummyBtnId).removeClass("dontShow").addClass(function(){return"inline-block";
});
$("#"+originalBtnId).removeClass("inline-block").addClass(function(){return"dontShow";
});
}function showAddToListBtn(className,checkAllId,unCheckAllId,dummyBtnId,originalBtnId){var name="."+className;
var checkedItems;
if(className=="ingredientswrapper"){checkedItems=$(name).find(":checkbox").filter(":checked").length;
}else{checkedItems=$(name).find(":checkbox").filter(".checked").length;
}var length=$(name).find(":checkbox").length;
if(checkedItems>0){$("#"+dummyBtnId).removeClass("inline-block").addClass(function(){return"dontShow";
});
$("#"+originalBtnId).removeClass("dontShow").addClass(function(){return"inline-block";
});
}else{if(checkedItems==0){$("#"+dummyBtnId).removeClass("dontShow").addClass(function(){return"inline-block";
});
$("#"+originalBtnId).removeClass("inline-block").addClass(function(){return"dontShow";
});
$("#"+checkAllId).removeClass("dontShow").addClass(function(){return"inline-block";
});
$("#"+unCheckAllId).removeClass("inline-block").addClass(function(){return"dontShow";
});
}}if(checkedItems==length){$("#"+checkAllId).removeClass("inline-block").addClass(function(){return"dontShow";
});
$("#"+unCheckAllId).removeClass("dontShow").addClass(function(){return"inline-block";
});
}else{if(checkedItems!=0&&checkedItems<length){$("#"+checkAllId).removeClass("dontShow").addClass(function(){return"inline-block";
});
$("#"+unCheckAllId).removeClass("inline-block").addClass(function(){return"dontShow";
});
}}}function showMore(key){var featureKey=key;
$("#moreOptions_"+featureKey).removeClass("dontShow").addClass(function(){return"show";
});
$("#moreOptionsLink_"+featureKey).removeClass("show").addClass(function(){return"dontShow";
});
}function showLess(key){var featureKey=key;
$("#moreOptions_"+featureKey).removeClass("show").addClass(function(){return"dontShow";
});
$("#moreOptionsLink_"+featureKey).removeClass("dontShow").addClass(function(){return"show";
});
}function changeCancelStyle(){if(($("input#newUserFolder").val()!="Name your folder here")&&($("input#newUserFolder").val().length>=0)){$("input#recipeBoxCanlcelButton").css("background-color","#EE2E24");
$("input#newUserFolder").css("color","#414142");
}}function showHideCreateFolderTextBox(){if($("#createUserFolderLink").is(":hidden")==false){$("#createUserFolderLink").hide();
if($("input#newUserFolder").val()!="Name your folder here"){$("input#newUserFolder").val("");
$("input#newUserFolder").blur();
}$("#createUserFolderText").show();
}else{$("#createUserFolderLink").show();
$("#createUserFolderText").hide();
$("input#recipeBoxCanlcelButton").css("background-color","#E0E0E0");
}}function loadRecipeItems(folderId){$("#recipeBoxItems").load(contextRoot+"/recipe/includes/recipeboxitems.jsp",{"folderIdValue":folderId,selectyze:true});
}function submitNameForm(form){$("form#"+form).submit();
}function submitForm(form){form.submit();
}function addToBox(recipeId,linkDiv,msgDiv){if(recipeId==null){return;
}var url=contextRoot+"/recipe/addtorecipebox.jsp?recipeId="+recipeId;
$.ajax({url:url,type:"POST",dataType:"json",success:function(response){var status=response.success;
if(status=="true"){$("#"+linkDiv).addClass("dontShow");
$("#"+msgDiv).html("<span>Added to Recipe Box</span>");
$("#myRecipeBoxDiv").load("includes/myrecipebox.jsp");
$("#recentlyViewed").load("includes/recentlyviewedrecipes.jsp",{"viewType":"vertical"});
}}});
}function deleteRecipeFolder(folderId){if(folderId==null){return;
}var confirmFlag=confirm("Please confirm to Delete the Folder");
if(confirmFlag==true){var url=contextRoot+"/recipe/deleterecipefolder.jsp?deleteFolderId="+folderId;
$.ajax({url:url,type:"POST",dataType:"json",success:function(response){var status=response.success;
if(status=="true"){alert("Folder Deleted");
}if(status=="false"){alert("Folder Not Deleted");
}var pageUrl=$("input#recipeBoxSeoUrl").val();
window.location=pageUrl;
}});
}}function moveRecipeToFolder(fromFolderId,toFolderId,recipeId,toFolderName){if(fromFolderId!=null&&toFolderId!=null&&recipeId!=null){var url=contextRoot+"/recipe/moverecipetofolder.jsp?fromFolderId="+fromFolderId+"&toFolderId="+toFolderId+"&recipeId="+recipeId;
$.ajax({url:url,type:"POST",dataType:"json",success:function(response){var status=response.success;
if(status=="true"){}if(status=="false"){alert("Recipe Not Moved");
}}});
recipeMovedOverlay(toFolderName);
}else{return;
}}function recipeMovedOverlay(toFolderName){var url=contextRoot+"/recipe/includes/recipeOverlay/moveRecipeOverlay.jsp?toFolderName="+toFolderName;
var divId="#OverlayDiv";
$.ajax({url:url,dataType:"html",type:"POST",success:function(data){$(divId).html(data);
}});
$(divId).modal({minWidth:580,minHeight:310,fixed:false,position:[75]});
}function closeRecipeBoxModal(){$("#modalWindow").empty();
$.modal.close();
var pageUrl=$("input#folderSeoUrl").val();
window.location=pageUrl;
}function addToRecipeBox(folderId,recipeId,form){if(folderId!=null&&form!=null){$(".addToRecipeBoxId_"+recipeId).val(folderId);
submitNameForm(form);
}}$(document).ready(function(){$(".checkbox").click(function(){if($(this).hasClass("selected")){$(this).removeClass("selected");
$(this).attr("src","img/checkoff.png");
}else{$(this).addClass("selected");
$(this).attr("src","img/checkon.png");
}});
});
$(document).ready(function(){$(".scrolltop a").click(function(){$("html,body").animate({scrollTop:$("#wrapper").offset().top},"fast");
return false;
});
});
$(document).ready(function(){$("div.recipelowerlinks").children().each(function(index,elem){categoryGridLiAutoHeight();
$(this).on("click",function(){$("div.recipelowerlinks").children(".redbutton").removeClass("redbutton").addClass("lightorangebutton");
$(this).removeClass("lightorangebutton").addClass("redbutton");
var left=$(this).offset().left;
var width=$(this).width();
var currId=$(this).attr("id");
$('ul[id|="tab"]').hide();
$("#tab-"+(index+1)).show();
categoryGridLiAutoHeight();
var currentSectionId=$(this).attr("id");
var arr=currentSectionId.split("-");
var count=arr[1];
var total=$("#total_"+count).val();
if(total!=undefined){var currentShowing=$("#tab-"+count).children("li").length;
if(currentShowing>12){}if(currentShowing>=total){currentShowing=total;
$("div.loadmorewrapper").find("div.loadmore").hide();
}else{$("div.loadmorewrapper").find("div.loadmore").show();
}$("div.loadmorewrapper").children("div.showing").html("Showing "+(currentShowing)+" of "+total);
}else{$("div.loadmorewrapper").find("div.loadmore").hide();
$("div.loadmorewrapper").children("div.showing").html("No recipes found");
}});
});
$("#promoRecipesLoadMore").on("click",function(){var currentSection=$("div.recipelowerlinks").children(".redbutton");
var currentSectionId=currentSection.attr("id");
var arr=currentSectionId.split("-");
var count=arr[1];
var total=$("#total_"+count).val();
var section=$("#sectionId_"+count).val();
var currentShowing=$("#tab-"+count).children("li").length;
var pageType=$("input#source").val();
var start=currentShowing+1;
$.get(contextRoot+"/recipe/includes/promorecipeslist.jsp?start="+start+"&howMany=4&section="+section+"&source="+pageType,function(data){$("#tab-"+count).append(data);
$.scrollTo($("#tab-"+count+" > li:nth-child("+start+")"),800);
currentShowing=currentShowing+12;
if(currentShowing>=total){currentShowing=total;
$("div.loadmorewrapper").find("div.loadmore").hide();
}$("div.loadmorewrapper").children("div.showing").html("Showing "+(currentShowing)+" of "+total);
var loadBtn=$(".showing").offset();
categoryGridLiAutoHeight();
});
});
});
$(document).ready(function(){$("#quickRecipeSearch").on("click",function(){invokeQuickRecipeSearch();
});
$("#advSearchButton").on("click",function(){invokeQuickRecipeSearch();
});
function invokeQuickRecipeSearch(){var dimNameOne=$("#dimNameOne").val();
var dimNameTwo=$("#dimNameTwo").val();
var optionOne=$("#optionOne").val();
var optionTwo=$("#optionTwo").val();
var andFilter="";
var orFilter="";
var filters="";
var andFilterString="";
var orFilterString="";
var filterString="";
if("Select"!=optionOne&&"Select"!=optionTwo){andFilter="&Nr=AND("+dimNameOne+":"+optionOne.replace(",","\\,")+","+dimNameTwo+":"+optionTwo.replace(",","\\,");
andFilterString='for "'+optionOne+'" and "'+optionTwo+'"';
}else{if("Select"!=optionOne&&"Select"==optionTwo){andFilter="&Nr=AND("+dimNameOne+":"+optionOne.replace(",","\\,");
andFilterString='for "'+optionOne+'"';
}else{if("Select"==optionOne&&"Select"!=optionTwo){andFilter="&Nr=AND("+dimNameTwo+":"+optionTwo.replace(",","\\,");
andFilterString='for "'+optionTwo+'"';
}}}$("div.quickrecipe-container :checkbox").each(function(index){if($(this).is(":checked")&&$(this).hasClass("checked")){if(filters!=""){filters=filters+",";
orFilterString=orFilterString+", ";
}filters=filters+$(this).attr("name")+":"+($(this).val()).replace(",",",");
orFilterString=orFilterString+'"'+$(this).val()+'"';
}else{$(this).attr("checked",false);
}});
if(filters!=""){if(andFilter!=""){orFilter=",OR("+filters+"))";
}else{orFilter="&Nr=OR("+filters+")";
}}else{if(andFilter!=""){andFilter=andFilter+")";
}else{andFilter="&clearterm=true";
}}if(orFilterString!=""){if(andFilterString!=""){filterString=andFilterString+" with "+orFilterString;
}else{filterString="with "+orFilterString;
}}else{if(andFilterString!=""){filterString=andFilterString;
}}var action=$("#advSearchForm").attr("action");
action=action+"&Ntk=RECIPESEARCH"+andFilter+orFilter;
$("#advSearchForm").attr("action",action);
$("input#quickrecipeterm").val(filterString);
$("#advSearchForm").submit();
}});
$(document).ready(function(){$('[class*="recipeview-list"]').on("click",function(){if($(this).attr("class")=="recipeview-list-off"){refreshRecipes(contextRoot+"/recipe/includes/recipelist.jsp");
$(".recipeview-grid-on").attr("class","recipeview-grid-off");
$(this).attr("class","recipeview-list-on");
}});
$('[class*="recipeview-grid"]').on("click",function(){if($(this).attr("class")=="recipeview-grid-off"){refreshRecipes(contextRoot+"/recipe/includes/recipegrid.jsp");
$(".recipeview-list-on").attr("class","recipeview-list-off");
$(this).attr("class","recipeview-grid-on");
}});
$("div.recipeoptionblock .recipecheckoption :checkbox").on("click",function(){refreshRecipes(getRecipesPageURL());
});
$("#sortBySelect").on("change",function(){refreshRecipes(getRecipesPageURL());
});
$("#recipeCategoryLoadMore").on("click",function(){if($(".recipeview-list-on").length>0){loadMoreRecipesList();
}else{loadMoreRecipesGrid();
}});
});
function getRecipesPageURL(){var page=contextRoot+"/recipe/includes/recipelist.jsp";
if($(".recipeview-grid-on").length>0){page=contextRoot+"/recipe/includes/recipegrid.jsp";
}return page;
}function refreshRecipes(page){var paramString=getParameterString();
$.post(page+"?"+paramString,function(data){$("#recipeListPlaceHolder").html(data);
showHideLoadMoreButton(16);
categoryGridLiAutoHeight();
});
}function getParameterString(){var params="";
var navId=$("#navId").val();
var catId=$("#catId").val();
var sortBy=$("#sortBySelect").val();
var pageName=$("#pageName").val();
var filterString="";
var filters="";
$("div.recipeoptionblock .recipecheckoption :checkbox").each(function(index){if($(this).is(":checked")){if(filters!=""){filters=filters+",";
}filters=filters+"recipe.filters"+":"+$(this).val();
}});
if(filters!=""){filterString="&Nr=OR"+filterString+"("+filters+")";
}params="N="+navId+"&catId="+catId+"&Ns="+sortBy+"&pgName="+pageName+filterString;
return params;
}function showHideLoadMoreButton(currentShowing){var totalRecord=$('[name|="totalRecord"]').val();
if(totalRecord>currentShowing){$("#recipeCategoryLoadMore").show();
$("#recipeCategoryLoadMoreWrapper > div.showing").html("Showing "+currentShowing+" of "+totalRecord);
}else{$("#recipeCategoryLoadMore").hide();
if(totalRecord<=0){$("#recipeCategoryLoadMoreWrapper > div.showing").html("No Recipes Found");
}else{$("#recipeCategoryLoadMoreWrapper > div.showing").html("Showing "+totalRecord+" of "+totalRecord);
}}$("div.result-search > span").html(totalRecord);
}function loadMoreRecipesList(loadMoreElem){var currentShowing=$("div.recipemakeit").length;
var start=currentShowing+1;
var paramString=getParameterString();
paramString=paramString+"&start="+start+"&howMany=16";
$.post(contextRoot+"/recipe/includes/recipelist.jsp?"+paramString,function(data){$("#recipeListPlaceHolder").append(data);
$.scrollTo($("div.recipemakeit")[start-1],800);
currentShowing=currentShowing+16;
showHideLoadMoreButton(currentShowing,loadMoreElem);
});
var loadBtn=$("#recipeCategoryLoadMoreWrapper .showing").offset();
}function loadMoreRecipesGrid(loadMoreElem){var currentShowing=$("li.listrecipeimage").length;
var start=currentShowing+1;
var paramString=getParameterString();
paramString=paramString+"&start="+start+"&howMany=16";
$.post(contextRoot+"/recipe/includes/recipegrid.jsp?"+paramString,function(data){$("#recipeListPlaceHolder").append(data);
$.scrollTo($("li.listrecipeimage")[start-1],800);
currentShowing=currentShowing+16;
showHideLoadMoreButton(currentShowing,loadMoreElem);
categoryGridLiAutoHeight();
});
var loadBtn=$("#recipeCategoryLoadMoreWrapper .showing").offset();
}function checkedOverlayInput(checkBxId){if($("input[id="+checkBxId+"]").is(":checked")){$("input[id="+checkBxId+"]").attr("checked",true);
$("input[id="+checkBxId+"]").addClass("checked");
}else{$("input[id="+checkBxId+"]").attr("checked",false);
$("input[id="+checkBxId+"]").removeClass("checked");
}}function checkedOverlayInputNew(checkBxId){checkedOverlayInput(checkBxId);
showAddToListBtn("addtolist","checkall_2","uncheckall_2","dummyAddToListBtn_2","addToListBtn_2");
}function checkedGeneralInput(){jQuery(".cutomize-checkbox input").click(function(){var classCheckbox=jQuery(this).attr("class");
if(typeof classCheckbox==="undefined"||classCheckbox===""){jQuery(this).addClass("checked");
jQuery(this).attr("checked","checked");
}else{jQuery(this).removeClass("checked");
jQuery(this).removeAttr("checked");
}});
}function showHideAdvSearch(){$(".quickrecipe-container").toggle();
}function triggerDropDownClick(){$(".icon").trigger("click");
}function displayMoreOptionDD(id){var name=$(id).attr("name");
$(".recipewrapper").each(function(){if($("div.atl-container").is(":visible")){jQuery(".atl-container ").show();
jQuery(".atl-recipe-container").show();
jQuery(id).parent().children("div.atl-container").hide();
}});
jQuery(".atl-container").hide();
jQuery(".atl-recipe-container").hide();
jQuery(id).parent().children("div."+name).show();
$("body").mouseover(function(e){var target=$(e.target);
if(!target.parents().is("a[name='"+name+"']")&&!target.is("a[name='"+name+"']")&&!target.is("div."+name)){jQuery(id).parent().children("div."+name).fadeOut();
}});
jQuery(id).parent().children("div."+name).mouseover(function(e){e.stopPropagation();
});
}function setSelectedList(contextRoot,isWarmUser){if(isWarmUser){location.href=contextRoot+"/my-account/login?source=mylist&action=browseRedirect";
}}