$(document).ready(function(){$("#screenNameUpdate").click(function(){var screenName=$("#screenName").val();
if(validateScreenName(screenName)){$.ajax({url:contextRoot+"/pdp/includes/reviews/updateScreenName.jsp",type:"POST",dataType:"json",data:{"screenName":screenName},success:function(response){var error=response.error;
var errorMsg=response.errorMsg;
if(error==undefined){$("#nickName").html(screenName);
$("screenName").val(screenName);
$("#editScreenName").addClass("hidden");
$("#displayScreenName").removeClass("hidden");
$("#screenName").val($("#screenName").attr("title"));
$("#reviewErrorMessage").addClass("hidden");
validateToEnableSubmitReviewButton();
}else{$("#screenName").addClass("input-error");
$("#reviewErrorMessage").html(errorMsg);
$("#reviewErrorMessage").removeClass("hidden");
}}});
}return false;
});
$("input#reviewTitle").blur(function(){validateEmptyAndSetGhostText("input#reviewTitle",$("input#reviewTitle").attr("title"),"ghost");
if(!$(this).hasClass("ghost")){if($(this).val()==$(this).attr("title")){$(this).addClass("ghost");
}}});
$("textarea#reviewComment").blur(function(){validateEmptyAndSetGhostText("#reviewComment",$("#reviewComment").attr("title"),"ghost");
if(!$(this).hasClass("ghost")){if($(this).val()==$(this).attr("title")){$(this).addClass("ghost");
}}});
$("input#reviewTitle").keyup(function(){validateToEnableSubmitReviewButton();
});
$("textarea#reviewComment").keyup(function(){validateToEnableSubmitReviewButton();
});
$("input#reviewTitle").focus(function(){removeGhostTextFromInputField("input#reviewTitle",$("input#reviewTitle").attr("title"),$("input#reviewTitle").attr("value"),"ghost");
});
$("textarea#reviewComment").focus(function(){removeGhostTextFromInputField("#reviewComment",$("#reviewComment").attr("title"),$("#reviewComment").attr("value"),"ghost");
validateToEnableSubmitReviewButton();
});
$("#screenName").focus(function(){removeGhostTextFromInputField("input#screenName",$("input#screenName").attr("title"),$("input#screenName").attr("value"),"ghost");
});
$("#screenName").blur(function(){validateEmptyAndSetGhostText("input#screenName",$("input#screenName").attr("title"),"ghost");
});
$("#screenNameEdit").click(function(){$("#editScreenName").removeClass("hidden");
$("#displayScreenName").addClass("hidden");
validateToEnableSubmitReviewButton();
});
$(".write-a-review").click(function(){window.location=$("#write-a-review-login-url").val();
});
function validateScreenName(screenName){$("#screenName").removeClass("input-error");
if(screenName==$("#screenName").attr("title")||screenName==""){$("#screenName").addClass("input-error");
return false;
}return true;
}$("#reviewSubmit").click(function(){if($(this).hasClass("inactive")){return false;
}var rating=$("#rating").val();
if(rating==0){$("div.ratingStarText").addClass("error");
return false;
}var productId=$("#bvProductId").val();
var reviewTitle=$("#reviewTitle").val();
var reviewComment=$("#reviewComment").val();
$.ajax({url:contextRoot+"/pdp/includes/reviews/submitreviewtobv.jsp",type:"POST",dataType:"json",data:"productId="+productId+"&title="+reviewTitle+"&reviewtext="+reviewComment+"&rating="+rating,success:function(response){var success=response.success;
var submissionId=response.submissionId;
var errorCode=response.errorCode;
var inputError=response.inputError;
if(success&&submissionId!=""){$(".reviews-product").load(contextRoot+"/pdp/includes/reviews/thankYouReview.jsp");
$("div#bvReviewErrorDiv").removeClass("show").addClass("dontShow");
}else{if(!success&&submissionId=="null"&&errorCode=="ERROR_DUPLICATE_SUBMISSION"){$("div#bvReviewErrorDiv").removeClass("dontShow").addClass("show");
$("span#bvReviewErrorSpan").html($("input#duplicateReviewMsg").val());
}else{$("div#bvReviewErrorDiv").removeClass("dontShow").addClass("show");
$("span#bvReviewErrorSpan").html($("input#bvErrorMsg").val());
}}window.location.hash="#reviews-container";
}});
return false;
});
$('[id*="ratingStar"]').on("click",function(event){clearAll();
var rating=$(this).attr("title");
$("#rating").val(rating);
var i=0;
var count=rating;
$(".review-start").children("li").each(function(){if(i<count){$(this).children().addClass("reviewsSelected");
i=i+1;
}});
validateToEnableSubmitReviewButton();
return false;
});
});
function clearAll(){$(".review-start").children("li").each(function(){$(this).children().removeClass("reviewsSelected");
});
}function validateToEnableSubmitReviewButton(){$("#reviewSubmit").removeClass("ovallon");
validateAndAddClass("inactive");
if(!validateIfReviewRatingSelected()){return false;
}if(!validateReviewText("reviewTitle")){return false;
}if(!validateReviewText("reviewComment")){return false;
}if(!validateNickNameSaved()){return false;
}$("#reviewSubmit").removeClass("inactive");
validateAndAddClass("ovallon");
return true;
}function validateAndAddClass(className){if(!$("#reviewSubmit").hasClass(className)){$("#reviewSubmit").addClass(className);
}}function validateIfReviewRatingSelected(){var reviewRatingSelected=false;
$(".review-start").children("li").children("a").each(function(){var a=$(this).attr("class");
if($(this).hasClass("reviewsSelected")){reviewRatingSelected=true;
}});
return reviewRatingSelected;
}function validateReviewText(id){var reviewTitle=$("#"+id).val().trim();
var reviewTitleTxt=$("#"+id).attr("title");
if(reviewTitle==""||reviewTitle==reviewTitleTxt||reviewTitle.length<3){return false;
}return true;
}function validateNickNameSaved(){return $("#editScreenName").hasClass("hidden");
}