function createTwitterLink(originalUrl,productDescription){var twitterURL=$("input#twitterURL").val();
var twitterMsg=$("input#twitterMsg").val();
var hashMsg=$("input#twitterHashTag").val();
var twitterVia=$("input#twitterVia").val();
if(twitterURL!="undefined"&&twitterURL!=""&&twitterMsg!="undefined"&&hashMsg!="undefined"){var tempUrl=twitterURL+encodeURI("original_referer="+originalUrl+"&text="+twitterMsg+" @"+twitterVia+" &tw_p=tweetbutton&url="+originalUrl+"&hashtags="+hashMsg);
popup(tempUrl,"twitter",655,300,true);
}}function createArticleTwitterLink(originalUrl,productDescription){var twitterURL=$("input#twitterURL").val();
var twitterMsg=$("input#twitterMsg").val();
var hashMsg=$("input#twitterHashTag").val();
var twitterVia=$("input#twitterVia").val();
if(twitterURL!="undefined"&&twitterURL!=""&&twitterMsg!="undefined"&&hashMsg!="undefined"){var encodedURI=encodeURI("original_referer="+originalUrl+"&tw_p=tweetbutton&url="+originalUrl+"&text=");
var encodedDescription=encodeURI(productDescription+", by @"+twitterVia);
encodedDescription=encodedDescription.replace("&","%26");
var twitterURLString=encodedURI+encodedDescription;
var tempUrl=twitterURL+twitterURLString;
popup(tempUrl,"twitter",655,300,true);
}}function createPinterestLink(urlProduct,imageUrl,productDescription){var pinterestURL=$("input#pinterestURL").val();
var pinterestVia=$("input#pinterestVia").val();
if(pinterestURL!="undefined"&&pinterestURL!=""&&pinterestVia!="undefined"){var encodedURI=encodeURI("url="+urlProduct+"&media="+imageUrl+"&maskuse=off&wid=1119&size=1121,1254&fit=crop&qlt=70,0&description=");
var encodedDescription=encodeURI(productDescription+" by @"+pinterestVia);
encodedDescription=encodedDescription.replace("&","%26");
var pinterestURLString=encodedURI+encodedDescription;
var tempUrl=pinterestURL+pinterestURLString;
popup(tempUrl,"pinterest",655,300,true);
}}$(document).ready(function(){window.fbAsyncInit=function(){FB.init({appId:"285140601635770",status:true,xfbml:true});
};
(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];
if(d.getElementById(id)){return;
}js=d.createElement(s);
js.id=id;
js.src="//connect.facebook.net/en_US/all.js";
fjs.parentNode.insertBefore(js,fjs);
}(document,"script","facebook-jssdk"));
});
