var listOverlayStore=false;
var loadMoreStore=false;
var loadStores=false;
function loadAvailableStore(zipcode,openlightbox){var url=contextRoot+"/pdp/includes/stores/availableStores.jsp";
var div="AvailableDivOverlay";
var skuId=getSelectedSkuId();
var productId=$("#productId").val();
loadStore(url,div,zipcode,skuId,openlightbox,productId);
}function loadWeeklyAddsStores(zipcode,openlightbox){var url=contextRoot+"/weekly-ads/adstoreoverlay.jsp";
var div="storeOverlay";
var skuId="";
loadStore(url,div,zipcode,skuId,openlightbox);
}function loadDealProductsStores(zipcode,openlightbox){var url=contextRoot+"/mylist/includes/storeOverlay/dealstoreoverlay.jsp";
var div="storeOverlay";
var skuId="";
loadStore(url,div,zipcode,skuId,openlightbox);
}function loadShopListStores(zipcode,openlightbox){var url=contextRoot+"/mylist/includes/storeOverlay/shopliststoreoverlay.jsp";
var div="storeOverlay";
var skuId="";
loadStore(url,div,zipcode,skuId,openlightbox);
}function loadCategoryStores(zipcode,openlightbox){var url=contextRoot+"/includes/categorystoreoverlay.jsp";
var div="catStoreOverlay";
var skuId="";
loadStore(url,div,zipcode,skuId,openlightbox);
}function loadPickupStore(zipcode,openlightbox){var url=contextRoot+"/pdp/includes/stores/pickupStores.jsp";
var div="PickupDivOverlay";
var skuId=getSelectedSkuId();
var productId=$("#productId").val();
loadStore(url,div,zipcode,skuId,openlightbox,productId,"addToCart");
}function loadChangeSelectedStore(zipcode,openlightbox){var url=contextRoot+"/pdp/includes/stores/changestores.jsp";
var div="PickupDivOverlay";
var skuId=getSelectedSkuId();
loadStore(url,div,zipcode,skuId,openlightbox);
}function loadBrowseStore(zipcode,openlightbox){var url=contextRoot+"/includes/pickupStores.jsp";
var div="PickupDivOverlay";
var skuId=getSelectedSkuId();
var productId=$("#"+skuId+"_productId").val();
loadStore(url,div,zipcode,skuId,openlightbox,productId,"addToCart");
}function openAdStoreOverlay(){var zipcode=$("#zipCodeTxt").val();
if(zipcode!=""&&zipcode!="Zip Code"){var validZipCode=validateZipCode(zipcode);
if(!validZipCode){$("div#zipcodeError").html('<div class="oops"><span class="text">Please enter a valid zipcode</span></div>');
$("input#zipCodeTxt").addClass("error");
}$("div#zipcodeError").html("");
$("input#zipCodeTxt").removeClass("error");
var url=contextRoot+"/weekly-ads/adstoreoverlay.jsp";
var div="storeOverlay";
var skuId="";
loadStore(url,div,zipcode,skuId,true);
}else{$("div#zipcodeError").html('<div class="oops"><span class="text">Please enter a zipcode</span></div>');
$("input#zipCodeTxt").addClass("error");
}}function openAdStoreOverlayFromShoppingList(){var url=contextRoot+"/mylist/includes/storeOverlay/dealstoreoverlay.jsp";
var div="storeOverlay";
var skuId="";
loadStore(url,div,"",skuId,true);
}function openShopListStoreOverLay(){var zipcode=$("#zipCodeTxt").val();
if(undefined==zipcode){zipcode="";
}var url=contextRoot+"/mylist/includes/storeOverlay/shopliststoreoverlay.jsp";
var div="storeOverlay";
var skuId="";
loadStore(url,div,zipcode,skuId,true);
}function openCategoryStoreOverLay(){var zipcode=$("#zipCodeTxt").val();
if(undefined==zipcode){zipcode="";
}var url=contextRoot+"/includes/categorystoreoverlay.jsp";
var div="catStoreOverlay";
var skuId="";
loadStore(url,div,zipcode,skuId,true);
}function loadStore(url,div,zipcode,skuId,openlightbox,productId,operation){var divId="#"+div;
var displayDefaultMsg=true;
if(zipcode!=""){displayDefaultMsg=false;
}$.ajax({url:url,dataType:"html",type:"POST",data:"zipcode="+zipcode+"&skuId="+skuId+"&displayDefaultMsg="+displayDefaultMsg+"&prdId="+productId+"&operation="+operation,success:function(data){$(divId).html(data);
}});
if(openlightbox){$(divId).modal({minWidth:886,minHeight:624});
}}function refreshStores(source){var zipcode=$(".map-controllers #zipcode").val();
if(source=="pickup"){loadPickupStore(zipcode,false);
return;
}else{if(source=="changeStore"){loadChangeSelectedStore(zipcode,false);
return;
}else{if(source=="weeklyads"){loadWeeklyAddsStores(zipcode,false);
return;
}else{if(source=="dealproducts"){loadDealProductsStores(zipcode,false);
return;
}else{if(source=="shoplist"){loadShopListStores(zipcode,false);
return;
}else{if(source=="category"){loadCategoryStores(zipcode,false);
return;
}else{if(source=="browse"){loadBrowseStore(zipcode,false);
return;
}}}}}}}loadAvailableStore(zipcode,false);
}function getSelectedSkuId(){var choiceHiddenValue="";
$(".pickerhidden").each(function(){var pickerValue=$(this).val();
if(pickerValue==null||$.trim(pickerValue)==""){$(this).parent().children(".pdp-step_title").children("#pickerText").addClass("error");
error=true;
}else{$(this).parent().children(".pdp-step_title").children("#pickerText").removeClass("error");
}choiceHiddenValue+=pickerValue;
});
var hiddenValuesId="#sku_"+choiceHiddenValue;
var skuId=$(hiddenValuesId).val();
if(skuId==""||skuId==undefined){skuId=$("#defaultChildSku").val();
}return skuId;
}function pageSelectCallback(page_index,jq){var zipcode=$("#storeZipCode").val();
var pageNumber=(page_index+1);
var url=$("input#moreStoreURL").val();
var pcrActive=$("input#pcrActive").val();
var pcrString="";
if((pcrActive!=undefined)&&(pcrActive!=null)&&(pcrActive==="")){pcrString="&pcrActive="+pcrActive;
}$.ajax({url:url,dataType:"xml",type:"POST",data:"zipcode="+zipcode+"&pageNumber="+pageNumber+"&showButton=true"+pcrString,success:function(data){$xml=$(data);
if($xml.find("success").text()){var htmlContent=$xml.find("htmlContent").text();
$("div#map-results").html(htmlContent);
locateAddressWithId("mapStoreOverlay");
}}});
}$(document).ready(function(){$("body").on("click","button#load-more-stores",function(){if(loadMoreStore){return false;
}loadMoreStore=true;
var url=$("input#moreStoreURL").val();
var zipcode=$("#storeZipCode").val();
var pageNumber=$("#storepageNumber").val();
var pcrActive=$("input#pcrActive").val();
var pcrString="";
if((pcrActive!=undefined)&&(pcrActive!=null)&&(pcrActive!="")){pcrString="&pcrActive="+pcrActive;
}$.ajax({url:url,dataType:"xml",type:"POST",data:"zipcode="+zipcode+"&pageNumber="+pageNumber+"&showButton=true"+pcrString,success:function(data){$xml=$(data);
if($xml.find("success").text()){var moreStoreAvailable=$xml.find("moreStoreAvailable").text();
var displayedStore=$xml.find("displayedStore").text();
var htmlContent=$xml.find("htmlContent").text();
$("ul#store-list").append(htmlContent);
$("font#toStore").html(displayedStore);
$("font#buttonToStore").html(displayedStore);
if(moreStoreAvailable=="false"){$("button#load-more-stores").hide();
}$("#storepageNumber").val(parseInt(pageNumber)+1);
clearPushpins(map);
locateAddress(map);
}}});
loadMoreStore=false;
return false;
});
$("button#storeGo").click(function(){loadFirstStores();
return false;
});
$("body").on("click","button#storeOverlayGo",function(){if(listOverlayStore){return false;
}var url=$("input#storeOverlayListURL").val();
var zipCode=$("input#zipcodeText").val();
listOverlayStore=true;
var pageNumber=1;
$.ajax({url:url,dataType:"xml",type:"POST",data:"zipcode="+zipCode+"&pageNumber="+pageNumber+"&showButton=true",success:function(data){$xml=$(data);
if($xml.find("success").text()){var success=$xml.find("success").text();
if(success=="true"){var htmlContent=$xml.find("htmlContent").text();
$("div#map-results").html(htmlContent);
locateAddressWithId("mapStoreOverlay");
var totalStore=$xml.find("totalNumberOfStore").text();
var opt={callback:pageSelectCallback};
$("#Pagination").pagination(totalStore,opt);
}else{var htmlContent=$xml.find("errorMessage").text();
$("div#map-results").html(htmlContent);
$("div#mapStoreOverlay").empty();
$("#Pagination").empty();
}}}});
listOverlayStore=false;
return false;
});
$("a#storeOverlay").click(function(){var url=$("input#storeOverlayURL").val();
$.ajax({url:url,dataType:"html",type:"POST",success:function(data){$("div#storeoverlay").html(data);
var zipCode=$("input#zipcodeText").val();
if(zipCode!=null&&zipCode!=""){$("button#storeOverlayGo").trigger("click");
}}});
$("div#storeoverlay").modal({minWidth:886,minHeight:624});
});
$("#storelocatorlink").click(function(){var zipcode=$("#sessionZipCode").val();
loadAvailableStore(zipcode,true);
});
$("#changeStorelink").click(function(){var zipcode=$("#sessionZipCode").val();
loadChangeSelectedStore(zipcode,true);
return false;
});
$(".pdp-carousel-add-to-cart-btn").click(function(){var productId=$(this).attr("id");
var skuColumnId="#skuId"+productId;
var skuId=$(skuColumnId).val();
var quantityColumnId="#quantity"+productId;
var quantity=$(quantityColumnId).val();
$("input#formProductId").val(productId);
$("input#formskuId").val(skuId);
$("input#formQuantity").val(quantity);
$("input#shipType").val("instore");
if($("#userSelectedStore").val()=="false"){recommendedProduct=true;
loadPickupStore($("#sessionZipCode").val(),skuId,true,productId,"addToCart");
return;
}else{$("form#addToCartForm").submit();
return;
}});
var pcrActive=$("#pcrActive").val();
if((pcrActive!=undefined)&&(pcrActive!=null)&&(pcrActive==="true")){loadFirstStores();
}$("body").on("click","button#selectShopListStore",function(){var contextRoot=$("#contextRoot").val();
var url=contextRoot+"/myaccount/setpreferredstore.jsp";
var storeId=$(this).attr("name");
$.ajax({url:url,dataType:"xml",type:"POST",data:"storeId="+storeId,success:function(data){$xml=$(data);
if($xml.find("success").text()){location.href=$("#targetURL").val();
}}});
});
$("body").on("click","button#selectCategoryStore",function(){var contextRoot=$("#contextRoot").val();
var url=contextRoot+"/includes/setpreferredstore.jsp";
var storeId=$(this).attr("name");
$.ajax({url:url,dataType:"xml",type:"POST",data:"storeId="+storeId,success:function(data){$xml=$(data);
if($xml.find("success").text()){location.href=$("#targetURL").val();
}}});
});
$("body").on("click",".cat-add-to-cart-btn",function(){var skuId=$(this).attr("name");
var productId=$("input#"+skuId+"_productId").val();
var quantity=$("input#"+skuId+"_"+productId+"_quantity").val();
$("input#formskuId").val(skuId);
$("input#defaultChildSku").val(skuId);
$("input#formProductId").val(productId);
$("input#formQuantity").val(quantity);
if($("#userSelectedStore").val()=="false"){loadStoreList($("#sessionZipCode").val(),skuId,true,productId,"addToCart");
}else{$("form#addToCartForm").submit();
}return false;
});
$("body").on("click","button#selectStore",function(){$("#userSelectedStore").val(true);
var storeId=$(this).attr("name");
$("input#formStore").val(storeId);
$("form#addToCartForm").submit();
});
$("body").on("click","button#changeStore",function(){var contextRoot=$("#contextRoot").val();
var storeId=$(this).attr("name");
$.ajax({url:contextRoot+"/pdp/includes/floral/updatecookiesessionstore.jsp",datatype:"json",type:"POST",data:"storeId="+storeId,success:function(data){var output=JSON.parse(data);
if(output.success=="true"){window.location.reload();
}else{}}});
return false;
});
$("body").on("click","button#selectDealStore",function(){var contextRoot=$("#contextRoot").val();
var storeId=$(this).attr("name");
$.ajax({url:contextRoot+"/pdp/includes/floral/updatecookiesessionstore.jsp",datatype:"json",type:"POST",data:"storeId="+storeId,success:function(data){var output=JSON.parse(data);
if(output.success=="true"){location.href=$("#dealProductsURL").val();
}else{}}});
return false;
});
});
function pageselectCallback(page_index,jq){var source="";
var id="";
var skuId=getSelectedSkuId();
var pageType=$("#sourceType").val();
var contextRoot=$("#contextRoot").val();
var url=contextRoot+"/pdp/includes/stores/storesFrag.jsp";
if(pageType!=""&&pageType!=undefined){source=pageType;
}if(skuId!=""&&skuId!=undefined){id=skuId;
}$("#map-results").load(url,"pageNumber="+(page_index+1)+"&query="+$("#zipcode").val()+"&skuId="+id+"&source="+source);
return false;
}function fetchStoreDetails(){var opt={callback:pageselectCallback};
$("#Pagination").pagination($("#totalNoOfStores").val(),opt);
}function loadFirstStores(){if(loadStores){return false;
}var url=$("input#storeListURL").val();
var zipCode=$("input#zipcode").val();
var pcrActive=$("input#pcrActive").val();
var pcrString="";
if((pcrActive!=undefined)&&(pcrActive!=null)&&(pcrActive!="")){pcrString="&pcrActive="+pcrActive;
}if(pcrString===""&&zipCode==""){return false;
}loadStores=true;
var pageNumber=1;
$.ajax({url:url,dataType:"xml",type:"POST",data:"zipcode="+zipCode+"&pageNumber="+pageNumber+"&showButton=true"+pcrString,success:function(data){$xml=$(data);
if($xml.find("success").text()){var success=$xml.find("success").text();
if(success=="true"){var htmlContent=$xml.find("htmlContent").text();
$("div#map-results").html(htmlContent);
clearPushpins(map);
locateAddress(map);
}else{var htmlContent=$xml.find("errorMessage").text();
$("div#map-results").html(htmlContent);
$("div#mapStoreOverlay").empty();
}}}});
loadStores=false;
return false;
}function loadStoreList(zipcode,skuId,openlightbox,productId,operation){var url=contextRoot+"/includes/pickupStores.jsp";
var div="PickupDivOverlay";
loadStore(url,div,zipcode,skuId,openlightbox,productId,operation);
}function validateZipCode(zipcode){var zipRegex=/^[1-9]{1}[0-9]{4}$/;
if(zipRegex.test(zipcode)){return true;
}else{return false;
}}