var isResultClicked=false;
var infobox;
jQuery(document).ready(function(){$("select").each(function(i,el){});
$("input#userQuery").on("keypress",function(e){if(e.keyCode===13){$("input.searchbtn").click();
return false;
}});
});
function GetMap(){return GetMapForId("mapDiv");
}function GetMapForId(id){var mapCenter=new Microsoft.Maps.Location(39.45,-98.9);
var bingKey=$("#bingKey").val();
map=new Microsoft.Maps.Map(document.getElementById(id),{credentials:bingKey,enableSearchLogo:false,showMapTypeSelector:false});
map.setView({mapTypeId:Microsoft.Maps.MapTypeId.road,center:mapCenter});
dataLayer=new Microsoft.Maps.EntityCollection();
map.entities.push(dataLayer);
var infoboxLayer=new Microsoft.Maps.EntityCollection();
map.entities.push(infoboxLayer);
Microsoft.Maps.registerModule("CustomInfoboxModule","/js/jquery/V7CustomInfobox.js");
Microsoft.Maps.loadModule("CustomInfoboxModule",{callback:function(){infobox=new CustomInfobox(map);
}});
Microsoft.Maps.Events.addHandler(map,"dblclick",function(event){switch(event.targetType){case"pushpin":event.handled=true;
}});
return map;
}function zoomStore(focusInLocation,map){if(map.getZoom()!=16){map.setView({center:focusInLocation,zoom:16});
}else{map.setView({center:focusInLocation,});
}isResultClicked=true;
return true;
}function focusOnStore(latitude,longitude,map,pinNum){var focusInLocation=new Microsoft.Maps.Location(latitude,longitude);
if(zoomStore(focusInLocation,map)){invokePinMouseOver(map,focusInLocation,pinNum);
}}function focusOffStores(map){var focusInLocation=new Microsoft.Maps.Location($("#centerLat").val(),$("#centerLong").val());
map.setView({center:focusInLocation,zoom:14});
}function focusFirstStore(map,latitude,longitude){var focusInLocation=new Microsoft.Maps.Location(latitude,longitude);
var zoomValue=map.getZoom()-2;
map.setView({center:focusInLocation,zoom:14});
}function closeInfoBox(){infobox.setOptions({visible:false});
close_highlightInfoBox();
}function search_createMapPin(count,storeURL,centerLat,centerLong,latitude,longitude,storeName,address,city,state,postalCode,storeNumber,phoneNum,pharmacyPhNum,distance,map,needInfo){var pushpinOptions={icon:"/img/storeLocator/pin.png",text:count+"",visible:true};
var location=new Microsoft.Maps.Location(latitude,longitude);
var centerLocation=new Microsoft.Maps.Location(centerLat,centerLong);
var pin=new Microsoft.Maps.Pushpin(location,pushpinOptions);
var infoBox;
if(needInfo==true){Microsoft.Maps.Events.addHandler(pin,"mouseover",function(event){showInfoBox(count,storeURL,latitude,longitude,storeName,address,city,state,postalCode,storeNumber,phoneNum,pharmacyPhNum,distance,event);
});
Microsoft.Maps.Events.addHandler(pin,"click",function(event){showInfoBox(count,storeURL,latitude,longitude,storeName,address,city,state,postalCode,storeNumber,phoneNum,pharmacyPhNum,distance,event);
});
}Microsoft.Maps.Events.addHandler(pin,"mouseover",function(){search_highlightInfoBox("loadMoreStoresLoop"+count);
});
Microsoft.Maps.Events.addHandler(pin,"click",function(){search_highlightInfoBox("loadMoreStoresLoop"+count);
});
dataLayer.push(pin);
map.setView({center:centerLocation,zoom:14});
$("a.MapPushpinBase div").addClass("pinOverlay");
}function search_createMapPinNoCenter(count,storeURL,latitude,longitude,storeName,address,city,state,postalCode,storeNumber,phoneNum,pharmacyPhNum,distance,map){var pushpinOptions={icon:"/img/storeLocator/pin.png",text:count+"",visible:true};
var location=new Microsoft.Maps.Location(latitude,longitude);
var pin=new Microsoft.Maps.Pushpin(location,pushpinOptions);
var infoBox;
Microsoft.Maps.Events.addHandler(pin,"mouseover",function(){search_highlightInfoBox("loadMoreStoresLoop"+count);
});
dataLayer.push(pin);
}function showInfoBox(count,storeURL,latitude,longitude,storeName,address,city,state,postalCode,storeNumber,phoneNum,pharmacyPhNum,distance,e){var pharmacy="";
var distanceString="";
var boxLocation=new Microsoft.Maps.Location(latitude,longitude);
if(pharmacyPhNum!=null&&pharmacyPhNum!=""){pharmacy="<p>Pharmacy:<span>"+pharmacyPhNum+"</span> </p>";
}if(distance!=null&&distance!=""){distanceString="<p class='distance-note'>"+distance+"miles away</p>";
}if(infobox!=null){infobox.setOptions({offset:{x:0,y:0}});
var description="<div><p>Corporate #"+storeNumber+"</p><p>"+address+"</p> <p>"+city+","+state+" "+postalCode+"</p></div><div><p>Main:<span>"+phoneNum+"</span></p>"+pharmacy+"</div><div>"+distanceString+"</div><p><a href='"+storeURL+"' class='seemorelink' title='Store Details'>Store Details<span class='bullet'></span></a></p>";
var html=["<div id='contentInfoWindow' class='contentMap'><div class='contentTxt'>"];
html.push("<a href="+storeURL+"><h2 class='system-link'>",storeName,"</h2></a>");
html.push(description);
html.push("</div></div>");
infobox.show(boxLocation,html.join(""));
}}function userSelectFeats(form){var selectedFeats="";
for(var i=0;
i<form.elements.length;
i++){if(form.elements[i].type=="checkbox"){if((form.elements[i].checked==true)&&(form.elements[i].disabled==false)&&(form.elements[i].value!="")){selectedFeats=selectedFeats+form.elements[i].value+"~";
}}}$("#storeresults").load(contextRoot+"/storelocator/storeresults.jsp",{selectedFeatures:selectedFeats});
}function loadNextSet(form,totalCount,setLimit){var count;
var totalShown=$(".show").length;
var pendingItem=totalCount-totalShown;
if(pendingItem>=setLimit){count=setLimit;
}else{count=pendingItem;
}var toBeShown=totalShown+count;
for(var i=totalShown+1;
i<=toBeShown;
i++){$("#loadMoreStoresLoop"+i).removeClass("dontShow").addClass(function(){return"show";
});
}$("#showIntialStoreCount").removeClass("show").addClass(function(){return"dontShow";
});
var countMessage="Showing "+toBeShown+" of "+totalCount;
document.getElementById("showUpdatedStoreCount").innerHTML=countMessage;
if(totalCount==toBeShown){$("#loadNextStoresButton").removeClass("button unselected").addClass(function(){return"dontShow";
});
}}function showMoreFeatures(key){var featureKey=key;
$("#showFeaturesCbox_"+featureKey).removeClass("dontShow").addClass(function(){return"show";
});
$("#filterSeeMoreLink_"+featureKey).removeClass("seemorelink").addClass(function(){return"dontShow";
});
$("#filterShowLessLink_"+featureKey).removeClass("dontShow").addClass(function(){return"seemorelink";
});
scrollPositionUpdate("#showFeaturesCbox_"+featureKey);
}function showLessFeatures(key){var featureKey=key;
$("#showFeaturesCbox_"+featureKey).removeClass("show").addClass(function(){return"dontShow";
});
$("#filterSeeMoreLink_"+featureKey).removeClass("dontShow").addClass(function(){return"seemorelink";
});
$("#filterShowLessLink_"+featureKey).removeClass("seemorelink").addClass(function(){return"dontShow";
});
scrollPositionUpdate("#showFeaturesCbox_"+featureKey);
}function populateErrorMsg(){var mainErrorMsg=document.getElementById("mainErrorMsg");
if(mainErrorMsg==undefined){$("#errorMsg").removeClass("dontShow").addClass(function(){return"oops";
});
$("#errorMsg").html("<span class='text'>There are no stores found within the selected radius of the input address, please change the search options and try again</span>");
}}function clearErrorMsg(){$("#errorMsg").removeClass("oops").addClass(function(){return"dontShow";
});
}function search_highlightInfoBox(divId){close_highlightInfoBox();
$("#"+divId).find("div.store-cont").css("background-color","white");
}function close_highlightInfoBox(){$('[id^="loadMoreStoresLoop"]').find("div.store-cont").css("background-color","");
}function validateString(obj,evt){var key=(evt.which)?evt.which:event.keyCode;
if(key==8){return true;
}var reg=/^[a-zA-Z0-9\s,-]*$/i;
if(!reg.test(obj.value)){obj.value=obj.value.replace(/[^a-zA-Z0-9\s,-]/g,"");
}return reg.test(String.fromCharCode(key));
}function locateAddress(map){if(map==null||map=="undefined"){map=GetMap();
}locateAddressInMap(map,false);
}function locateAddressWithId(id){var map=GetMapForId(id);
locateAddressInMap(map,true);
}function locateAddressInMap(map,isIgnoreEmptyStoreId){$(".locateMap").each(function(){var centralLat=0;
var centralLong=0;
var needInfo=false;
var storeId=$(this).attr("id");
if(isIgnoreEmptyStoreId&&storeId==""){}else{if($("#"+storeId+"showModel").val()=="true"){needInfo=true;
}var ignoreLocate=$("#"+storeId+"ignoreLocate").val();
var count=$("#"+storeId+"indexCount").val();
var storeURL=$("#"+storeId+"url").val();
latitude=$("#"+storeId+"latitude").val();
longitude=$("#"+storeId+"longitude").val();
var storeName=$("#"+storeId+"storeName").val();
var address=$("#"+storeId+"address").val();
var city=$("#"+storeId+"city").val();
var state=$("#"+storeId+"state").val();
var postalCode=$("#"+storeId+"postalCode").val();
var storeNumber=$("#"+storeId+"storeNumber").val();
var phoneNum=$("#"+storeId+"phoneNum").val();
var centerLat=$("#"+storeId+"centerLat").val();
var centerLong=$("#"+storeId+"centerLong").val();
var pharmacyPhNum=$("#"+storeId+"pharmacyPhNumber").val();
var distance=$("#"+storeId+"distance").val();
if(centerLat==""){if(centralLat==0&&centralLong==0){search_createMapPinNoCenter(count,storeURL,latitude,longitude,storeName,address,city,state,postalCode,storeNumber,phoneNum,pharmacyPhNum,distance,map);
}else{search_createMapPin(count,storeURL,centralLat,centralLong,latitude,longitude,storeName,address,city,state,postalCode,storeNumber,phoneNum,pharmacyPhNum,distance,map,needInfo);
}}else{search_createMapPin(count,storeURL,centerLat,centerLong,latitude,longitude,storeName,address,city,state,postalCode,storeNumber,phoneNum,pharmacyPhNum,distance,map,needInfo);
}}});
}function scrollPositionUpdate(id){var elementClass=jQuery(id).parent().attr("class");
var elementArray=elementClass.split(" ");
var isLast=false;
if("last"==elementArray[2]){isLast=true;
}var elementPosition=elementArray[1];
var heightPosition=0;
jQuery(".viewport ul").each(function(index,element){if(index<elementPosition-1){heightPosition+=jQuery(element).height();
}});
var scrollPosition=jQuery("#scrollbar1");
scrollPosition.tinyscrollbar();
jQuery("#scrollbar1").tinyscrollbar({sizethumb:55});
var positionVal=((heightPosition/590)*(elementPosition))*100;
if(heightPosition<positionVal){positionVal=((heightPosition/590)*(elementPosition))*50;
}if(isLast){positionVal-=250;
}scrollPosition.tinyscrollbar_update(positionVal);
}function clearPushpins(map){for(var i=map.entities.getLength()-1;
i>=0;
i--){var dataLayer=map.entities.get(i);
if(dataLayer instanceof Microsoft.Maps.EntityCollection){for(var j=dataLayer.getLength()-1;
j>=0;
j--){if(dataLayer.get(j) instanceof Microsoft.Maps.Pushpin){dataLayer.removeAt(j);
}}}}}function invokePinMouseOver(map,focusInLocation,pinNum){for(var i=map.entities.getLength()-1;
i>=0;
i--){var dataLayer=map.entities.get(i);
if(dataLayer instanceof Microsoft.Maps.EntityCollection){for(var j=dataLayer.getLength()-1;
j>=0;
j--){if(dataLayer.get(j) instanceof Microsoft.Maps.Pushpin){var pin=dataLayer.get(j);
var pinLocation=pin.getLocation();
if(pin.getText()==pinNum){setTimeout(function(){showOverlayfunc(pin);
},500);
break;
}}}}}}function showOverlayfunc(pin){Microsoft.Maps.Events.invoke(pin,"mouseover");
}function resetInfoDisplay(){if(isResultClicked){isResultClicked=false;
}else{closeInfoBox();
}isResultClicked=false;
}