function addCouponToOrder(){$("input#couponAction").val("add");
var couponCode=$("input#addCouponCode").val();
$("input#couponCode").val(couponCode);
document.getElementById("couponForm").submit();
}$(document).ready(function(){$("a#miniCartLogo").mouseover(function(){});
$("#mini-cart").on("click",".closeitem.right",function(){$("#mini-cart").slideUp();
clearInterval(timerMC);
});
$("window,body").on("mousemove keypress",function(){timerMCValue=0;
});
$("body").on("click","button#triggerRemoveCode",function(){$("input#couponAction").val("remove");
$("input#removeCouponCode").val($(this).attr("name"));
document.getElementById("couponForm").submit();
return false;
});
$("body").on("click","button#chkoutBtn",function(){$("input#actionType").val("checkOut");
document.getElementById("modifyOrderForm").submit();
return false;
});
$("body").on("click","button#updateQuantity",function(){$("input#updateSkuId").val($(this).attr("name"));
$("input#actionType").val("");
document.getElementById("modifyOrderForm").submit();
return false;
});
$("body").on("click","button#removeItem",function(){$("input#deleteItemId").val($(this).attr("name"));
$("input#actionType").val("");
document.getElementById("modifyOrderForm").submit();
return false;
});
$("body").on("click","input#floralOverlay",function(){var value=$(this).attr("name");
var result=value.split("_");
loadEditFloralOverlay(result[0],result[1],false,1);
return false;
});
$("body").on("click","input#bakeryOverlay",function(){var value=$(this).attr("name");
var result=value.split("_");
loadEditBakeryOverlay(result[0],result[1],false,1);
return false;
});
$("body").on("click","input#pickerOverlay",function(){var value=$(this).attr("name");
var result=value.split("_");
loadEditPickerOverlay(result[0],result[1],false,1);
return false;
});
});
function loadEditPickerOverlay(commId,prodId,isError,errorQuantity){var url="includes/overlay/editpickeroverlay.jsp";
var div="cartOverlay";
loadRequestedPage(url,div,commId,prodId,errorQuantity,isError,true);
}function loadEditBakeryOverlay(commId,prodId,isError,errorQuantity){var url="includes/overlay/editbakeryoverlay.jsp";
var div="cartOverlay";
loadRequestedPage(url,div,commId,prodId,errorQuantity,isError,true);
}function loadEditFloralOverlay(commId,prodId,isError,errorQuantity){var url="includes/overlay/editfloraloverlay.jsp";
var div="cartOverlay";
loadRequestedPage(url,div,commId,prodId,errorQuantity,isError,true);
}function loadRequestedPage(url,div,commId,prodId,errorQuantity,isError,openOverLay){var divId="#"+div;
var delivPostalCodeDiv="input#"+commId+"_hiddenDeliveryPostalCode";
var delivPostalCode=$(delivPostalCodeDiv).val();
$.ajax({url:url,dataType:"html",type:"POST",data:"itemId="+commId+"&productId="+prodId+"&errorQuantity="+errorQuantity+"&isError="+isError+"&delivPostalCode="+delivPostalCode,success:function(data){if("Error"==data){window.location=contextRoot+"/applicationerror.jsp";
}$(divId).html(data);
}});
if(openOverLay){$(divId).modal({minWidth:855,minHeight:699,fixed:false});
}}