var prescription_index_remove=1;
var prescription_index=1;
var transfer_prescription=1;
var dependent_counter=4;
$(document).ready(function(){$(".ui-datepicker-trigger").datepicker("option","minDate",-4);
$(".cancelLink").click(loadCancelOverlayPage);
$(".remove-pres").click(removePrescription);
$(".addDependent").click(addDependent);
$(".removeDependent").click(removeDependent);
$(".remove-pres-refill").click(loadCancelRefillRevOverlayPage);
$(".remove-express-pres").click(loadCancelRefillExpOverlayPage);
$(".pharmacyprofileoverlay").click(loadProfileCancelOverlayPage);
$(".showInsuranceForm").click(loadInsuranceForm);
var pageCount=document.getElementById("prescriptionCount");
if(pageCount!=null){prescription_index=$(pageCount).val();
}$(document).on("click","a[id='add_prescription']",function(e){var pageValue=$(this).data("page_value");
prescription_index++;
$(this).parent().before($("#prescription_number1").clone(true).attr("id","prescription_number"+prescription_index));
$("#prescription_number"+prescription_index).css("display","inline");
$("#prescription_number"+prescription_index+" :input").each(function(){$(this).attr("id",$(this).attr("id")+prescription_index);
$(this).val("as on prescription bottle");
$(this).addClass("ghost");
$(this).addClass("rxpharmacyimg");
$(this).removeClass("input-error");
});
$("#prescription_number"+prescription_index+" label").attr("for","presLabel"+prescription_index);
$("#prescription_number"+prescription_index+" a").attr("style","visibility:none");
$("#prescription_number"+prescription_index+" .error").attr("id","errorprescription1"+prescription_index);
$("div#errorprescription1"+prescription_index).hide();
$("#prescription_number"+prescription_index+" a").attr("data-div_value","prescription_number"+prescription_index);
if(pageValue=="refillExpress"){$("label[for=presLabel"+prescription_index+"]").html("Prescription #"+prescription_index+" <sup class='required'>&#42;</sup></label>");
}else{$("label[for=presLabel"+prescription_index+"]").html("Prescription #"+prescription_index+" <em>*</em></label>");
}if(prescription_index==10){$(".addPrescription").hide();
}if(pageValue!="refillStatus"){$("input.ghost").focus(removeDefaultValues);
}$(".remove-pres").click(removePrescription);
});
$("button#refillExValidatePatient").click(function(e){e.preventDefault();
if(validatePatientFormFields()){return false;
}$("form#refillExpress").submit();
});
$("button#refillRxValidatePatientCheck").click(function(e){e.preventDefault();
if(validatePatientFormFields()){return false;
}$("form#refillStatusForm").submit();
});
$("a#userInformation").on("click",function(e){e.preventDefault();
if($(this).hasClass("graybutton")){return false;
}else{if(validateTransferPrescriptionForm()){return false;
}$("form#userInformationForm").submit();
}});
$("a#userInformation").on("keypress",function(e){if(e.keyCode==13){if($(this).hasClass("graybutton")){return false;
}else{if(validateTransferPrescriptionForm()){return false;
}$("form#userInformationForm").submit();
}}});
$("a#currentPharmacy").on("click",function(){if($(this).hasClass("graybutton")){return false;
}else{if(validateTransferPrescriptionCurrentPharmacy()){return false;
}$('input[id^="drugPrescription"]').each(function(index){if($(this).hasClass("ghost")){$(this).val("");
}});
$("form#userInformationForm").submit();
}loadSubmitData();
});
$("button#refillExReview").click(function(e){e.preventDefault();
$("form#refillExpressReview").submit();
});
$("button#refillExNotfy").click(function(e){e.preventDefault();
$("div#refillExpErrorMessage").hide();
$("div#formErrorMessage").hide();
if(validateExpNtfyFields("true")){$("div#refillExpErrorMessage").show();
$(document).scrollTop(100);
return false;
}$("form#refillExpNtfy").submit();
});
$("button#transferPresNotfy").click(function(e){e.preventDefault();
if($(this).hasClass("graybutton")){return false;
}else{if(validateTransferPrescriptionNotificationFields("transferPresChkSms","transferPresChkPhone","transferPresChkEmail")){$(document).scrollTop(100);
return false;
}}$("form#setupAutoRefill").submit();
});
$("button#refillExSubmit").click(function(e){e.preventDefault();
$("form#refillExpSubmit").submit();
});
$("#rxRefillExpChkSms").live("click",function(event){if($(this).is(":checked")){$("#refillExpChkDisc").removeAttr("disabled");
$("#refillExpChkDiscBlock").css("visibility","visible");
$("div.stepThreeBlock.lastBlock").find("sup.required").css("visibility","visible");
$("div.stepThreeBlock.lastBlock").children("div.requiredContainer").css("visibility","visible");
}else{$("#refillExpChkDisc").removeClass("checked");
$("#refillExpChkDisc").attr("disabled","disabled");
$("#refillExpChkDiscBlock").css("visibility","hidden");
$("div.stepThreeBlock.lastBlock").children("div.requiredContainer").css("visibility","hidden");
$("div.stepThreeBlock.lastBlock").find("sup.required").css("visibility","hidden");
}});
if($("#rxRefillExpChkSms").length){if($(this).is(":checked")){$("#refillExpChkDiscBlock").css("visibility","visible");
$("div.stepThreeBlock.lastBlock").find("sup.required").css("visibility","visible");
$("div.stepThreeBlock.lastBlock").children("div.requiredContainer").css("visibility","visible");
}else{$("#refillExpChkDisc").removeClass("checked");
$("#refillExpChkDiscBlock").css("visibility","hidden");
$("div.stepThreeBlock.lastBlock").children("div.requiredContainer").css("visibility","hidden");
$("div.stepThreeBlock.lastBlock").find("sup.required").css("visibility","hidden");
}}$("#transferPresChkSms").live("click",function(event){if($(this).is(":checked")){$("#transferPresChkAgreement").removeAttr("disabled");
$("#transferPresChkDiscBlock").css("visibility","visible");
$("ul.rows li.last").find("sup.required").css("visibility","visible");
$("ul.rows li.last").children("div.requiredContainer").css("visibility","visible");
}else{$("#transferPresChkAgreement").removeClass("checked");
$("#transferPresChkAgreement").attr("disabled","disabled");
$("#transferPresChkDiscBlock").css("visibility","hidden");
$("ul.rows li.last").children("div.requiredContainer").css("visibility","hidden");
$("ul.rows li.last").find("sup.required").css("visibility","hidden");
}});
if($("#transferPresChkSms").length){if($(this).is(":checked")){$("#transferPresChkDiscBlock").css("visibility","visible");
$("ul.rows li.last").find("sup.required").css("visibility","visible");
$("ul.rows li.last").children("div.requiredContainer").css("visibility","visible");
}else{$("#refillExpChkDisc").removeClass("checked");
$("#transferPresChkDiscBlock").css("visibility","hidden");
$("ul.rows li.last").children("div.requiredContainer").css("visibility","hidden");
$("ul.rows li.last").find("sup.required").css("visibility","hidden");
}}$("#profilePhone").live("click",function(event){if($(this).is(":checked")){$("#profilephoneauth").removeAttr("disabled");
$("#profilemobileauth").removeAttr("disabled");
}});
$("#profileText").live("click",function(event){if($(this).is(":checked")){$("#profilephoneauth").prop("checked",false);
$("#profilemobileauth").prop("checked",false);
$("#profilephoneauth").attr("disabled","disabled");
$("#profilemobileauth").attr("disabled","disabled");
}});
$("#profileEmail").live("click",function(event){if($(this).is(":checked")){$("#profilephoneauth").prop("checked",false);
$("#profilemobileauth").prop("checked",false);
$("#profilephoneauth").attr("disabled","disabled");
$("#profilemobileauth").attr("disabled","disabled");
}});
$("input.ghost").focus(removeDefaultValues);
$("#refillStatusForm input.ghost").on("blur",function(){if($(this).val()==""&&$(this).data("ghost")!=undefined&&$(this).data("ghost")!=""){$(this).val($(this).data("ghost"));
$(this).addClass("ghost");
}});
$("button#storeGo").click(function(){loadFirstStores();
return false;
});
$("a#print-history-mail-overlay").click(function(){$("#OverlayDiv").modal({minWidth:735,minHeight:719});
});
$("body").on("click","button.storeSelectButton",function(){$("button.storeSelectButton").each(function(){$(this).show();
});
var storeId=$(this).attr("value");
$("input#preferredStore").val(storeId);
$(".storeContinue").removeClass("graybutton");
$(".storeContinue").prop("disabled",false);
setUrlParam();
$(this).hide();
return false;
});
enableSmtOnNewPres();
$(".requiredVal").on("keyup",enableSmtOnNewPres);
$("body").on("keyup",".numberOnly",validateNumber);
$("body").on("keyup",".nameOnly",validateUserName);
$("body").on("keyup",".alphaNumberOnly",validateAlphaNumber);
$(".nameForNotRX").hide();
$(".prescriberName select").change(setReqFieldsPresc);
var newRxPatient=$(".PatientName select").val();
if(newRxPatient!=null&&newRxPatient=="other"){$("div.nameForRX").hide();
$("div.nameForNotRX").show();
$("div#hiddenNameVal").html("");
$("div.nameForNotRX input").addClass("requiredVal");
var dobLab=$("div.nameForNotRXDOB").parent().find("label");
var curText=$(dobLab).html()+"<em>*</em>";
$(dobLab).html(curText);
}var selAttrValDef=$(".prescriberName select").find("option:selected").html();
if(selAttrValDef!=null){var fullNameDef=selAttrValDef.split("&nbsp;");
$("#presFName").val("");
$("#presLName").val("");
if(fullNameDef.length>0){$("#presFName").val(fullNameDef[0]);
}if(fullNameDef.length>1){$("#presLName").val(fullNameDef[1]);
}}$("button#rxRefillExpressBtn").click(function(e){e.preventDefault();
var refillOption=$('input[name="ntfyStatus"]:checked').attr("value");
$("input#refillOption").val(refillOption);
var isEditTrue=$("#isEditMode").val();
if(validateExpNtfyFields(isEditTrue)){return false;
}$("input[type=checkbox]").each(function(){if($(this).attr("disabled")!=null){$(this).removeAttr("disabled");
}});
$("form#rxRefillExpress").submit();
});
$("button#pharmcyStoreGo").click(function(event){var zipCode=$("input#zipCode").val();
var selectStore=$("input#selectStore").val();
var divId="#storeComp";
var pageName=$("#pageName").val();
var loadMap=$("#loadMap").val();
if(zipCode==""||zipCode==" "||!isValidZip(zipCode)||zipCode=="00000"){$("div#errorMessage").show();
$("div#errorMessage div.errorZipInvalid").show();
$("div#errorMessage div.errorZipNoRecords").hide();
$("input#zipCode").addClass("error");
$(divId).html("");
return false;
}$.ajax({url:contextRoot+"/pharmacy/common/pharmacyBingMap.jsp",dataType:"html",type:"POST",data:"zipCode="+zipCode+"&isPharmacy=true&pageName="+pageName+"&selectStore="+selectStore+"&loadMap="+loadMap,success:function(data){var result=$(data).filter("div#map-controllers").attr("id");
if(result!="map-controllers"){$(divId).html("");
$("div#errorMessage").show();
$("div#errorMessage div.errorZipNoRecords").show();
$("div#errorMessage div.errorZipInvalid").hide();
$("input#zipCode").addClass("error");
return false;
}else{$(divId).html(data);
$("input#zipCode").removeClass("error");
$("div#errorMessage").hide();
locateAddress();
}}});
return false;
});
$("a#addTransferPrescription").click(function(event){var cur=transfer_prescription;
transfer_prescription++;
if(cur<10){var html=getDrugNameStrings(transfer_prescription);
$("div#prescriptionCounter"+cur).after(html);
$("input#drugCount").val(transfer_prescription);
$("input.ghost").focus(removeDefaultValues);
}if(transfer_prescription==10){$("a#addTransferPrescription").css("visibility","hidden");
}$("#currentPharmacy").addClass("graybutton");
event.stopPropagation();
});
$("button#profilePrescInfo").click(function(e){e.preventDefault();
if(validateProfilePrescInfo()){return false;
}$("form#profilePresc").submit();
});
$("button#profileNotification").click(function(e){e.preventDefault();
if(validateProfileNotification()){return false;
}$(this).addClass("graybutton");
$(this).attr("onclick","return false;");
$("form#profileNotfy").submit();
});
$("button#profileAuthCode").click(function(e){e.preventDefault();
if(validateProfileAuthenticationCode()){return false;
}$("form#profileAuthorize").submit();
});
$("#showHideUpcomingAutoRefills").on("click",function(){if($("#moreUpcomingAutoRefills").is(":visible")){$("#moreUpcomingAutoRefills").hide();
$.scrollTo($(this).parent().parent().parent(),800);
$(this).text("Show More");
}else{$("#moreUpcomingAutoRefills").show();
$(this).text("Show Less");
}});
$("#showHideViewMoreAutoRefills").on("click",function(){if($("#viewMoreUpcomingAutoRefills").is(":visible")){$("#viewMoreUpcomingAutoRefills").hide();
$(this).text("View More");
}else{$("#viewMoreUpcomingAutoRefills").show();
$(this).text("View Less");
}});
$("button#refillRxValidatePatient").click(function(e){e.preventDefault();
if(validatePatientFormFields()){return false;
}$("form#refillRx").submit();
});
$("body").on("click","button#refillRxValidatePatientHelp",function(e){e.preventDefault();
if(validatePatientFormFields()){return false;
}$("form#refillRxHelp").submit();
});
$("button#paymentFormSubmit").click(function(e){e.preventDefault();
if(validateRewardsPaymentForm()){return false;
}$("form#paymentForm").submit();
});
$("select#pickUpTimeDD").change(populatePickUpDateTime);
$("#manageRxRefillCheckoutButton").on("click",function(){if($("#manageRxRefillCheckoutForm input[type=checkbox]:checked").length>0){document.getElementById("manageRxRefillCheckoutForm").submit();
return true;
}else{return false;
}});
if($("#manageRxRefillCheckoutForm").length){$('li.select-for-refill input[type="checkbox"]').on("click",function(){if($("li.select-for-refill input:checked").length>0){$("#manageRxRefillCheckoutButton").prop("disabled",false);
$("#manageRxRefillCheckoutButton").removeClass("graybutton");
}else{$("#manageRxRefillCheckoutButton").prop("disabled",true);
$("#manageRxRefillCheckoutButton").addClass("graybutton");
}});
}checkedManagePrescription();
$(".secTitle").on("click",toggleProfileSections);
$("#addFamilyMember input[type=radio]").on("click",function(){if($(this).val()=="Yes"){$("#dependentInformation").show();
}else{$("#dependentInformation").hide();
}});
enableSbmtOnRewards();
$(".requiredValRewards").on("keyup",enableSbmtOnRewards);
$(".requiredValRewOpt").on("change",enableSbmtOnRewards);
$("#printRxHitoryBtn").on("click",function(){return printRxHistory(this);
});
enableSbmtOnRewardStep3();
$(".requiredValRewardStep3").on("keyup click",enableSbmtOnRewardStep3);
$(".requiredValRewDD").on("change",enableSbmtOnRewardStep3);
$(".profileMsg").change(function(){$("#profileMsgTxt").show();
});
if($("#userInformation").length){var isNotMissing=isRequiredFieldPopulated("#userInformationForm input:text, input:radio");
if(isNotMissing){$("#userInformation").removeClass("graybutton");
}else{$("#userInformation").addClass("graybutton");
}$('#userInformationForm input[data-required="true"]').on("keyup",function(){var isNotMissing=isRequiredFieldPopulated("#userInformationForm input:text, input:radio");
if(isNotMissing){$("#userInformation").removeClass("graybutton");
}else{$("#userInformation").addClass("graybutton");
}});
}$("body").on("keyup",'#frmCurrentPharmacy input[data-required="true"]',function(){checkFormCurrentPharmacyRequiredField();
});
$("#transferPresChkEmail").on("click",function(){if($(this).is(":checked")){$("#transferPresEmail").data("required",true);
$("#transferPresReEmail").data("required",true);
}else{$("#transferPresEmail").data("required",false);
$("#transferPresReEmail").data("required",false);
}});
$("#transferPresChkPhone").on("click",function(){if($(this).is(":checked")){$("#transferPresPhonePart1").data("required",true);
$("#transferPresPhonePart2").data("required",true);
$("#transferPresPhonePart3").data("required",true);
}else{$("#transferPresPhonePart1").data("required",false);
$("#transferPresPhonePart2").data("required",false);
$("#transferPresPhonePart3").data("required",false);
}});
$("#transferPresChkSms").on("click",function(){if($(this).is(":checked")){$("#transferPresMobilePart1").data("required",true);
$("#transferPresMobilePart2").data("required",true);
$("#transferPresMobilePart3").data("required",true);
$("#transferPresChkAgreement").data("required",true);
$("#transferPresChkAgreement").prop("checked",false);
$("#transferPresChkAgreement").prop("disabled",false);
$("em#required-star").show();
}else{$("#transferPresMobilePart1").data("required",false);
$("#transferPresMobilePart2").data("required",false);
$("#transferPresMobilePart3").data("required",false);
$("#transferPresChkAgreement").data("required",false);
$("#transferPresChkAgreement").prop("checked",false);
$("#transferPresChkAgreement").prop("disabled",true);
$("em#required-star").hide();
}});
if($("#setupAutoRefill").length){checkAllReqTransPresStep3();
$("#setupAutoRefill").on("keyup click","input:text, input:radio, input:checkbox",checkAllReqTransPresStep3);
}$("div.section-content").each(expandThisTab);
if($("#btnSelectRefillRxStore").length){if($("#preferredStore").val()!=""){$("#btnSelectRefillRxStore").removeClass("graybutton");
}}if($("#btnSelectTransferRxStore").length){if($("#preferredStore").val()!=""){$("#btnSelectTransferRxStore").removeClass("graybutton");
}}if($("#addMinorForm, #addPetForm, #refillStatusForm, #refillRx, #refillExpress, #profilePresc").length){$("#firstName, #fName").on("focus",setFirstNameImage);
$("#lastName, #lName").on("focus",setLastNameImage);
$("#corpNum, #corpNumber").on("focus",setCorpImage);
$('input[id^="prescription"], #presc').on("focus",setPrescriptionImage);
$("#dob-date, #dob-month, #dob-year, #dobDay, #dobMonth, #dobYear, #phonePart3").on("focus",setDefaultImage);
}if($("#printHistoryEmailOverlayForm").length){$("#printHistoryEmailOverlayForm").on("submit",function(){var userName=$("#userName");
var userEmail=$("#userEmail");
$("input.input-error").removeClass("input-error");
$("div.error").html("");
var isValidForm=true;
if(isFieldEmpty("userName")){userName.addClass("input-error");
userName.parent().children("div.error").html("Please enter name.");
isValidForm=false;
}if(isFieldEmpty("userEmail")){userEmail.addClass("input-error");
userEmail.parent().children("div.error").html("Please enter email.");
isValidForm=false;
}return isValidForm;
});
}var profilePageName=$("input#manageprofilePage").val();
if(profilePageName!=null&&profilePageName!=""){var inputname="a#"+profilePageName;
$(inputname).trigger("click");
}if($("#transferPresChkSms").is(":checked")){$("#transferPresChkAgreement").prop("disabled",false);
$("em#required-star").show();
}$(".gender").click(function(){if($(this).attr("checked")){if($(this).hasClass("checked")){$(this).removeClass("checked");
$(this).attr("checked",false);
}else{var name=$(this).attr("name");
$(".gender").each(function(){if(name==$(this).attr("name")){$(this).removeClass("checked");
}});
$(this).addClass("checked");
}}});
$(".tabs .tab a").click(function(){$(".left div.tab").each(function(){if($(this).hasClass("active")){$(this).removeClass("active").addClass("unselected");
}});
$(".left div.advice").each(function(){$(this).css("display","none");
});
var divId=$(this).parent().attr("name");
$("div#"+divId).css("display","");
$(this).parent().addClass("active");
});
$("a.immunizationLink").click(function(){$("a.immunizationLink").each(function(){$(this).removeClass("activeImu");
});
$(this).addClass("activeImu");
$("div.changeImmuContent").each(function(){$(this).hide();
});
var divId="div#"+$(this).attr("name");
$(divId).show();
});
$("a#resendAuthCode").click(function(e){e.preventDefault();
$("form#resendAuthCode").submit();
});
var pharmacyServiceDown=$("#pharmacyServiceDown").val();
if(pharmacyServiceDown!=null&&pharmacyServiceDown=="true"){$("#pharmacyServiceDownMsg").show();
}$("body").on("click","div.tab-container div.tab",function(){$("div.tab-container div.tab").each(function(){$(this).removeClass("active");
});
$("div.tab-content-wrapper").each(function(){$(this).hide();
});
var divId="div#"+$(this).attr("title");
$(divId).show();
var titleValue=$(divId).attr("title");
if(titleValue==null||titleValue==""){var contentUrl=getPharmacyLandingTabURL($(this).attr("title"));
if(contentUrl!=null){$(divId).html('<img id="img-spinner" src="/img/ajax-loader.gif" alt="Loading" align="center"/>');
$.ajax({url:contentUrl,type:"GET",dataType:"html",success:function(data){$(divId).html(data);
$(divId).attr("title","true");
titlemessageWithCss();
}});
}}$(this).addClass("active");
});
$("body").on("click","#refillStatusTabBtn",function(e){e.preventDefault();
var errorMessage=false;
if(validateInputField("#rxStausTab_fName",$("#emptyRefillStatusFirstName").val())){errorMessage=true;
}if(validateInputField("#rxStausTab_lName",$("#emptyRefillStatusLastName").val())){errorMessage=true;
}if(validateInputField("#rxStausTab_corpNumber",$("#emptyRefillStatusCorpNo").val())){errorMessage=true;
}if(validateDateFields("#rxStausTab_dobMonth","#rxStausTab_dobDay","#rxStausTab_dobYear",$("#invalidRxMonth").val(),$("#invalidRxDay").val(),$("#invalidRxYear").val())){errorMessage=true;
}if(validateInputField("#rxStausTab_prescription",$("#invalidRxPrescription").val())){errorMessage=true;
}if(errorMessage){return false;
}$("form#refillStatusTabForm").submit();
});
$("body").on("click","#refillExpBtn",function(e){e.preventDefault();
var errorMessage=false;
if(validateInputField("#refillexp_firstName",$("#emptyRefillStatusFirstName").val())){errorMessage=true;
}if(validateInputField("#refillexp_lastName",$("#emptyRefillStatusLastName").val())){errorMessage=true;
}if(validateInputField("#refillexp_corpNumber",$("#emptyRefillStatusCorpNo").val())){errorMessage=true;
}if(validateDateFields("#refillexp_dobMonth","#refillexp_dobDay","#refillexp_dobYear",$("#invalidRxMonth").val(),$("#invalidRxDay").val(),$("#invalidRxYear").val())){errorMessage=true;
}if(validateInputField("#refillexp_prescription",$("#invalidRxPrescription").val())){errorMessage=true;
}if(errorMessage){return false;
}$("form#autoRefillTab").submit();
});
$("body").on("click","#transferRxTabBtn",function(e){e.preventDefault();
var errorMessage=false;
if(validateInputField("#transferrx_drugName",$("#transferRxEmptyDrugName").val())){errorMessage=true;
}if(validateInputField("#transferrx_pname",$("#transferRxEmptyPharmacy").val())){errorMessage=true;
}if(validatePhoneNumber("#transferrx_phonePart1","#transferrx_phonePart2","#transferrx_phonePart3",$("#invalidRxPhoneNumber").val())){errorMessage=true;
}if($("#drugPrescription").val()==$("#drugPrescription").attr("title")){$("#drugPrescription").val("");
}if(errorMessage){return false;
}$("form#transferRxTab").submit();
});
$("body").on("click","#requestRxNewTabBtn",function(e){e.preventDefault();
var errorMessage=false;
if(validateInputField("#reqnewRx_presLName",$("#emptyRefillStatusLastName").val())){errorMessage=true;
}if(validateInputField("#reqnewRx_med",$("#invalidMedication").val())){errorMessage=true;
}if(validatePhoneNumber("#reqnewRx_presPh1","#reqnewRx_presPh2","#reqnewRx_presPh3",$("#invalidRxPhoneNumber").val())){errorMessage=true;
}if(errorMessage){return false;
}$("form#requestNewRxTabFrm").submit();
});
if($("input#tabActiveFlag").length){var tabValue=$("input#tabActiveFlag").val();
$("div.tab-container div.tab").each(function(){$(this).removeClass("active");
if($(this).attr("title")==tabValue){$(this).addClass("active");
}});
}$("input#signup_1").click(function(){if($(this).attr("checked")){$("#sendCopyHidden").val(true);
}else{$("#sendCopyHidden").val("");
}});
if($("input#sendCopyHidden").length){if($("#sendCopyHidden").val()){$("input#signup_1").click();
}}enableTabRightImageRefillRx();
$("#buttonSendEmail").click(function(e){e.preventDefault();
$(this).addClass("graybutton");
$(this).attr("onclick","return false;");
var emailMsg=$("#rxEmailMessage").val().trim();
if(emailMsg!=""){emailMsg=emailMsg.replace(/"/g,"");
$("#rxEmailMessage").val(emailMsg);
}$("form#printHistoryEmailOverlayForm").submit();
});
});
var minMonth=1;
var maxMonth=12;
var minDay=1;
var maxDay=31;
var minYear=1900;
function validatePhoneNumber(phone1Id,phone2Id,phone3Id,errorMessage){var error=false;
var phonePart1=$(phone1Id).val().trim();
var phonePart2=$(phone2Id).val().trim();
var phonePart3=$(phone3Id).val().trim();
var phoneNumber=phonePart1+phonePart2+phonePart3;
$(phone1Id).parent().parent().children("div.error").html("");
$(phone1Id).removeClass("input-error");
$(phone2Id).removeClass("input-error");
$(phone3Id).removeClass("input-error");
if(isEmpty(phone1Id)){$(phone1Id).addClass("input-error");
error=true;
}if(isEmpty(phone2Id)){$(phone2Id).addClass("input-error");
error=true;
}if(isEmpty(phone3Id)){$(phone3Id).addClass("input-error");
error=true;
}if(!error&&!isValidPhoneNumber(phoneNumber)){$(phone1Id).addClass("input-error");
$(phone2Id).addClass("input-error");
$(phone3Id).addClass("input-error");
error=true;
}if(error){$(phone1Id).parent().parent().children("div.error").html(errorMessage);
}return error;
}function validateDateFields(monthId,dayId,yearId,monthMsg,dayMsg,YearMsg){var error=false;
var appendBefore="";
$(monthId).parent().parent().children("div.error").html("");
$(monthId).removeClass("input-error");
$(dayId).removeClass("input-error");
$(yearId).removeClass("input-error");
var monthValue=$(monthId).val();
var dayValue=$(dayId).val();
var yearValue=$(yearId).val();
if(isEmptyWithValue(monthId,$(monthId).attr("title"))||monthValue<minMonth||monthValue>maxMonth){$(monthId).addClass("input-error");
$(monthId).parent().parent().children("div.error").html(monthMsg);
appendBefore="<br/>";
error=true;
}if(isEmptyWithValue(dayId,$(dayId).attr("title"))||dayValue<minDay||dayValue>maxDay){$(dayId).addClass("input-error");
$(dayId).parent().parent().children("div.error").append(appendBefore+dayMsg);
appendBefore="<br/>";
error=true;
}if(isEmptyWithValue(yearId,$(yearId).attr("title"))||yearValue<minYear||yearValue>new Date().getFullYear()){$(yearId).addClass("input-error");
$(yearId).parent().parent().children("div.error").append(appendBefore+YearMsg);
error=true;
}return false;
}function validateInputField(fieldId,errorMessage){$(fieldId).parent().parent().children("div.error").html("");
$(fieldId).removeClass("input-error");
if(isEmptyWithValue(fieldId,$(fieldId).attr("title"))){$(fieldId).parent().parent().children("div.error").html(errorMessage);
$(fieldId).addClass("input-error");
return true;
}return false;
}function enableTabRightImageRefillRx(){$("body").on("focus","#firstName, #fName, #rxStausTab_fName, #refillexp_firstName",setFirstNameImage);
$("body").on("focus","#lastName, #lName, #rxStausTab_lName, #refillexp_lastName",setLastNameImage);
$("body").on("focus","#corpNum, #corpNumber, #rxStausTab_corpNumber, #refillexp_corpNumber",setCorpImage);
$("body").on("focus","#prescription, #prescription1, #rxStausTab_prescription, #refillexp_prescription",setPrescriptionImage);
$("body").on("focus","#dob-date, #dob-month, #dob-year, #rxStausTab_dobMonth, #rxStausTab_dobDay, #rxStausTab_dobYear, #refillexp_dobMonth, #refillexp_dobDay, #refillexp_dobYear",setDefaultImage);
}function enableTabRightImageCheckRefill(){}function getPharmacyLandingTabURL(tabId){var url=contextRoot;
if(tabId=="refillRxTab"){url+="/pharmacy/common/refillRxTab.jsp?source=refillRx";
}else{if(tabId=="checkRefillStatusTab"){url+="/pharmacy/common/refillStatusTab.jsp?source=refillStatus";
}else{if(tabId=="autoRefillTab"){url+="/pharmacy/common/autorefillTab.jsp?source=refillRx";
}else{if(tabId=="transferRxTab"){url+="/pharmacy/common/transferRxTab.jsp";
}else{if(tabId=="requestNewRxTab"){url+="/pharmacy/common/requestNewRxTab.jsp";
}}}}}if(url==contextRoot){return null;
}return url;
}function checkFormCurrentPharmacyRequiredField(){var isNotMissing=isRequiredFieldPopulated("#frmCurrentPharmacy input:text, input:radio");
if(isNotMissing){$("#currentPharmacy").removeClass("graybutton");
}else{$("#currentPharmacy").addClass("graybutton");
}}function setDefaultImage(){$("div.please-note-block div.prescription").css("background-position","18px 0px");
}function setFirstNameImage(){$("div.please-note-block div.prescription").css("background-position","-221px 0px");
}function setLastNameImage(){$("div.please-note-block div.prescription").css("background-position","-460px 0px");
}function setCorpImage(){$("div.please-note-block div.prescription").css("background-position","-699px 0px");
}function setPrescriptionImage(){$("div.please-note-block div.prescription").css("background-position","-938px 0px");
}function checkProfileNotifReqFields(){var isNotMissing=isRequiredFieldPopulated("form#profileNotfy input:checkbox");
if(isNotMissing){$("button#profileNotification").removeClass("graybutton");
}else{$("button#profileNotification").addClass("graybutton");
}}function checkAllReqTransPresStep3(){var isMissing=false;
var isAutoRefillDrug=false;
$("td.right-cell").find('input[type="radio"]:checked').each(function(index){if($(this).val()=="yes"){isAutoRefillDrug=true;
return;
}});
if($("#transferPresChkEmail").length&&$("#transferPresChkEmail").is(":checked")){$("#transferPresEmail").data("required",true);
$("#transferPresReEmail").data("required",true);
}else{$("#transferPresEmail").data("required",false);
$("#transferPresReEmail").data("required",false);
}if($("#transferPresChkPhone").length&&$("#transferPresChkPhone").is(":checked")){$("#transferPresPhonePart1").data("required",true);
$("#transferPresPhonePart2").data("required",true);
$("#transferPresPhonePart3").data("required",true);
}else{$("#transferPresPhonePart1").data("required",false);
$("#transferPresPhonePart2").data("required",false);
$("#transferPresPhonePart3").data("required",false);
}if($("#transferPresChkSms").length&&$("#transferPresChkSms").is(":checked")){$("#transferPresMobilePart1").data("required",true);
$("#transferPresMobilePart2").data("required",true);
$("#transferPresMobilePart3").data("required",true);
$("#transferPresChkAgreement").data("required",true);
}else{$("#transferPresMobilePart1").data("required",false);
$("#transferPresMobilePart2").data("required",false);
$("#transferPresMobilePart3").data("required",false);
$("#transferPresChkAgreement").data("required",false);
}if(isAutoRefillDrug){if($("#transferPresChkEmail").length||$("#transferPresChkPhone").length||$("#transferPresChkSms").length){$("#p_RefillNotificationRequiredParagraph").show();
$("#p_autoRefillParagraph3").hide();
if(!$("#transferPresChkEmail").is(":checked")&&!$("#transferPresChkPhone").is(":checked")&&!$("#transferPresChkSms").is(":checked")){isMissing=true;
}}}else{$("#p_RefillNotificationRequiredParagraph").hide();
$("#p_autoRefillParagraph3").show();
}if(!isRequiredFieldPopulated("#setupAutoRefill input:text, input:radio, input:checkbox")){isMissing=true;
}if(!isMissing){$("#transferPresNotfy").removeClass("graybutton");
}else{$("#transferPresNotfy").addClass("graybutton");
}}function validateRewardsPaymentForm(){var error=false;
var phoneNumberPart1=$("#phoneNumber1").val().trim();
var phoneNumberPart2=$("#phoneNumber2").val().trim();
var phoneNumberPart3=$("#phoneNumber3").val().trim();
var phoneNumber=phoneNumberPart1+phoneNumberPart2+phoneNumberPart3;
$("input#phoneNumber").val(phoneNumber);
return error;
}function loadCancelOverlayPage(){$("#OverlayDiv").load(contextRoot+"/pharmacy/common/canceloverlay.jsp");
$("#OverlayDiv").modal({minWidth:500,minHeight:195});
}function validatePatientFormFields(){var error=false;
var ghost="as on prescription bottle";
$("div#errorMessage").hide();
$("div#formErrorMessage").hide();
validateDate();
validateName("fName",ghost);
validateName("lName",ghost);
validateName("corpNum",ghost);
validatePrescription("prescription1",ghost);
if($("div#errorMessage").is(":visible")){error=true;
}return error;
}function validateDate(){var error=false;
var dtField="div#dob-date";
var divId="div#dob";
$("input#dob-month").removeClass("input-error");
$("input#dob-date").removeClass("input-error");
$("input#dob-year").removeClass("input-error");
$("div#errorMessage").hide();
$("div#errordob-month").hide();
$("div#errordob-date").hide();
$("div#errordob-year").hide();
var monthValue=$("input#dob-month").val();
var dayValue=$("input#dob-date").val();
var yearValue=$("input#dob-year").val();
if(isEmptyWithValue("input#dob-month","mm")||monthValue<1||monthValue>12){$("input#dob-month").addClass("input-error");
$("div#errordob-month").show();
error=true;
}if(isEmptyWithValue("input#dob-date","dd")||dayValue<1||dayValue>31){$("input#dob-date").addClass("input-error");
$("div#errordob-date").show();
error=true;
}if(isEmptyWithValue("input#dob-year","yyyy")||yearValue<1900||yearValue>new Date().getFullYear()){$("input#dob-year").addClass("input-error");
$("div#errordob-year").show();
error=true;
}if(error){$("div#errorMessage").show();
}}function validateName(id,ghost){var error=false;
var inputField="input#"+id;
if(isEmptyWithValue($(inputField),ghost)){error=true;
}if(error){showFieldError(id);
}else{hideFieldError(id);
}}function showFieldError(id){var inputField="input#"+id;
$($(inputField)).addClass("input-error");
$("div#error"+id).show();
$("div#errorMessage").show();
}function hideFieldError(id){var inputField="input#"+id;
$("div#error"+id).hide();
$($(inputField)).removeClass("input-error");
}function changePatient(pageName){window.location.href=pageName+"?pId="+$("#patientDependentDropdown").val();
}function removeDefaultValues(){if(jQuery(this).hasClass("ghost")){jQuery(this).attr("value","");
jQuery(this).removeClass("ghost");
jQuery(this).select();
}}function enableSmtOnNewPres(){var isEnab=false;
var getAllReq=$(".requiredVal");
for(i=0;
i<getAllReq.length;
i++){var currObj=$(".requiredVal").get(i);
if($(currObj).val()==""){isEnab=true;
}else{var titleValue=$(currObj).attr("title");
if($(currObj).val()==titleValue){isEnab=true;
break;
}else{if($(currObj).val()==""){isEnab=true;
break;
}}}}$("button#btnConfStepOne").prop("disabled",isEnab);
if(!isEnab){$("button#btnConfStepOne").removeClass("graybutton");
}else{$("button#btnConfStepOne").addClass("graybutton");
}}function loadUnenrollOverlay(patientId){var patient=patientId;
$("#OverlayDiv").load(contextRoot+"/pharmacy/common/unenrollOverlay.jsp?patientId="+patient);
$("#OverlayDiv").modal({minWidth:500,minHeight:195});
}function loadEligiblePrescriptions(){$("div#eligiblePrescription").show();
}function loadRxNotifyEditMode(){$("span#rxDisableMobileDiv").hide();
$("span#rxDisableEmailDiv").hide();
$("span#rxDisableConfEmailDiv").hide();
$("span#rxDisablePhoneDiv").hide();
$("div#rxEnableMobileDiv").show();
$("div#rxEnableEmailDiv").show();
$("div#rxEnableConfEmailDiv").show();
$("div#rxEnablePhoneDiv").show();
$("#rxRefillExpChkSms").removeAttr("disabled");
$("#rxRefillExpChkEmail").removeAttr("disabled");
$("#rxRefillExpChkPhone").removeAttr("disabled");
$("#isEditMode").val("true");
var isText=$("#rxRefillExpChkSms").is(":checked");
if(isText){$("#refillExpChkDisc").removeAttr("disabled");
$("#refillExpChkDiscBlock").css("visibility","visible");
}}function enableRefillExpressForRx(rxId){$.ajax({url:contextRoot+"/pharmacy/manage/enablerefillexpressforrx.jsp",type:"POST",dataType:"html",data:"rxId="+rxId,success:function(data){if(data.indexOf("success")!=-1){var anchor=$("#res_"+rxId);
anchor.attr("onclick","removeRefillExpressForRx("+rxId+");");
anchor.text("Remove from Auto-Refill");
}}});
}function removeRefillExpressForRx(rxId){$.ajax({url:contextRoot+"/pharmacy/manage/removerefillexpressforrx.jsp",type:"POST",dataType:"html",data:"rxId="+rxId,success:function(data){if(data.indexOf("success")!=-1){var anchor=$("#res_"+rxId);
anchor.attr("onclick","enableRefillExpressForRx("+rxId+");");
anchor.text("Set as Auto-Refill");
}}});
}function loadPrintRxHistoryEmailOverlay(){$("#OverlayDiv").modal({minWidth:735,minHeight:733});
}function validateConsentForm(){var firstName=$("#firstName").val().trim();
var lastName=$("#lastName").val().trim();
var dateOfBirth=$("#dateOfBirth").val().trim();
var phoneNumberPart1=$("#phonePart1").val().trim();
var phoneNumberPart2=$("#phonePart2").val().trim();
var phoneNumberPart3=$("#phonePart3").val().trim();
var phoneNumber=phoneNumberPart1+phoneNumberPart2+phoneNumberPart3;
var city=$("#city").val().trim();
var zip=$("#zip").val().trim();
var medicarePartBNumber=$("#medicarePartBNumber").val().trim();
var doctorName=$("#doctorName").val().trim();
$(".input-error").each(function(index){$(this).removeClass("input-error");
});
$("div.error").each(function(index){$(this).html("");
});
var isValidForm=true;
if($("#firstName").attr("readOnly")!="readonly"){if(firstName==""){$("#firstName").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxFirstName);
$("#firstName").addClass("input-error");
isValidForm=false;
}else{if(!isValidFirstName(firstName)){$("#firstName").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxFirstName);
$("#firstName").addClass("input-error");
isValidForm=false;
}}}if($("#lastName").attr("readOnly")!="readonly"){if(lastName==""){$("#lastName").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxLastName);
$("#lastName").addClass("input-error");
isValidForm=false;
}else{if(!isValidLastName(lastName)){$("#lastName").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxLastName);
$("#lastName").addClass("input-error");
isValidForm=false;
}}}if(dateOfBirth==""){$("#dateOfBirth").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxDateOfBirth);
$("#dateOfBirth").addClass("input-error");
isValidForm=false;
}else{if(!isValidDateOfBirthExpression(dateOfBirth)){$("#dateOfBirth").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxDateOfBirth);
$("#dateOfBirth").addClass("input-error");
isValidForm=false;
}else{var mm=Number(dateOfBirth.split("/")[0]);
var dd=Number(dateOfBirth.split("/")[1]);
var yyyy=Number(dateOfBirth.split("/")[2]);
var response=validateDateField(mm,dd,yyyy);
if(!response.isValid){isValidForm=false;
$("#dateOfBirth").addClass("input-error");
if(response.errorCode=="day.invalid"){$("#dateOfBirth").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxDay);
}else{if(response.errorCode=="month.invalid"){$("#dateOfBirth").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxMonth);
}else{if(response.errorCode=="year.invalid"){$("#dateOfBirth").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxYear);
}}}}}}if(phoneNumber==""){isValidForm=false;
$("#phonePart1").parent().parent().children("div.error").html(immunizationErrMsgs.InvalidRxPhoneNumber);
$("#phonePart1").addClass("input-error");
$("#phonePart2").addClass("input-error");
$("#phonePart3").addClass("input-error");
}else{if(!isValidPhoneNumber(phoneNumber)){isValidForm=false;
$("#phonePart1").parent().parent().children("div.error").html(immunizationErrMsgs.InvalidRxPhoneNumber);
$("#phonePart1").addClass("input-error");
$("#phonePart2").addClass("input-error");
$("#phonePart3").addClass("input-error");
}}if(city!=""&&!isValidCity(city)){$("#city").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxCity);
$("#city").addClass("input-error");
isValidForm=false;
}if(zip==""){$("#zip").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxZip);
$("#zip").addClass("input-error");
isValidForm=false;
}else{if(!isValidZip(zip)){$("#zip").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxZip);
$("#zip").addClass("input-error");
isValidForm=false;
}}if(medicarePartBNumber!=""&&!isValidMedicarePartBNumber(medicarePartBNumber)){$("#medicarePartBNumber").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxMedicare);
$("#medicarePartBNumber").addClass("input-error");
isValidForm=false;
}if(doctorName!=""&&!isValidDoctorName(doctorName)){$("#doctorName").parent().parent().children("div.error").html(immunizationErrMsgs.invalidRxDoctorName);
$("#doctorName").addClass("input-error");
isValidForm=false;
}if(isValidForm){printConsentForm();
}return isValidForm;
}function isValidFirstName(firstName){var regExp=/^[a-zA-Z ]{0,25}$/;
if(regExp.test(firstName)){return true;
}else{return false;
}}function isValidLastName(lastName){var regExp=/^[a-zA-Z ]{0,25}$/;
if(regExp.test(lastName)){return true;
}else{return false;
}}function isValidDateOfBirth(dateOfBirth){var regExp=/^\d{1,2}\/\d{1,2}\/\d{4}$/;
if(regExp.test(dateOfBirth)){var day=Number(dateOfBirth.split("/")[1]);
var date=new Date(dateOfBirth);
if(date&&date.getDate()==day){return true;
}return false;
}else{return false;
}}function validateDateField(month,day,year){var isValid=true;
var errorCode="";
var today=new Date();
var dd=today.getDate();
var mm=today.getMonth()+1;
var yyyy=today.getFullYear();
if(month>12||month<1){errorCode="month.invalid";
isValid=false;
}else{if(day>31||day<1){errorCode="day.invalid";
isValid=false;
}else{if(year<1900||year>yyyy){errorCode="year.invalid";
isValid=false;
}else{var inputDate=new Date(year,month-1,day);
if(inputDate.getDate()!=day){errorCode="day.invalid";
isValid=false;
}else{if(inputDate.getMonth()!=(month-1)){errorCode="month.invalid";
isValid=false;
}else{if(inputDate.getFullYear()!=year){errorCode="year.invalid";
isValid=false;
}else{if(year==yyyy&&month>mm){errorCode="month.invalid";
isValid=false;
}else{if(year==yyyy&&month==mm&&day>dd){errorCode="day.invalid";
isValid=false;
}}}}}}}}var response=new Object();
response.isValid=isValid;
response.errorCode=errorCode;
return response;
}function isValidDateOfBirthExpression(dateOfBirth){var regExp=/^\d{1,2}\/\d{1,2}\/\d{4}$/;
return regExp.test(dateOfBirth);
}function isValidPhoneNumber(phoneNumber){var regExp=/^\d{10}$/;
if(regExp.test(phoneNumber)){return true;
}else{return false;
}}function isValidCity(city){var regExp=/^[a-zA-Z ]{0,20}$/;
if(regExp.test(city)){return true;
}else{return false;
}}function isValidZip(zip){var regExp=/^\d{5}$/;
if(regExp.test(zip)){return true;
}else{return false;
}}function isValidDoctorName(doctorName){var regExp=/^[a-zA-Z ]{0,50}$/;
if(regExp.test(doctorName)){return true;
}else{return false;
}}function isValidMedicarePartBNumber(medicarePartBNumber){var regExp=/^[a-zA-Z0-9, ]{0,20}$/;
if(regExp.test(medicarePartBNumber)){return true;
}else{return false;
}}function isValidCorpNo(corpNo){var regExp=/^\d{1,5}$/;
if(regExp.test(corpNo)){return true;
}else{return false;
}}function isValidPrescriptionNo(prescriptionNO){var regExp=/^\d{1,10}$/;
if(regExp.test(prescriptionNO)){return true;
}else{return false;
}}function printConsentForm(){var firstName=$("#firstName").val();
var lastName=$("#lastName").val();
var dateOfBirth=$("#dateOfBirth").val();
var tokenArr=dateOfBirth.split("/");
var month=tokenArr[0];
var day=tokenArr[1];
var year=tokenArr[2];
var phoneNumberPart1=$("#phonePart1").val();
var phoneNumberPart2=$("#phonePart2").val();
var phoneNumberPart3=$("#phonePart3").val();
var phoneNumber=phoneNumberPart1+phoneNumberPart2+phoneNumberPart3;
var streetAddress=$("#streetAddress").val();
var city=$("#city").val();
var state=$("#state").val();
var zip=$("#zip").val();
var medicarePartBNumber=$("#medicarePartBNumber").val();
var doctorName=$("#doctorName").val();
var url=contextRoot+"/pharmacy/services/vaccineconsentform.jsp?";
url+="value8="+Base64.encode(firstName);
url+="&value9="+Base64.encode(lastName);
url+="&value10="+Base64.encode(month)+"&value11="+Base64.encode(day)+"&value12="+Base64.encode(year);
url+="&value13="+Base64.encode(phoneNumberPart1)+"&value14="+Base64.encode(phoneNumberPart2)+"&value15="+Base64.encode(phoneNumberPart3);
url+="&value16="+Base64.encode(streetAddress);
url+="&value17="+Base64.encode(city);
url+="&value18="+Base64.encode(state);
url+="&value19="+Base64.encode(zip);
url+="&value20="+Base64.encode(medicarePartBNumber);
url+="&value21="+Base64.encode(doctorName);
window.open(url,"");
}var nameReg=/[A-Za-z\s]+$/;
var numberReg=/[0-9]+$/;
var alphaNumberReg=/[0-9A-Za-z\s]+$/;
function validateUserName(){var userName=$(this).val();
if(!nameReg.test(userName)){userName=userName.replace(/[^A-Za-z\s]/g,"");
$(this).val(userName);
}else{return true;
}}function validateNumber(){var userNumber=$(this).val();
if(!numberReg.test(userNumber)){userNumber=userNumber.replace(/[^0-9]/g,"");
$(this).val(userNumber);
}else{return true;
}}function validateAlphaNumber(){var userValue=$(this).val();
if(!alphaNumberReg.test(userValue)){userValue=userValue.replace(/[^0-9A-Za-z]/g,"");
$(this).val(userValue);
}else{return true;
}}function validateProfilePrescInfo(){var error=false;
var ghost="as on prescription bottle";
$("div#errorMessage").hide();
$("div#formErrorMessage").hide();
$(".input-error").each(function(index){$(this).removeClass("input-error");
});
validateDate();
validateName("fName",ghost);
validateName("lName",ghost);
validateName("corpNum",ghost);
validateName("presc",ghost);
var phoneNumberPart3=$("input#phonePart3").val().trim();
$("div#errorphonePart3").hide();
if(phoneNumberPart3==""){$("input#phonePart3").addClass("input-error");
$("div#errorphonePart3").show();
$("div#errorMessage").show();
}if($("div#errorMessage").is(":visible")){error=true;
}return error;
}function loadInsuranceForm(){$("div#left-block-form").show();
$(this).hide();
return false;
}function loadProfileCancelOverlayPage(){$("#OverlayDiv").load(contextRoot+"/pharmacy/manageaccount/pharmacyprofilecanceloverlay.jsp");
$("#OverlayDiv").modal({minWidth:500,minHeight:195});
}function reArrangePrescr(){var presc_change=prescription_index_remove;
$("div#removeThis").nextAll().each(function(index){var currItem=$(this);
$(currItem).attr("id","prescription_number"+presc_change);
var currLabelItem=$(currItem).find("label");
$(currLabelItem).attr("for","presLabel"+presc_change);
$(currLabelItem).html("Prescription #"+presc_change+" <em>*</em></label>");
var currInputItem=$(currItem).find("input");
$(currInputItem).attr("id","prescription1"+presc_change);
var currInputItem=$(currItem).find("div.error");
$(currInputItem).attr("id","errorprescription1"+presc_change);
presc_change++;
});
}function validateProfileNotification(){var error=false;
$("div#errorMessage").hide();
$("div#formErrorMessage").hide();
$(".input-error").each(function(index){$(this).removeClass("input-error");
});
validateHipaaCheck();
validateNotificationCheck();
if($("div#errorMessage").is(":visible")){error=true;
}return error;
}function validateHipaaCheck(){var error=false;
if($("div#hippablock").is(":visible")){if($("input#hippaCK").is(":checked")){$("input#hippaTandC").val("checked");
}else{error=true;
$("div#errorMessage").show();
}}return error;
}function validateNotificationCheck(){var error=false;
var authType=$("input:radio[name=authmode]:checked").val();
if(authType=="undefined"){$("div#errorMessage").show();
error=true;
}if(authType=="phone"){var phoneType=$("input:radio[name=phoneauthmode]:checked").val();
if(phoneType=="undefined"){$("div#errorMessage").show();
error=true;
}}return error;
}function setUrlParam(){var storeId=$("#preferredStore").val();
if($("#nextPageLink")){var currHref=$("#nextPageLink").attr("href");
$("#nextPageLink").attr("href",currHref+storeId);
}}function validateTransferPrescriptionForm(){var error=false;
$("div#errorMessage").hide();
$("div#formErrorMessage").hide();
if(validateTransferPrescriptionDate()){error=true;
}if($("#fname").attr("readOnly")!="readonly"){if(validateTransferPrescriptionName("fname")){error=true;
}}if($("#lname").attr("readOnly")!="readonly"){if(validateTransferPrescriptionName("lname")){error=true;
}}if(validateTransferPrescriptionPhone()){error=true;
}if($("#zipcode").val()!=""&&validateZip("zipcode")){error=true;
}if(validateCityAddress("city")){error=true;
}if(validateCityAddress("address1")){error=true;
}return error;
}function isMissingMandatoryFieldsForCurrentPharmacy(){$("div#errorMessage").hide();
$("div#formErrorMessage").hide();
var name=$("input#pname").val().trim();
if(name==""){return true;
}var drugId=$("input#drugCount").val();
if(drugId==""){return true;
}var phonePart1=$("input#phonePart1").val().trim();
if(phonePart1==""){return true;
}var phonePart2=$("input#phonePart2").val().trim();
if(phonePart2==""){return true;
}var phonePart3=$("input#phonePart3").val().trim();
if(phonePart3==""){return true;
}var zip=$("input#zipcode").val().trim();
if(zip==""){return true;
}if(isMissingDrugNames()){return true;
}$("#morePrescriptions");
return false;
}function isMissingDrugNames(){var error=false;
$("input.drugNames").each(function(){var input=$(this).val().trim();
if(!error&&input==""){error=true;
}});
return error;
}function validateTransferPrescriptionCurrentPharmacy(){var error=false;
$("div#errorMessage").hide();
$("div#formErrorMessage").hide();
if(validateTransferPrescriptionName("pname")){error=true;
}var drugId=$("input#drugCount").val();
if(validateDrugName(drugId)){error=true;
}if(validateTransferPrescriptionPhone()){error=true;
}return error;
}function validateDrugName(drugId){var error=false;
var errorArray=new Array();
for(var i=1;
i<=drugId;
i++){var inputField="input#drugName"+i;
var inputDrugStrength="input#drugStrength"+i;
var inputDrugPrescription="input#drugPrescription"+i;
var inputRxDrugName="input#rxDrugName"+i;
var inputRxDrugStrength="input#rxDrugStrength"+i;
var inputRxDrugPrescription="input#rxDrugPrescription"+i;
if(isEmpty($(inputField))){errorArray[i-1]=inputField;
$($(inputField)).addClass("error");
if($("#drugNameError"+i).length==0){jQuery(inputField).parent().prepend("<div class='error' id='drugNameError"+i+"'> "+invalidDrugNameMsg+"</div");
}}else{$(inputRxDrugName).val($(inputField).val());
$(inputRxDrugStrength).val($(inputDrugStrength).val());
if($(inputDrugPrescription).val()==$(inputDrugPrescription).attr("title")){$(inputRxDrugPrescription).val("");
}else{$(inputRxDrugPrescription).val($(inputDrugPrescription).val());
}}}if(errorArray.length>0){error=true;
}return error;
}function validateTransferPrescriptionName(id){var error=false;
var inputField="input#"+id;
var name=$("#"+id).val().trim();
if(isEmpty($(inputField))){error=true;
}if(error){$($(inputField)).addClass("error");
$("div#error"+id).show();
}else{$("div#error"+id).hide();
$($(inputField)).removeClass("error");
}return error;
}function validateTransferPrescriptionDate(){var error=false;
var id="dob-date";
var dtField="div#dob-date";
var divId="div#dob";
var isRxUser=$("input#isRxUser").val();
if(isRxUser=="true"){var dateofbirth=$("input#dob-date").val();
if(!isValidDateOfBirthExpression(dateofbirth)){error=true;
}}else{var monthValue=$("#dob-month").val().trim();
var dayValue=$("#dob-date").val().trim();
var yearValue=$("#dob-year").val().trim();
var dateofbirth=monthValue+"/"+dayValue+"/"+yearValue;
if(isEmptyWithValue("input#dob-month","mm")||monthValue<1||monthValue>12){error=true;
$("div#errordob-month").show();
}else{$("div#errordob-month").hide();
}if(isEmptyWithValue("input#dob-date","dd")||dayValue<1||dayValue>31){error=true;
$("div#errordob-day").show();
}else{$("div#errordob-day").hide();
}if(isEmptyWithValue("input#dob-year","yyyy")||yearValue<1900||yearValue>new Date().getFullYear()){error=true;
$("div#errordob-year").show();
}else{$("div#errordob-year").hide();
}if(!error&&!isValidDateOfBirth(dateofbirth)){error=true;
$("div#error"+id).show();
}}if(error){$("input#dob-month").addClass("error");
$("input#dob-date").addClass("error");
$("input#dob-year").addClass("error");
}else{$("input#dob-month").removeClass("error");
$("input#dob-date").removeClass("error");
$("input#dob-year").removeClass("error");
$("div#errorMessage").hide();
$("div#error"+id).hide();
}return error;
}function validateTransferPrescriptionPhone(){var error=false;
var id="phone";
var dtField="div#phone";
var divId="div#phone";
var phonePart1=$("#phonePart1").val().trim();
var phonePart2=$("#phonePart2").val().trim();
var phonePart3=$("#phonePart3").val().trim();
var phoneNumber=phonePart1+phonePart2+phonePart3;
if(isEmpty("input#phonePart1")){error=true;
}else{if(isEmpty("input#phonePart2")){error=true;
}else{if(isEmpty("input#phonePart3")){error=true;
}else{if(!isValidPhoneNumber(phoneNumber)){error=true;
}}}}if(error){$("input#phonePart1").addClass("error");
$("input#phonePart2").addClass("error");
$("input#phonePart3").addClass("error");
$("div#error"+id).show();
}else{$("input#phonePart1").removeClass("error");
$("input#phonePart2").removeClass("error");
$("input#phonePart3").removeClass("error");
$("div#errorMessage").hide();
$("div#error"+id).hide();
}return error;
}function validateZip(id){var error=false;
var zip=$("#zipcode").val().trim();
var inputField="input#"+id;
if(isEmpty($(inputField))||!isValidZip(zip)){error=true;
}if(error){$($(inputField)).addClass("error");
$("div#error"+id).show();
}else{$("div#error"+id).hide();
$($(inputField)).removeClass("error");
}return error;
}function validateCityAddress(id){var error=false;
var inputField="input#"+id;
if(isEmpty($(inputField))){error=true;
}if(error){$($(inputField)).addClass("error");
$("div#error"+id).show();
}else{$("div#error"+id).hide();
$($(inputField)).removeClass("error");
}return error;
}function setReqFields(){var selVal=$(this).val();
if("other"==selVal){$("div.nameForRX").hide();
$("div.nameForNotRX").show();
$("div.nameForNotRX input").addClass("requiredVal");
$("div#hiddenNameVal").html("");
var dobLab=$("div.nameForNotRXDOB").parent().find("label");
var curText=$(dobLab).html()+"<em>*</em>";
$(dobLab).html(curText);
$(".clearOnOthr").val("");
enableSmtOnNewPres();
}else{var selName=$(this).find("option:selected").html();
var nameArray=selName.split("&nbsp;");
$("div.nameText").html(nameArray[1]+",&nbsp;"+nameArray[0]);
var patientId=selVal;
var divId="#ajaxResultForPatient";
$.ajax({url:contextRoot+"/pharmacy/newprescribe/getPatientDetails.jsp",dataType:"html",type:"POST",data:"patientId="+patientId+"&isRxUser=true",success:function(data){$(divId).html(data);
var newDiv=$(divId).find("#dummyForm");
$(divId).html($(newDiv).html());
$("div.nameForRX").show();
$("div.nameForNotRX").hide();
$("div.nameForNotRX input").removeClass("requiredVal");
$("div#hiddenNameVal input").each(function(){$(this).attr("priority","10");
});
var dobLab=$("div.nameForNotRXDOB").parent().find("label");
var curText=$(dobLab).html();
$(dobLab).html("Date of Birth");
}});
}return false;
}function setReqFieldsPresc(){var selVal=$(this).val();
var selAttrVal=$(this).find("option:selected").html();
var fullName=selAttrVal.split("&nbsp;");
$("#presFName").val("");
$("#presLName").val("");
if(fullName.length>0){$("#presFName").val(fullName[0]);
}if(fullName.length>1){$("#presLName").val(fullName[1]);
}if("other"==selVal){$("#presFName").val("");
$("#presLName").val("");
}return false;
}function validateProfileAuthenticationCode(){var error=false;
clearErrorMessage();
var authCode=$("input#authCode").val().trim();
if(authCode==""){$("input#authCode").addClass("input-error");
$("div#errorauthCode").show();
$("div#errorMessage").show();
}if($("div#errorMessage").is(":visible")){error=true;
}return error;
}function clearErrorMessage(){$("div#errorMessage").hide();
$("div#formErrorMessage").hide();
$(".input-error").each(function(index){$(this).removeClass("input-error");
});
}function removePrescription(){var divForHide=$(this).parents("div[id^='prescription_number']");
var id=$(divForHide).attr("id");
if(id!=undefined){prescription_index_remove=$(divForHide).attr("id").slice(-1);
$(divForHide).attr("id","removeThis");
reArrangePrescr();
$(divForHide).remove();
prescription_index--;
if(prescription_index<10){$(".addPrescription").show();
}var prescriptionId=$(this).data("pres_value");
var divId="#rxDetails";
if(prescriptionId!=""){$.ajax({type:"POST",url:contextRoot+"/pharmacy/refillRx/rxInclude.jsp",data:"removedRxId="+prescriptionId,success:function(data){$(divId).html(data);
}});
}}}function addDependent(){$(".dep"+dependent_counter).show();
$(".depRemove"+dependent_counter).show();
removeCount=dependent_counter-1;
$(".depRemove"+removeCount).hide();
dependent_counter++;
if(dependent_counter>10){$(this).hide();
}}function removeDependent(){depToHide=dependent_counter-1;
$(".dep"+depToHide).hide();
if(dependent_counter>5){removeCount=dependent_counter-2;
$(".depRemove"+removeCount).show();
}if(dependent_counter>4){dependent_counter--;
}else{$(this).hide();
}}function validateRefillStatusForm(){var firstName=$("#firstName");
var lastName=$("#lastName");
var dobMonth=$("#dobMonth");
var dobDay=$("#dobDay");
var dobYear=$("#dobYear");
var corpNumber=$("#corpNumber");
var prescriptions=$('input[id*="prescription"]');
var prescriptionErrMsgs=["1st","2nd","3rd","4th","5th","6th","7th","8th","9th","10th"];
var isValidForm=true;
$("div.error").each(function(index){$(this).html("");
});
$("input.error").each(function(index){$(this).removeClass("error");
});
if(isFieldEmpty("firstName")){firstName.addClass("error");
firstName.parent().children("div.error").html($("input#emptyRefillStatusFirstName").val());
isValidForm=false;
}else{if(isFieldEmpty("lastName")){lastName.addClass("error");
lastName.parent().children("div.error").html($("input#emptyRefillStatusLastName").valu());
isValidForm=false;
}}var today=new Date();
var dd=today.getDate();
var mm=today.getMonth()+1;
var yyyy=today.getFullYear();
var dobErrorMsg="";
if(isFieldEmpty("dobMonth")||isFieldEmpty("dobDay")||isFieldEmpty("dobYear")){dobErrorMsg=$("input#emptyRefillStatusDateOfBirth").val();
}if(dobErrorMsg==""){var month=Number(dobMonth.val());
var day=Number(dobDay.val());
var year=Number(dobYear.val());
var response=validateDateField(month,day,year);
if(!response.isValid){dobErrorMsg=dobErrorMsg+$("input#invalidRxDateOfBirth").val();
}}if(dobErrorMsg!=""){dobMonth.addClass("error");
dobDay.addClass("error");
dobYear.addClass("error");
dobMonth.parent().children("div.error").html(dobErrorMsg);
isValidForm=false;
}if(isFieldEmpty("corpNumber")){corpNumber.addClass("error");
corpNumber.parent().children("div.error").html($("input#emptyRefillStatusCorpNo").val());
isValidForm=false;
}else{if(!isValidCorpNo($("#corpNumber").val())){corpNumber.addClass("error");
corpNumber.parent().children("div.error").html($("input#invalidRxCorpNumber").val());
isValidForm=false;
}}$(prescriptions).each(function(index,element){if(isFieldEmpty($(this).attr("id"))){$(this).addClass("error");
$(this).parent().children("div.error").html("Please enter "+prescriptionErrMsgs[index]+" prescription number.").show();
isValidForm=false;
}else{if(!isValidPrescriptionNo($(element).val())){$(this).addClass("error");
$(this).parent().children("div.error").html($("input#invalidRxPrescription").val()+".").show();
isValidForm=false;
}}});
return isValidForm;
}function isFieldEmpty(id){var isEmpty=false;
var elem=$("#"+id);
var value=elem.val();
if(elem.data("ghost")!=undefined){if(elem.data("ghost")==value){isEmpty=true;
}}if(value==""||value.trim()==""){isEmpty=true;
}return isEmpty;
}function validateTransferPrescriptionNotificationFields(text,phone,email){var success=false;
$("div#notificationErrorMessage").hide();
$("div#transferPresErrorMobile").hide();
$("div#transferPresErrorPhone").hide();
$("div#transferPresErrorEmail").hide();
$("div#transferPresErrorReEmail").hide();
$("div#transferPresAgreement").hide();
$("div#transferPresErrorEmailType").hide();
$("input#transferPresMobilePart1").removeClass("error");
$("input#transferPresMobilePart2").removeClass("error");
$("input#transferPresMobilePart3").removeClass("error");
$("input#transferPresPhonePart1").removeClass("error");
$("input#transferPresPhonePart2").removeClass("error");
$("input#transferPresPhonePart3").removeClass("error");
$("input#transferPresEmail").removeClass("error");
$("input#transferPresReEmail").removeClass("error");
var isText=$("#"+text).is(":checked");
var isPhone=$("#"+phone).is(":checked");
var isEmail=$("#"+email).is(":checked");
var isAgreement=$("#transferPresChkAgreement").is(":checked");
var isAutoRefillDrug=false;
$("td.right-cell").find('input[type="radio"]:checked').each(function(index){if($(this).val()=="yes"){isAutoRefillDrug=true;
return;
}});
if(isAutoRefillDrug){if(!($("#transferPresChkEmail").length||$("#transferPresChkPhone").length||$("#transferPresChkSms").length)){success=false;
return success;
}else{if(!isEmail&&!isPhone&&!isText){$("div#notificationErrorMessage").show();
success=true;
}}}if(!success){if(isText){var phoneNumberPart1=$("#transferPresMobilePart1").val().trim();
var phoneNumberPart2=$("#transferPresMobilePart2").val().trim();
var phoneNumberPart3=$("#transferPresMobilePart3").val().trim();
var phoneNumber=phoneNumberPart1+phoneNumberPart2+phoneNumberPart3;
if(isEmpty("input#transferPresMobilePart1")){success=true;
}else{if(isEmpty("input#transferPresMobilePart2")){success=true;
}else{if(isEmpty("input#transferPresMobilePart3")){success=true;
}else{if(!isValidPhoneNumber(phoneNumber)){success=true;
}else{if(!isAgreement){success=true;
}}}}}if(success){if(isAgreement){$("input#transferPresMobilePart1").addClass("error");
$("input#transferPresMobilePart2").addClass("error");
$("input#transferPresMobilePart3").addClass("error");
$("div#transferPresErrorMobile").show();
}else{$("input#transferPresMobilePart1").addClass("error");
$("input#transferPresMobilePart2").addClass("error");
$("input#transferPresMobilePart3").addClass("error");
$("div#transferPresAgreement").show();
$("input#transferPresChkAgreement").addClass("error");
}}}if(isPhone){var phoneNumberPart1=$("#transferPresPhonePart1").val().trim();
var phoneNumberPart2=$("#transferPresPhonePart2").val().trim();
var phoneNumberPart3=$("#transferPresPhonePart3").val().trim();
var phoneNumber=phoneNumberPart1+phoneNumberPart2+phoneNumberPart3;
if(isEmpty("input#transferPresPhonePart1")){success=true;
}else{if(isEmpty("input#transferPresPhonePart2")){success=true;
}else{if(isEmpty("input#transferPresPhonePart3")){success=true;
}else{if(!isValidPhoneNumber(phoneNumber)){success=true;
}}}}if(success){$("input#transferPresPhonePart1").addClass("error");
$("input#transferPresPhonePart2").addClass("error");
$("input#transferPresPhonePart3").addClass("error");
$("div#transferPresErrorPhone").show();
}}if(isEmail){var email=$("#transferPresEmail").val().trim();
var reEmail=$("#transferPresReEmail").val().trim();
if(isEmpty("input#transferPresEmail")){$("div#transferPresErrorEmail").show();
$("input#transferPresEmail").addClass("error");
success=true;
}else{if(isEmpty("input#transferPresReEmail")){$("div#transferPresErrorReEmail").show();
$("input#transferPresReEmail").addClass("error");
success=true;
}else{if(!validateEmail(email)){$("div#transferPresErrorEmailType").show();
$("input#transferPresReEmail").addClass("error");
$("input#transferPresEmail").addClass("error");
success=true;
}else{if(email!=reEmail){$("div#transferPresErrorReEmail").show();
$("input#transferPresReEmail").addClass("error");
success=true;
}}}}}}return success;
}function populatePickUpTime(mon,day,year){var corpId=$("input#corpIdAjax1").val();
var divId="#ajaxPickUpTime";
$.ajax({url:contextRoot+"/pharmacy/common/pharmacyPickUpTime.jsp?day="+day+"&month="+mon+"&year="+year+"&corpId="+corpId,dataType:"html",type:"POST",data:"",success:function(data){$(divId).html(data);
$("select#pickUpTimeDD").change(populatePickUpDateTime);
populatePickUpDateTime();
}});
}function validatePrescription(id,ghost){var inputField="input[id^='"+id+"']";
$(inputField).each(function(){var error=false;
if(isEmptyWithValue($(this),ghost)){error=true;
}var currId=$(this).attr("id");
if(error){$(this).addClass("input-error");
$("div#error"+currId).show();
$("div#errorMessage").show();
}else{$(this).removeClass("input-error");
$("div#error"+currId).hide();
}});
}function populatePickUpDateTime(){var currValueDay=$("input#pickUpDay").val();
var currValueMon=$("input#pickUpMon").val();
var currValueYear=$("input#pickUpYear").val();
var pickUpTime=$("#pickUpTimeDD").val();
currValueDate=currValueMon+currValueDay+currValueYear+" "+pickUpTime;
$("input#dateTimeSelParam").val(currValueDate);
}function loadCancelRefillRevOverlayPage(){var prescriptionId=$(this).data("pres_value");
$("#OverlayDiv").load(contextRoot+"/pharmacy/common/canceloverlayrefillrev.jsp?prescriptionId="+prescriptionId);
$("#OverlayDiv").modal({minWidth:500,minHeight:195});
}function loadCancelRefillExpOverlayPage(){var prescriptionId=$(this).data("pres_value");
$("#OverlayDiv").load(contextRoot+"/pharmacy/common/cancleOverlayRefillExp.jsp?prescriptionId="+prescriptionId);
$("#OverlayDiv").modal({minWidth:500,minHeight:195});
}function removePrescriptionRefillRev(prescriptionId){var divId="#rxDetails";
if(prescriptionId!=""){$.ajax({type:"POST",url:contextRoot+"/pharmacy/refillRx/rxInclude.jsp",data:"removedRxId="+prescriptionId,success:function(data){closeGeneralModal();
var checkPresc=$(data).filter("div#rxPrescSuccess").attr("id");
if(checkPresc=="rxPrescSuccess"){$(divId).html(data);
$(".remove-pres-refill").click(loadCancelRefillRevOverlayPage);
}else{var checkPrescForIE=$(data).find("div#rxPrescSuccess").attr("id");
if(checkPrescForIE=="rxPrescSuccess"){$(divId).html(data);
$(".remove-pres-refill").click(loadCancelRefillRevOverlayPage);
}else{window.location.href=contextRoot+"/pharmacy/refillRx.jsp";
}}}});
}}function validateExpNtfyFields(id){$("div#notificationErrorMessage").hide();
$("div#errorrefillExpPhone").hide();
$("div#errorrefillExpMobile").hide();
$("div#errorrefillExpEmailAddress").hide();
$("div#errorrefillExpConfEmailAddress").hide();
$("div#errorMessage").hide();
$("div#errorrefillExpEmailMisMatch").hide();
$("div#error").hide();
var success=false;
var emailSuccess=false;
var phoneSuccess=false;
var textSuccess=false;
var isEmail=$("#rxRefillExpChkEmail").is(":checked");
var isPhone=$("#rxRefillExpChkPhone").is(":checked");
var isText=$("#rxRefillExpChkSms").is(":checked");
$(".input-error").each(function(index){$(this).removeClass("input-error");
});
if(id=="true"){if(!isEmail&&!isPhone&&!isText){$("div#notificationErrorMessage").show();
success=true;
}if(!success){if(isText){var phoneNumberPart1=$("#refillExpMob1").val().trim();
var phoneNumberPart2=$("#refillExpMob2").val().trim();
var phoneNumberPart3=$("#refillExpMob3").val().trim();
var phoneNumber=phoneNumberPart1+phoneNumberPart2+phoneNumberPart3;
if(isEmpty("input#refillExpMob1")){textSuccess=true;
}else{if(isEmpty("input#refillExpMob2")){textSuccess=true;
}else{if(isEmpty("input#refillExpMob3")){textSuccess=true;
}else{if(!isValidPhoneNumber(phoneNumber)){textSuccess=true;
}else{var isTextAck=$("#refillExpChkDisc").is(":checked");
if(!isTextAck){success=true;
$("div#errorMessage").show();
}}}}}if(textSuccess){$("input#refillExpMob1").addClass("input-error");
$("input#refillExpMob2").addClass("input-error");
$("input#refillExpMob3").addClass("input-error");
$("div#errorrefillExpMobile").show();
var isTextAck=$("#refillExpChkDisc").is(":checked");
if(!isTextAck){success=true;
$("div#errorMessage").show();
}}}if(isPhone){var phoneNumberPart1=$("#refillExpPhone1").val().trim();
var phoneNumberPart2=$("#refillExpPhone2").val().trim();
var phoneNumberPart3=$("#refillExpPhone3").val().trim();
var phoneNumber=phoneNumberPart1+phoneNumberPart2+phoneNumberPart3;
if(isEmpty("input#refillExpPhone1")){phoneSuccess=true;
}else{if(isEmpty("input#refillExpPhone2")){phoneSuccess=true;
}else{if(isEmpty("input#refillExpPhone3")){phoneSuccess=true;
}else{if(!isValidPhoneNumber(phoneNumber)){phoneSuccess=true;
}}}}if(phoneSuccess){$("input#refillExpPhone1").addClass("input-error");
$("input#refillExpPhone2").addClass("input-error");
$("input#refillExpPhone3").addClass("input-error");
$("div#errorrefillExpPhone").show();
}}if(isEmail){var email=$("#refillExpEmailAddress").val().trim();
var reEmail=$("#refillExpConfEmailAddress").val().trim();
if(isEmpty("input#refillExpEmailAddress")){$("input#refillExpEmailAddress").addClass("input-error");
$("div#errorrefillExpEmailAddress").show();
emailSuccess=true;
}if(isEmpty("input#refillExpConfEmailAddress")){$("input#refillExpConfEmailAddress").addClass("input-error");
$("div#errorrefillExpConfEmailAddress").show();
emailSuccess=true;
}}}}if(textSuccess||phoneSuccess||emailSuccess){success=true;
}return success;
}function getDrugNameStrings(index){var label="";
if(index===1){label="st";
}else{if(index===2){label="nd";
}else{if(index===3){label="rd";
}else{label="th";
}}}var html="";
var cancellink='<a href="#" class="system-link remove-transferpres" onclick="javascript:cancelPrescriptionLink('+index+');" id="presCancel'+index+'" data-id="'+index+'" data-page_value="currentPharmacy" data-pres_value="">'+'<img src="/img/common/close.png" width="15" height="17" alt="Close" /> </a>';
var part1="";
var drugStrengthText="'drugStrength"+index+"'";
var drugPrescriptionText="'drugPrescription"+index+"'";
var drugNameAutoTabHtml='onKeyUp="autotab(this,'+drugStrengthText+');"';
var drugStrengthAutoTabHtml='onKeyUp="autotab(this,'+drugPrescriptionText+');"';
if(index==1){part1='<div id="prescriptionCounter'+index+'"> <div class="field clearfix"> <label id="count'+index+'"> Drug Name <em>*</em> </label>'+'<input class="drugNames" id="drugName'+index+'" type="text" maxlength="35" value="" data-required="true" '+drugNameAutoTabHtml+"/>";
}else{part1='<div id="prescriptionCounter'+index+'"> <div class="field clearfix"> <label id="count'+index+'"> Drug Name <em>*</em> </label>'+'<input class="drugNames" id="drugName'+index+'" type="text" maxlength="35" value="" data-required="true" '+drugNameAutoTabHtml+"/>";
}var part2=' </div><div class="field clearfix"> <label for="">Drug Strength</label>'+' <input id="drugStrength'+index+'" type="text" maxlength="25" '+drugStrengthAutoTabHtml+'/> </div> <div class="field clearfix"> '+' <label for="presTransferLabel'+index+'">';
if(index==1){part2+=index+"st ";
}else{if(index==2){part2+=index+"nd ";
}else{if(index==3){part2+=index+"rd ";
}else{part2+=index+"th ";
}}}part2+="Prescription Number </label> "+'<input id="drugPrescription'+index+'" type="text" maxlength="10" class="titlemessagewithcss ghost" value="As on prescription bottle" title="As on prescription bottle" /> </div> </div>';
if(index===1){html=part1+part2;
}else{html=part1+cancellink+part2;
}return html;
}function loadDrugNameStrings(loadCount,values,errorIndexs,invalidDrugNameMsg){var setUpCount=parseInt(loadCount);
if(loadCount===""){setUpCount=1;
}transfer_prescription=setUpCount;
var html="";
for(var count=1;
count<=setUpCount;
count++){html=html+getDrugNameStrings(count);
}$("div#morePrescriptions").append(html);
setUpInitialData(setUpCount,values,errorIndexs,invalidDrugNameMsg);
if($("#tabDrugName").length){$("#drugName1").val($("#tabDrugName").val());
$("#drugStrength1").val($("#tabDrugStrength").val());
$("#drugPrescription1").val($("#tabDrugPrescreption").val());
$("#drugPrescription1").removeClass("ghost");
}}function setUpInitialData(setUpCount,values,errorIndexs,invalidDrugNameMsg){var jsonValues=eval("("+values+")");
for(var i=1;
i<=setUpCount;
i++){jQuery("#drugName"+i).val(jsonValues["drugName"+i]);
jQuery("#drugStrength"+i).val(jsonValues["drugStrength"+i]);
if(jsonValues["drugPrescription"+i]!=undefined){jQuery("#drugPrescription"+i).val(jsonValues["drugPrescription"+i]);
}}var errors=errorIndexs.split(",");
if(invalidDrugNameMsg===""){invalidDrugNameMsg="transferRxEmptyDrugName";
}for(var i=0;
i<=errors.length;
i++){if(errors[i]!=undefined){jQuery("#drugName"+errors[i]).addClass("error");
jQuery("#drugName"+errors[i]).parent().prepend("<div class='error' id='drugNameError"+errors[i]+"'> "+invalidDrugNameMsg+"</div");
}}}function loadSubmitData(){$.ajax({url:contextRoot+"/pharmacy/transfer/includes/drugDetailsSubmit.jsp",dataType:"html",type:"POST",data:"count="+transfer_prescription,success:function(data){jQuery("div#addedPrescriptions").html(data);
var html=$("form#drugStren").html();
console.log(html);
jQuery("div#addedPrescriptions").html(html);
jQuery("#drugCount").val(transfer_prescription);
for(var i=1;
i<=transfer_prescription;
i++){jQuery("#dname"+i).val(jQuery("#drugName"+i).val());
jQuery("#dStrength"+i).val(jQuery("#drugStrength"+i).val());
jQuery("#dPresc"+i).val(jQuery("#drugPrescription"+i).val());
}$("form#frmCurrentPharmacy").submit();
}});
}function cancelPrescriptionLink(pres_to_remove){jQuery("#prescriptionCounter"+pres_to_remove).remove();
adjustTransferPrecription(pres_to_remove);
if(transfer_prescription<10){$("a#addTransferPrescription").css("visibility","inherit");
}if($("#frmCurrentPharmacy").length>0){checkFormCurrentPharmacyRequiredField();
}}function adjustTransferPrecription(pres_to_remove){var toRemove=parseInt(pres_to_remove);
var displayCount=toRemove;
if(toRemove<=transfer_prescription){for(var i=toRemove+1;
i<=transfer_prescription;
i++){var drugname=jQuery("#drugName"+i).val();
var drugStrength=jQuery("#drugStrength"+i).val();
var drugPrescription=jQuery("#drugPrescription"+i).val();
jQuery("#prescriptionCounter"+i).remove();
$("div#prescriptionCounter"+(displayCount-1)).after(getDrugNameStrings(displayCount));
jQuery("#drugName"+displayCount).val(drugname);
jQuery("#drugStrength"+displayCount).val(drugStrength);
jQuery("#drugPrescription"+displayCount).val(drugPrescription);
displayCount++;
}}transfer_prescription--;
}function checkedManagePrescription(){jQuery(".give-access-container .cutomize-checkbox label").click(function(){var checkElement=jQuery(this).parent().find("[type=checkbox]");
var classCheckbox=$(checkElement).attr("class");
if(typeof classCheckbox==="undefined"||classCheckbox===""){$(checkElement).addClass("checked");
$(checkElement).attr("checked","checked");
}else{$(checkElement).removeClass("checked");
$(checkElement).removeAttr("checked");
}});
}function loadRemovePlanOverlay(formname){$("#OverlayDiv").load(contextRoot+"/pharmacy/common/removePlanOverlayPage.jsp?formname="+encodeURIComponent(formname));
$("#OverlayDiv").modal({minWidth:470,minHeight:304});
}function removeInsurance(formname){$("form#"+formname).submit();
closeGeneralModal();
}function isRequiredFieldPopulated(requiredFieldsSelector){var allReqPopulated=true;
$(requiredFieldsSelector).each(function(index,element){if($(this).data("required")!=undefined&&$(this).data("required")==true){var tagName=$(this).prop("tagName");
if(tagName=="SELECT"){if($(this).val()==""){allReqPopulated=false;
return false;
}}else{if(tagName=="INPUT"){var type=$(this).attr("type");
switch(type){case"text":if($(this).val()==""){allReqPopulated=false;
return false;
}else{var maxlength=$(this).attr("maxlength");
if($(this).hasClass("maxlenghvalue")){if($(this).val().length!=maxlength){allReqPopulated=false;
return false;
}}}break;
case"radio":var name=$(this).attr("name");
if($('input:radio[name="'+name+'"]:checked').length<=0){allReqPopulated=false;
return false;
}break;
case"checkbox":if(!$(this).is(":checked")){allReqPopulated=false;
return false;
}break;
}}}}});
return allReqPopulated;
}function toggleProfileSections(){var parentEleemnt=$(this).parent().parent();
var isExpClass=$(this).hasClass("expanded-bullet");
var contentsec=$(parentEleemnt).find(".section-subcontent");
$(contentsec).toggle();
if(isExpClass==true){$(this).removeClass("expanded-bullet").addClass("collapsed-bullet");
}else{$(this).removeClass("collapsed-bullet").addClass("expanded-bullet");
}return false;
}function validateRxRewardsStep1(){var allReqPopulated=true;
$("#rxRewards input:text, input:radio, input:checkbox").each(function(index,element){if($(this).data("required")!=undefined&&$(this).data("required")==true){var type=$(this).attr("type");
switch(type){case"text":if($(this).val()==""){allReqPopulated=false;
return false;
}break;
case"radio":var name=$(this).attr("name");
if($('input:radio[name="'+name+'"]:checked').length<=0){allReqPopulated=false;
return false;
}break;
case"checkbox":var name=$(this).attr("name");
if($('input:checkbox[name="'+name+'"]:checked').length<=0){allReqPopulated=false;
return false;
}break;
}}});
return allReqPopulated;
}function validateRxRewardsStep3(){var allReqPopulated=true;
$("#paymentForm input:text, input:radio, select").each(function(index,element){if($(this).data("required")!=undefined&&$(this).data("required")==true){var tagName=$(this).prop("tagName");
if(tagName=="SELECT"){if($(this).val()==""){allReqPopulated=false;
return false;
}}else{if(tagName=="INPUT"){var type=$(this).attr("type");
switch(type){case"text":if($(this).val()==""){allReqPopulated=false;
return false;
}break;
case"radio":var name=$(this).attr("name");
if($('input:radio[name="'+name+'"]:checked').length<=0){allReqPopulated=false;
return false;
}break;
case"checkbox":if(!$(this).is(":checked")){allReqPopulated=false;
return false;
}break;
}}}}});
return allReqPopulated;
}function removeExpPres(prescriptionId){var divId="#rxExpDetails";
if(prescriptionId!=""){$.ajax({type:"POST",url:contextRoot+"/pharmacy/refillexpress/refillExpressDetails.jsp",data:"removedRxId="+prescriptionId,success:function(data){var checkPresc=$(data).filter("div#rxExpPrescSuccess").attr("id");
if(checkPresc=="rxExpPrescSuccess"){$(divId).html(data);
$(".remove-express-pres").click(loadCancelRefillExpOverlayPage);
}else{window.location.href=contextRoot+"/pharmacy/refillexpress/refillExpressLanding.jsp";
}}});
closeGeneralModal();
}}function enableSbmtOnRewards(){var isEnab=true;
var getAllReq=$(".requiredValRewards");
for(i=0;
i<getAllReq.length;
i++){var currObj=$(".requiredValRewards").get(i);
if($(currObj).val().length>0){isEnab=false;
}else{isEnab=true;
break;
}}if(!isEnab){var radioBtnFam=$("input:radio[name='requiredValRadioFamily']").is(":checked");
var radioBtnGender=$("input:radio[name='requiredValRadioGender']").is(":checked");
var chkTerm=$("input:checkbox[name='termsNConditions']").is(":checked");
if(!radioBtnFam||!radioBtnGender||!chkTerm){isEnab=true;
}else{isEnab=false;
}}$("button#btnContRewards").prop("disabled",isEnab);
if(!isEnab){$("button#btnContRewards").removeClass("graybutton");
}else{$("button#btnContRewards").addClass("graybutton");
}}function printRxHistory(elem){if($("#fromDate").val()!=""&&$("#toDate").val()!=""){var url=$(elem).data("href");
url=url+"?fdate="+Base64.encode($("#fromDate").val());
url=url+"&tdate="+Base64.encode($("#toDate").val());
url=url+"&pid="+Base64.encode($("#patId").val());
window.open(url,"_blank");
}return false;
}function enableSbmtOnRewardStep3(){var isEnab=true;
var getAllReq=$(".requiredValRewardStep3");
for(i=0;
i<getAllReq.length;
i++){var currObj=$(".requiredValRewardStep3").get(i);
if($(currObj).val().length>0){isEnab=false;
}else{isEnab=true;
break;
}}if($('input:radio[name="creditCardType"]:checked').length<=0){isEnab=true;
}if(!isEnab){var getAllDD=$("select.requiredValRewDD");
for(i=0;
i<getAllDD.length;
i++){var ddExp=$(getAllDD[i]).val();
if(ddExp!=""){isEnab=false;
}else{isEnab=true;
break;
}}}$("button#paymentFormSubmit").prop("disabled",isEnab);
if(!isEnab){$("button#paymentFormSubmit").removeClass("graybutton");
}else{$("button#paymentFormSubmit").addClass("graybutton");
}}function expandThisTab(){var objToExp=$(this);
var currVal=$(this).find(".toExpand").val();
if(currVal=="true"){$(objToExp).find(".section-subcontent").show();
$(objToExp).find(".secTitle").removeClass("collapsed-bullet").addClass("expanded-bullet");
}}function validateEmail(email){var regExp=/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/;
if(regExp.test(email)){return true;
}return false;
}function autotabPhone(original,destination){$(original).val($(original).val().replace(/[^\d]/ig,""));
if(original.getAttribute&&original.value.length==original.getAttribute("maxlength")){$("input#"+destination).focus();
}}function autotabCity(original,destination){$(original).val($(original).val().replace(/[^a-zA-Z\s]*$/,""));
if(original.getAttribute&&original.value.length==original.getAttribute("maxlength")){$("input#"+destination).focus();
$("input#"+destination).removeClass("ghost");
}}function autotab(original,destination){if(original.getAttribute&&original.value.length==original.getAttribute("maxlength")&&original.value!=original.getAttribute("title")){$("input#"+destination).focus();
}}